### ISSUE TITLE
[Bug]: Cannot build NDK application

### ISSUE THREAD

**Issue by yazigegeda** [AndroidIDEOfficial/AndroidIDE#1011]
### What happened?

When I create a native project and run the build, it shows the following error:

Task :app:configureCMakeDebug[arm64-v8a]
C/C++: debug|arm64-v8a :/data/data/com.itsaky.androidide/files/home/android-sdk/cmake/3.18.1/bin/cmake[1]: syntax error: unexpected '('

> Task :app:configureCMakeDebug[arm64-v8a] FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] error when building with cmake using /storage/emulated/0/AndroidIDEProjects/MyApplication/app/src/main/cpp/CMakeLists.txt: Build command failed.
  Error while executing process /data/data/com.itsaky.androidide/files/home/android-sdk/cmake/3.18.1/bin/cmake with arguments {-H/storage/emulated/0/AndroidIDEProjects/MyApplication/app/src/main/cpp -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=21 -DANDROID_PLATFORM=android-21 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/data/data/com.itsaky.androidide/files/home/android-sdk/ndk/24.0.8215888 -DCMAKE_ANDROID_NDK=/data/data/com.itsaky.androidide/files/home/android-sdk/ndk/24.0.8215888 -DCMAKE_TOOLCHAIN_FILE=/data/data/com.itsaky.androidide/files/home/android-sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/data/data/com.itsaky.androidide/files/home/android-sdk/cmake/3.18.1/bin/ninja -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/storage/emulated/0/AndroidIDEProjects/MyApplication/app/build/intermediates/cxx/Debug/24284k5c/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/storage/emulated/0/AndroidIDEProjects/MyApplication/app/build/intermediates/cxx/Debug/24284k5c/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -B/storage/emulated/0/AndroidIDEProjects/MyApplication/app/.cxx/Debug/24284k5c/arm64-v8a -GNinja}
  
  /data/data/com.itsaky.androidide/files/home/android-sdk/cmake/3.18.1/bin/cmake[1]: syntax error: unexpected '('

### What's the expected behavior?

bug

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
See [this](https://github.com/MrIkso/AndroidIDE-NDK)

**Comment by itsaky** [comment]
You need to use CMake that is built to run on Android. See the link provided by @MrIkso.
