### ISSUE TITLE
[Bug]: .gitignore files is not generated for new projects

### ISSUE THREAD

**Issue by andihasan97** [AndroidIDEOfficial/AndroidIDE#1014]
### What happened?

The .gitignore file is not generated for the new project

### What's the expected behavior?

Fix the .gitignore file so it can be generated 

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BanDroid** [comment]
this is not a bug, because this is not intended to do, just create your own file named .gitignore after you initialize git repository. or change the label to `feature`.

**Comment by itsaky** [comment]
Actually, the IDE should automatically generate the `.gitignore` files. Otherwise, unwanted files may be accidentally staged to git by the user.
