### ISSUE TITLE
[Bug]: androidIDE freezing 

### ISSUE THREAD

**Issue by jonstudio8** [AndroidIDEOfficial/AndroidIDE#1041]
### What happened?

Sometimes AndroidIDE simply freezes and to go back to normal, just forcing it to stop. when I'm typing codes, or when I close a class through the options menu, it restarts itself.

### What's the expected behavior?

That it doesn't freeze.

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
It doesn't show an error, it just freezes AndroidIDE. this occurs when i am typing codes. and it simply freezes everything and to go back you have to force stop.
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
#1209.
