### ISSUE TITLE
[Bug]: Template No AndroidX Missing

### ISSUE THREAD

**Issue by Rystars** [AndroidIDEOfficial/AndroidIDE#1047]
### What happened?

Missing NoAndroidX project templates

### What's the expected behavior?

please return i need projects without androidX
![Screenshot_2023-06-17-09-17-25-429_com itsaky androidide](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/96302690/9aa08cbf-2dbc-452e-ba73-a55a633543ef)

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
no log
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Added in b4215bdb58d840712b0fab0254309bbab10964ea.

**Comment by gamecss** [comment]
> Added in [b4215bd](https://github.com/AndroidIDEOfficial/AndroidIDE/commit/b4215bdb58d840712b0fab0254309bbab10964ea).

Now the template called "No AndroidX" using AndroidX.
