### ISSUE TITLE
[Bug]: Editor color scheme issues

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1051]
### What happened?

Writing in the Android IDE, I noticed some color inconsistencies when I do certain things in my code, here are the main mistakes I noticed

1- Referencing an activity in a context turns its color white as you can see in the images below 

![Screenshot_20230619-104012](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/d11f9f83-2e0f-49f9-b3b4-116a459964b3)
![Screenshot_20230619-104005](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/90affdc7-b9da-421c-b1e5-3e2bf7fc98c6)

2 - Put variable and private variables as parameter of classes, data classes makes that contents of the parentheses blue, if i remove the leading parenthesis it seems to go back to normal colors but that would not compile

![Screenshot_20230619-103830](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/96df849a-46c8-45f2-98ca-dd5b98c436e4)

![Screenshot_20230619-103841](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/df4f545a-3017-4458-b355-80fb7b171d03)

3- Annotations color should be yellow in my opinion not only because it matches Android Studio, but because in certain cases it would differ from the color of other elements that are already blue too as in this example where the class name is already blue and the annotation parameter which is also blue this would make it more readable 

![Screenshot_20230619-103855](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/546e2b20-bc09-4961-b153-ddd767aa841a)

for color comparison
![Screenshot_20230619-002449](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/c013b29e-879b-4dcc-b17c-ebc87fa1b868)

I think these are the main points

### What's the expected behavior?

Colors do not suffer from these inconsistencies when writing code and make the code more beautiful visualization

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SuccessfulPerson2023** [comment]
AndroidIDE crash report
Manufacturer: samsung
Device: SM-G970U
ABI: arm64-v8a
SDK version: 31
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2235)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2268)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
- [ ]

**Comment by Rafael2616** [comment]
@SuccessfulPerson2023 Why did you make this issue in my issue comment? This has nothing to do with my problem.You must open another issue.

**Comment by Rafael2616** [comment]
It got much better, but the error 1 quoted still doesn't look so good

**Comment by Rafael2616** [comment]
It got much better for annotations an params, but the error 1 quoted still doesn't look so good
![Screenshot_20230716-080358](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/e531bf60-861a-45a0-bb23-c993ab5db927)

**Comment by itsaky** [comment]
I'll have to modify the grammar for this which could take some time. This is because that statement can have a qualified reference as well. For example :

```kotlin
this@Activity.field.method()
```

**Comment by Rafael2616** [comment]
Ok, I got it
