### ISSUE TITLE
[Bug]: No title

### ISSUE THREAD

**Issue by TechnicalStudioDeveloper** [AndroidIDEOfficial/AndroidIDE#1055]
### What happened?

IDK how this happened
![](https://dl.dropbox.com/s/q343rm4pbwz7yws/Screenshot_2023-06-21-12-19-40-731_com.itsaky.androidide.jpg?dl=0)

### What's the expected behavior?

Just rotated device to landscape and thus happened

### What version of AndroidIDE you're using?

v2.4.0

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This happens after device rotation?

**Comment by TechnicalStudioDeveloper** [comment]
> This happens after device rotation?

Just rotated orientation

**Comment by itsaky** [comment]
Unfortunately, I cannot reproduce this error. Please reopen if you know how to reproduce this.
