### ISSUE TITLE
[Bug]: Error Not Download data

### ISSUE THREAD

**Issue by moderGamer** [AndroidIDEOfficial/AndroidIDE#1056]
### What happened?

Error Not Download Sdk 

![Screenshot_20230621-210726_AndroidIDE](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/125615066/0fec90be-289f-4581-8a28-2ef423157658)

### What's the expected behavior?

In normal mode, nothing is downloaded, even the installation file is not downloaded from the site

### What version of AndroidIDE you're using?

v2.4.0

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Check your internet connection. Prefer using a a WiFi connection if possible.

I don't think there's any that we can do for this.

**Comment by moderGamer** [comment]
> 

I tested with everything, even with the filter breaker, the data is cut off in the middle of the download
@itsaky

**Comment by itsaky** [comment]
If the script isn't working, you can try to install the tools manually. Have a look at [this video](https://t.me/androidide_discussions/1/79442).
