### ISSUE TITLE
[MAINTENANCE] enable Discussions in project settings 

### ISSUE THREAD

**Issue by john-peterson** [AndroidIDEOfficial/AndroidIDE#1059]
Discussions under the address `/discussions` is better for long term visions and projects than shortnterm finger pointing FIX THIS demands (that made me lave the software industry) that was historically here under `/issues`

I have several long term visions I want to discuss

More fluid gestures and many other things. Happy to support my with a token sum. And lots of love

**Comment by itsaky** [comment]
I have enabled GitHub discussions. However, people are more active on the [Telegram group](https://t.me/androidide_discussions).
