### ISSUE TITLE
[Bug]:  Preview Layout

### ISSUE THREAD

**Issue by answer2** [AndroidIDEOfficial/AndroidIDE#1060]
### Brief Description
When using the "Preview Layout" function, the "include" tag in the "xml" file will be modified, and the set "layout" tag will also be removed, but will be replaced with "android:layout_width" and "android:layout_height" label, when the situation is not known, compiling the project throws an error

### 1.Before using the "Preview Layout" function
![Screenshot_2023-06-25-23-12-14-61_9ad8e654efd333b66ab21513aa36e36c](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/62866043/eb4d59ec-67ee-4e3e-8bde-000d63fa62ea)
### 2.After using the "Preview Layout" function
![Screenshot_2023-06-25-23-11-59-42_9ad8e654efd333b66ab21513aa36e36c](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/62866043/9a73d35d-8085-41d6-ad02-7d466b7ba6a8)
### 3.Compilation errors that occur
**In fact, the error caused by the layout cannot be found** 
![Screenshot_2023-06-25-23-17-45-04_9ad8e654efd333b66ab21513aa36e36c](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/62866043/6ceb9e46-0964-43e7-a7ed-ba1e1ce81bed)

### What's the expected behavior?

**This bug fix avoids unexpected compilation errors**

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
/storage/emulated/0/AndroidIDEProjects/YourProject/app/src/main/res/layout/activity_main.xml: Resource and asset merger: ERROR: [44 68 25] must include a layout file:///storage/emulated/0/AndroidIDEProjects/YourProject/app/src/main/res/layout/activity_main.xml

android.databinding.tool.processing.ScopedException: ERROR: [44 68 25] must include a layout file:///storage/emulated/0/AndroidIDEProjects/YourProject/app/src/main/res/layout/activity_main.xml
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in https://github.com/AndroidIDEOfficial/AndroidIDE/commit/8f4fdc3210093088dbf46bd7ec07c79014c56556.
