### ISSUE TITLE
[Features] Add Cancel action to Finding references job if it takes too long

### ISSUE THREAD

**Issue by john-peterson** [AndroidIDEOfficial/AndroidIDE#1061]
![Screenshot_20230625-181810](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/207571/5166168a-8e9d-4644-8579-86415859d045)

Looking at this for five minutes now

Desperately need it will do anything to get it to work

If it was async I could look at the log of what it is doing to get an idea if it will ever complete

**Comment by itsaky** [comment]
Added in 764a6fa8c2bdfc671007f7a68f8b1ec1b28e3481. The commit also fixes an issue where the dialog is shown indefinitely when finding references for types and members.
