### ISSUE TITLE
[Bug]: Android version 12 or 13 does not initialize properly

### ISSUE THREAD

**Issue by xiaoweibob** [AndroidIDEOfficial/AndroidIDE#1066]
### What happened?

Android version 12 or 13 does not initialize properly

### What's the expected behavior?

Expect to be able to use this software on Android 12 and 13

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Can you provide more information about this issue? I'm using Android 13 as well.

**Comment by xiaoweibob** [comment]
> 您能提供有关此问题的更多信息吗？我也在使用安卓 13。

Yes, when the project is opened, the project name is not displayed in the upper left corner, and it is not initialized.
The ide has these two errors.

Pointer tag for 0x7d71927340 was truncated, see 'https://source.android.com/devices/tech/debug/tagged-pointers'.

An error occurred initializing the project with Tooling API  null

**Comment by itsaky** [comment]
Okay, can you tell me what version of AndroidIDE you're using? This bug should not happen in v2.4.0-beta, you might be using an older version. Also, are you using JDK 11? If yes, please install JDK 17 from terminal and try again.

You can follow this guide on [getting started with AndroidIDE](https://androidide.com/blogs/getting-started/2023/03/15/getting-started-with-androidide/).

**Comment by xiaoweibob** [comment]
> 好的，你能告诉我你正在使用哪个版本的AndroidIDE吗？此错误不应发生在 v2.4.0-beta 中，您可能使用的是旧版本。另外，您是否正在使用JDK 11？如果是，请从终端安装 JDK 17，然后重试。
> 
> 您可以按照本指南开始使用[AndroidIDE](https://androidide.com/blogs/getting-started/2023/03/15/getting-started-with-androidide/)。

Thank you. I used jdk11 before and there is no problem after I changed it to 17
