### ISSUE TITLE
 getting "unexpected error"

### ISSUE THREAD

**Issue by Tanzin01** [AndroidIDEOfficial/AndroidIDE#1067]
### What happened?

while trying to add module into my project got an error. Here is the error text-

```
Task :projectb:initializeIDEProject
>>> PROJECT INITIALIZED <<<

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > AAPT2 .androidide Daemon #0: Unexpected error during link, attempting to stop daemon.
     This should not happen under normal circumstances, please file an issue if it does.
```
image if it helps-
![Screenshot_20230706_150023_AndroidIDE](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/41266558/136f5bcd-e9fa-4ef4-926c-1e4695bfe1b1)

### What's the expected behavior?

Expected behivour- i dont know a thing about thiis error. So i guess app compiles normally is the expected behivour¿

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Rerun the build `--stacktrace` enabled. This will show the stacktrace when the build fails.

You can enable this setting from Preferences -> Build & Run -> Additional Gradle arguments.
