### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by AmirrezaWeb** [AndroidIDEOfficial/AndroidIDE#1077]
### Feature description

Hi support elamutor
![Uploading Screenshot_۲۰۲۳۰۷۰۹-۲۲۲۹۳۰_AIDE.jpg…]()

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
I don't know what you're talking about. Reopen this issue when you have more information about the error/bug/suggestion.
