### ISSUE TITLE
[Bug]: library "libc.so.6" not found:

### ISSUE THREAD

**Issue by mesflit** [AndroidIDEOfficial/AndroidIDE#1093]
### What happened?

library "libc.so.6" not found:

### What's the expected behavior?

library "libc.so.6" not found:

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
library "libc.so.6" not found:
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mesflit** [comment]
> > library "libc.so.6" not found:
> 
> I'll need more than this. Please share the full error.
> 
> I think you might be trying to implement Room DB in your application. If this is the case, you can follow [this guide](https://androidide.com/blogs/room/2023/03/17/using-room-persistence-library-in-an-androidide-project/) to setup Room DB in AndroidIDE.

happened while compiling this project https://github.com/F0x1d/Sense

**Comment by itsaky** [comment]
It does use Room DB. Follow the guide and the error will be resolved. Reopen this issue if it doesn't.
