### ISSUE TITLE
[Bug]: AAPT2 error

### ISSUE THREAD

**Issue by BanDroid** [AndroidIDEOfficial/AndroidIDE#1094]
### What happened?

i run assembleDebug, and this happen, unfortunately this started to happen after i follow #cpaapt instruction in telegram, and then all my projects gives this error build.

### What's the expected behavior?

build should be success.

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
Jalankan task : [assembleDebug]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:dataBindingMergeDependencyArtifactsDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:packageDebugResources
> Task :app:mapDebugSourceSetPaths
> Task :app:mergeDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :app:checkDebugAarMetadata
> Task :app:parseDebugLocalResources
> Task :app:processDebugMainManifest
> Task :app:dataBindingGenBaseClassesDebug
> Task :app:processDebugManifest
> Task :app:javaPreCompileDebug
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets FROM-CACHE
> Task :app:compressDebugAssets
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:checkDebugDuplicateClasses
> Task :app:desugarDebugFileDependencies
> Task :app:processDebugManifestForPackage
> Task :app:mergeExtDexDebug
> Task :app:mergeDebugJniLibFolders FROM-CACHE
> Task :app:mergeLibDexDebug
> Task :app:mergeDebugNativeLibs NO-SOURCE
> Task :app:stripDebugDebugSymbols NO-SOURCE
> Task :app:validateSigningDebug
> Task :app:writeDebugAppMetadata
> Task :app:writeDebugSigningConfigVersions
AAPT2 .androidide Daemon #0: Unexpected error output: /data/data/com.itsaky.androidide/files/home/.androidide/aapt2[1]: can't open ￯﾿ﾽ: No such file or directory
AAPT2 .androidide Daemon #0: Unexpected error output: /data/data/com.itsaky.androidide/files/home/.androidide/aapt2[2]: syntax error: unexpected '('
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform core-1.8.0.aar (androidx.core:core:1.8.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/ef7e1b98507d7d4bda90d03defcba420/transformed/core-1.8.0.
         > AAPT2 .androidide Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.8.0.aar (androidx.core:core:1.8.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/ef7e1b98507d7d4bda90d03defcba420/transformed/core-1.8.0.
         > AAPT2 .androidide Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 11s
26 actionable tasks: 24 executed, 2 from cache
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Run with `--stacktrace` and share the build output.

**Comment by BanDroid** [comment]
> > Caused by: java.nio.file.NoSuchFileException: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/ef7e1b98507d7d4bda90d03defcba420/transformed/core-1.8.0/AndroidManifest.xml
> 
> Strange. You can try clearing the Gradle cache (`$HOME/.gradle/caches`).

still the same, here's the [logs](https://t.me/androidide_discussions/63782/81334)

**Comment by itsaky** [comment]
> Caused by: java.io.IOException: Process unexpectedly exit.

Can you try replacing the aapt2 file in the `$HOME/.androidide/` directory? You can find the aapt2 file in the [arch-specific assets](https://github.com/AndroidIDEOfficial/AndroidIDE/tree/dev/app/src). Or you can try the aapt2 binary from [this repository](https://github.com/itsaky/platform-tools) (see releases).

**Comment by BanDroid** [comment]
> > Caused by: java.io.IOException: Process unexpectedly exit.
> 
> Can you try replacing the aapt2 file in the `$HOME/.androidide/` directory? You can find the aapt2 file in the [arch-specific assets](https://github.com/AndroidIDEOfficial/AndroidIDE/tree/dev/app/src). Or you can try the aapt2 binary from [this repository](https://github.com/itsaky/platform-tools) (see releases).

thanks, it does work, i use aapt2 from [arch-specific assets](https://github.com/AndroidIDEOfficial/AndroidIDE/tree/dev/app/src).

the instruction in telegram group about #cpaapt should be changed to avoid this bug, idk why the aapt2 broke because of this, it does work in my old phone, seems there're breaking changes from the latest build-tools, probably.
