### ISSUE TITLE
[Bug]: SAF exception when accessing AndroidIDE dir.

### ISSUE THREAD

**Issue by BanDroid** [AndroidIDEOfficial/AndroidIDE#1095]
### What happened?

i could only access androidide home dir when androidide is running or in my recent opened apps.

![screenshot.jpg](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/68449470/364153b1-dced-480b-a95a-7bd64a0162d8)

### What's the expected behavior?

i could access androidide home dir even when androidide is not opened.

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Can you provide more information about your device?

**Comment by BanDroid** [comment]
> Can you provide more information about your device?

INFINIX MOBILITY LIMITED, Infinix X682B
Model: Infinix X682B
Manufacturer: INFINIX MOBILITY LIMITED
Board: Infinix-X682B
Device: Infinix-X682B
Product: X682B-GL
CPU Cores: 8
CPU Bit: 64-Bit
CPU Model: MT6769V/CB
Memory: Total 3.71 GB, Avail 1.73 GB
Storage: Total 52.07 GB, Avail 6.15 GB
Resolution: 720 * 1640 px / 320 dp
Screen Size: 2.7" * 6.2" / 6.8 Inches

INFINIX MOBILITY LIMITED, Infinix X682B
Android 10 / Q / API 29
Baseband Version: MOLY.LR12A.R3.MP.V118.11.P53
Build Number: X682B-H694ABT-Q-GL-220729V430
Build Fingerprint: Infinix/X682B-GL/Infinix-X682B:10/QP1A.190711.020/220729V430:user/release-keys
Linux Kernel Version: 4.14.141+
Http User Agent: Dalvik/2.1.0 (Linux; U; Android 10; Infinix X682B Build/QP1A.190711.020)

![Screenshot_20230715-112122](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/68449470/b753e6bf-6254-4f49-bdea-24b74c425c5e)

**Comment by BanDroid** [comment]
i've figured out, this is actually a system settings of my phone that blocked AndroidIDE $HOME dir to be able opened in background, the settings is `System -> App Launch -> (AndroidIDE (enable it)` then i could access the directory in my SAF without AndroidIDE running.

![Screenshot_20230720-201131](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/68449470/359112ae-133c-4ab7-b636-dc75ce0de266)
