### ISSUE TITLE
a

### ISSUE THREAD

**Issue by kongle233** [AndroidIDEOfficial/AndroidIDE#1096]
I really want to know how to build it in itself

**Comment by itsaky** [comment]
**We do not recommend building AndroidIDE in itself.** It may put a lot of load on your device's CPU.

**If** you're opening the project in AndroidIDE, I don't think you need to do anything special to achieve this. However, if you're building the AndroidIDE project in the AndroidIDE's terminal, you can use this command :
```bash
bash ./gradlew -Pandroid.aapt2FromMavenOverride=$HOME/.androidide/aapt2 :app:assembleDebug
```

The `-P...` argument is important here as it is needed to configure the Android Gradle Plugin to use the `aapt2` binary that can be executed on Android.


_Please give a proper title to the issues/PRs you create. See the [contribution guidelines](https://github.com/AndroidIDEOfficial/AndroidIDE/blob/dev/CONTRIBUTING.md)._

**Comment by kongle233** [comment]
> 

I followed what you say,but I failed to build it😭
