### ISSUE TITLE
[Bug]: xml 'android' autocomplete adds too much text

### ISSUE THREAD

**Issue by AlloMoondragon** [AndroidIDEOfficial/AndroidIDE#1100]
### What happened?

![Screenshot_20230712_105509_AndroidIDE~2](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/127817827/3ae8d6b7-62e6-47db-9f0f-fee94bde1ca6)
when typing 'android', it pops up this little window and selecting an option does not detect and replace the fragment of the word 'android' that triggers the sensor to offer suggestions.
So very often, selecting an option results in incorrection via reduplication of the initial word 'android' like the 'android:android' seen here
![Screenshot_20230712_104809_AndroidIDE~2](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/127817827/03fb431a-17e3-47ef-b824-26e4ac5cc32f)

For some reason, all but one thing I feel to improve is within my understanding and about this xml parsing and possibility referencing.  But I looked in Android Ide files and, while my knowledge of the language is farther, I do not know where I would be looking in Android Ide src for this part of it.  If you choose to tell me, I will type potential solutions and progress the path to submitting worthy edits to Android Ide.  But I am also content and could see it being potentially healthy to focus my scripting on what I make WITHIN Android Ide and purely state things, such as improveables and bugs, without then delving in to the script so you can better do it exactly as you want.

So I am stating these here so they are known, would look farther in to them myself, but unknown to me the location of the underlying code and also whether I, in general, should focus on your layer of construction or just what I make within it.
 
(minor but on same xml detection facet: I believe there is an ideal step when showing the list of possible matches for the checking if there have been any changes to which resource files there are, as android ide had to be reopened to have it detect and list drawables i had manually moved in to the folder while android ide was open)

### What's the expected behavior?

For it to all work better than expected and us to never feel annoyance at the app ~which can leak in to interactions with the good people who generously make it.  To raise the quality of every part to where there are no annoyances ~and every place makes people WANT to stay and WANT to find how they can support such a worthy project.  And then to escalate growth comfortably with higher ratio of growth of support to backsliding of support.

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
The issue has been fixed in 96c68ff32071b275ce510e71eb45adfc73f67080.

>  But I looked in Android Ide files and, while my knowledge of the language is farther, I do not know where I would be looking in Android Ide src for this part of it.

If you need help to get started with working on the AndroidIDE project itself, you can leave us a message on Telegram. We'll be happy to assist you.

> (minor but on same xml detection facet: I believe there is an ideal step when showing the list of possible matches for the checking if there have been any changes to which resource files there are, as android ide had to be reopened to have it detect and list drawables i had manually moved in to the folder while android ide was open)

As of now, AndroidIDE does not watch the file system for changes, so the resource table is not updated when you add a resource externally. However, you can re-sync the project and the resources will be updated (`Options menu` -> `Sync project`).
