### ISSUE TITLE
Spring boot support to android ide[Feature]: 

### ISSUE THREAD

**Issue by mohammad-ayan-008** [AndroidIDEOfficial/AndroidIDE#1111]
### Feature description

SpringBoot gradle project Support

### What version of AndroidIDE you're using?

v2.4.1

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
AndroidIDE is meant for Android app development only. This won't be added.
