### ISSUE TITLE
[Bug]: "text to search" string is not localized

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1117]
### What happened?

I couldn't find the string "text_to_search" in Crowdin to translate.
I downloaded the project and saw that this string was like "item" in the "resources" folder, but I can't test and create a pull , as I would have to uninstall the app just to verify this

Non-translatable string:
![Screenshot_20230717-195649~2](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/712924ae-66f9-43bc-8628-3706ca9bfd74)

As it is in the resource file:
![Screenshot_20230717-200452~2](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/4a4cb748-707c-4cbc-a387-41633b32c8f1)

### What's the expected behavior?

String be translatable to languages

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Those strings can be translated now.
