### ISSUE TITLE
[Bug]: Error with the IDE v2.5.1

### ISSUE THREAD

**Issue by esalessandrxx** [AndroidIDEOfficial/AndroidIDE#1123]
### What happened?

when updating to version 2.5.1 I am getting this error with the IDE

[ide_logs.txt](https://github.com/AndroidIDEOfficial/AndroidIDE/files/12080325/ide_logs.txt)

### What's the expected behavior?

use the ide normally

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
I forgot to release the maven dependencies. I have published them now. They should be available in a few minutes.

**Comment by esalessandrxx** [comment]
OK thanks
