### ISSUE TITLE
[Bug]: internet speed drops while downloading openjdk

### ISSUE THREAD

**Issue by Rystars** [AndroidIDEOfficial/AndroidIDE#1131]
### What happened?

internet speed drops while downloading openjdk

![Screenshot_2023-07-20-07-17-32-339_com itsaky androidide](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/96302690/901d811b-48b4-4e7b-bc24-3ff2c44e00fc)

### What's the expected behavior?

I hope that the internet speed can be increased like when downloading other files such as the sdk tool, so you don't have to wait too long

![Screenshot_2023-07-20-07-36-52-591_com miui videoplayer](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/96302690/9ccf727b-4172-403e-992a-dee1a97e66bb)

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
no log
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
I don't think we can fix this from our side. I reinstalled the IDE on my device and I get a good enough download speed for OpenJDK.

![Screenshot_2023-07-20-09-37-12-91_9ad8e654efd333b66ab21513aa36e36c](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/46931079/9fafea08-3d20-4651-9868-9ad608dcb0f0)
