### ISSUE TITLE
[Bug]: android-sdk extract error xz: (stdin): Unexpected end of input

### ISSUE THREAD

**Issue by mahdiware** [AndroidIDEOfficial/AndroidIDE#1138]
### What happened?

when installing got error

### What's the expected behavior?

when installing got error

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
android-sdk/licenses/android-sdk-license
android-sdk/licenses/android-sdk-preview-license
android-sdk/platforms/
android-sdk/platforms/android-33/
android-sdk/platforms/android-33/core-for-system-modules.jar
android-sdk/platforms/android-33/build.prop
android-sdk/platforms/android-33/android-stubs-src.jar
xz: (stdin): Unexpected end of input
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mahdiware** [comment]
oh sorry cannot work android-sdk

**Comment by itsaky** [comment]
> xz: (stdin): Unexpected end of input
> tar: Unexpected EOF in archive
> tar: Unexpected EOF in archive
> tar: Error is not recoverable: exiting now

The downloaded archive may have been corrupted. You can try to [manually install the tools](https://androidide.com/blogs/getting-started/2023/07/17/manually-installing-build-tools-in-androidide/).
