### ISSUE TITLE
[Bug]: Kotlin silll bulit into apk even though not any kotlin config in project

### ISSUE THREAD

**Issue by gamecss** [AndroidIDEOfficial/AndroidIDE#1139]
### What happened?

I'm going to make an app which compiled by AndroidIDE smaller. Then I was surprised to find that kotlin runtime incuded in the app. There aren't any kotlin in the project and most aren't any kotlin configure. The only config about kotlin is `kotlin.code.style=official` in gradle.properties. Tried remove it, no effect.

### What's the expected behavior?

Kotlin runtime not included in apk.

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
Starting build...
 Creating Idea project model...
 IdeaProject model created...
 Fetching Android project model...
 Building AndroidModule for project: app
 Fetching 'debug' dependencies
 Fetching project sync issues...
 Android project model for project 'app' created in 2954 ms

CONFIGURE SUCCESSFUL in 23s
运行任务 : [:app:assembleRelease]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.

> Task :app:preBuild UP-TO-DATE
> Task :app:preReleaseBuild UP-TO-DATE
> Task :app:dataBindingMergeDependencyArtifactsRelease
> Task :app:generateReleaseResValues FROM-CACHE
> Task :app:generateReleaseResources UP-TO-DATE
> Task :app:packageReleaseResources
> Task :app:javaPreCompileRelease FROM-CACHE
> Task :app:mapReleaseSourceSetPaths
> Task :app:checkReleaseAarMetadata
> Task :app:createReleaseCompatibleScreenManifests
> Task :app:extractDeepLinksRelease FROM-CACHE
> Task :app:parseReleaseLocalResources
> Task :app:processReleaseMainManifest
> Task :app:processReleaseManifest
> Task :app:mergeReleaseResources
> Task :app:extractProguardFiles
> Task :app:dataBindingGenBaseClassesRelease
> Task :app:mergeReleaseJniLibFolders FROM-CACHE
> Task :app:mergeReleaseNativeLibs NO-SOURCE
> Task :app:stripReleaseDebugSymbols NO-SOURCE
> Task :app:extractReleaseNativeSymbolTables NO-SOURCE
> Task :app:mergeReleaseNativeDebugMetadata NO-SOURCE
> Task :app:checkReleaseDuplicateClasses
> Task :app:processReleaseJavaRes NO-SOURCE
> Task :app:mergeReleaseArtProfile
> Task :app:mergeReleaseShaders FROM-CACHE
> Task :app:compileReleaseShaders NO-SOURCE
> Task :app:generateReleaseAssets UP-TO-DATE
> Task :app:mergeReleaseAssets FROM-CACHE
> Task :app:compressReleaseAssets FROM-CACHE
> Task :app:collectReleaseDependencies
> Task :app:sdkReleaseDependencyData
> Task :app:writeReleaseAppMetadata
> Task :app:writeReleaseSigningConfigVersions
> Task :app:processReleaseManifestForPackage
> Task :app:mergeReleaseJavaResource
> Task :app:processReleaseResources
> Task :app:compileReleaseJavaWithJavac NO-SOURCE
> Task :app:mergeReleaseGeneratedProguardFiles
> Task :app:optimizeReleaseResources
> Task :app:lintVitalAnalyzeRelease
> Task :app:lintVitalReportRelease
> Task :app:lintVitalRelease
> Task :app:minifyReleaseWithR8
> Task :app:compileReleaseArtProfile FROM-CACHE
> Task :app:packageRelease
> Task :app:createReleaseApkListingFileRedirect
> Task :app:assembleRelease

BUILD SUCCESSFUL in 1m 42s
36 actionable tasks: 28 executed, 8 from cache
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Skaldebane** [comment]
Modern Android apps will inevitably have some Kotlin in them even if they don't use it, because of other dependencies.

Idk exactly what you mean by Kotlin "runtime", but it's natural to see some parts of the Kotlin standard library being part of your app when dependenices use them, and the size effect is small (if they aren't coming from Kotlin stdlib, the libraries would rewrite the same code manually anyways, so it shouldn't make much of a difference in size).

Hope this answers your concerns!

**Comment by itsaky** [comment]
As @Skaldebane mentioned, the libraries that your project depends on must be using Kotlin so it is included in your project as a [transitive dependency](https://docs.gradle.org/current/userguide/dependency_management_terminology.html#sub:terminology_transitive_dependency).

For debug builds, the [`logsender`](https://github.com/AndroidIDEOfficial/AndroidIDE/tree/dev/logsender) dependency is included in the projects, which is written in Java and has only one dependency ([the AndroidIDE Logger](https://github.com/AndroidIDEOfficial/AndroidIDE/tree/dev/logger)). AndroidIDE does not add any other external dependencies to the projects.
