### ISSUE TITLE
[Question]: Become a Crowdin Proofreader

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1144]
### Feature description

As the translations into Portuguese were not done by a native speaker, and because it is a very complex language, many approved Crowdin strings do not make such complete sense, that's why I wanted to become a proofreader for the Portuguese language, which in Crowdin is Portuguese from Portugal, but they are in Brazilian Portuguese.
How do I know that @itsaky It shouldn't waste time approving strings, so if I become proofreader can I approve them on my own 
I sent you a message on Crowdin, there's my nick, if you need any data like email, just ask there 

Direct link to messages
https://crowdin.com/messages/

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This should not be reported here. You can ask about these things on Telegram (preferred) or on Crowdin (as you did).
