### ISSUE TITLE
[Bug]: No AndroidX template but still implements AndroidX library

### ISSUE THREAD

**Issue by Rystars** [AndroidIDEOfficial/AndroidIDE#1146]
### What happened?
**_No AndroidX template but still implements AndroidX library_**
![Screenshot_2023-07-24-18-09-55-434_com rhmsoft code](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/96302690/43c91485-f757-46d6-b85f-3f5c5611381a)

one more dependency android build tool does not use the latest version, namely version 8.0.2, 
and the version that was used when you first made it, namely 8.0.0

AndroidIDE version that I use is 2.5.1

### What's the expected behavior?

the template doesn't use androidX fully

### What version of AndroidIDE you're using?

v2.5.0

### Relevant log output

```shell
no log
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in 167af9c143ed3a6b18a38603ffceba2dbf98eb9f.
