### ISSUE TITLE
Template build failing

### ISSUE THREAD

**Issue by JuliaAllen1** [AndroidIDEOfficial/AndroidIDE#1148]
Android 13. Project is Java, w/ Android 10 minimum SDK. Fresh install on S22. Basic template build produces the following:
```
Run tasks : [assembleDebug]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > Failed to find Build Tools revision 33.0.3

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s

```

**Comment by ThatMG393** [comment]
Just change it to `33.0.1`

**Comment by PranavPurwar** [comment]
or install the newer sdk

**Comment by itsaky** [comment]
Downgrading the version to `33.0.2` or upgrading it to `34.0.0` (or later) should fix this this issue.

**Comment by wuxianggujun** [comment]
I want to know how to do it, I use idesetup -s 34.0.4 -c, or idesetup -s 34.0.0 -c. Still setup -s 33.0.1 -c -j 17

**Comment by wuxianggujun** [comment]
I carefully checked the directory and obviously downloaded '''~/android-sdk/build-tools $ ls
34.0.0 34.0.4', but still compiled with 33.0.0.3

**Comment by Rafael2616** [comment]
just remove the 'buildToolsVersion' line from your gradle file, if your project is new just build a new one using that version or newer 

https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/6049678030

**Comment by wuxianggujun** [comment]
Android hasn't been playing for too long, only to find out that I forgot to modify it. No wonder installed. The SDK used has always been 33. embarrassed

**Comment by Queedity** [comment]
i cant understand    i have same issue please help me 
i downloaded sdk v34.0.0   (+34.0.4 in build tools folder)
but with creating new project or deleting setting.gradle file, the build process log  steel shows 33.0.0.3 version😐  i couldn't understand "just remove the 'buildToolsVersion' line from your gradle file"🥲.   also i looked at that link

**Comment by Rafael2616** [comment]
> i cant understand    i have same issue please help me 
> i downloaded sdk v34.0.0   (+34.0.4 in build tools folder)
> but with creating new project or deleting setting.gradle file, the build process log  steel shows 33.0.0.3 version😐  i couldn't understand "just remove the 'buildToolsVersion' line from your gradle file"🥲.   also i looked at that link

Go to your project > app > build.gradle [.kts] > look for buildToolsVersion in 'android' block > remove it. 

If you are unable to do this, try downloading the latest debug version from GitHub Actions as this is already implemented by default when creating a new template with these versions
