### ISSUE TITLE
[Feature]: Add a section to support offline gradle build from internal storage

### ISSUE THREAD

**Issue by Memehub-Network** [AndroidIDEOfficial/AndroidIDE#1155]
### Feature description

It has been hard for me to continue creating my project after my pc broke.I've tried using this app from the go:
1.I installed all the necessary tools
2.I ran a successful gradle build

But the real problem is that I don't always have a steady internet connection as I am using internet from a mobile carrier.

How can I just build the app without requiring every time an internet connection?.
I have downloaded gradle 7.2.0 file ready but I can't seem to figure out how to install it.
Please kill my problems if it helps.🙏

### What version of AndroidIDE you're using?

v2.4.1

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
You can enable the `--offline` flag in preferences to make Gradle work fully offline. However, this may result in build failures if dependencies are not already downloaded.

You can also configure AndroidIDE to use a fixed Gradle distribution to build all of your projects. See [this message](https://t.me/androidide_discussions/1/83816). This will ignore the Gradle distribution version specified in Gradle wrapper properties and hence it won't be downloaded at all. Please note that this may result in build failures as projects may not be compatible with some Gradle versions.

You can configure both of these in `IDE Preferences -> Build & Run`.
