### ISSUE TITLE
[Feature]: Informative about using logsender

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1157]
### Feature description

I see a lot of people are wondering how to use logsender, how to add logsender to the project and questions like that, so I think a simple text in the app logs tab will reduce doubts about how to use the log sender, here is a capture, it is even more didactic for the user only
In the example, if there were no logs, this message would appear and from the moment they were captured, the message would disappear

![Picsart_23-07-28_11-56-21-185](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/9232d6e8-e72a-402f-a0ac-82a6465b906b)

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafael2616** [comment]
Updated version, could you put the link to the website page referring to logsender

**Comment by Rafael2616** [comment]
Updated version, could you put the website link referring to logsender

Updated
![Picsart_23-07-28_13-13-38-063.jpg](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/0868ca23-c65e-45b8-80ad-7f40a983fe26)

**Comment by john-peterson** [comment]
I can't find the link anywhere 

Blank page

https://github.com/AndroidIDEOfficial/AndroidIDE/wiki/Logsender
