### ISSUE TITLE
[Bug]: "Connection refused..." errors from logsender

### ISSUE THREAD

**Issue by gituser1000000** [AndroidIDEOfficial/AndroidIDE#1183]
### What happened?

v2.5.2-beta
App logs view is spamming with connection-refused errors.

From app logs:
08-05 11:48:47.163 25101 25101 D  NetworkSecurityConfig_    No Network Security Config specified, using platform default
08-05 11:48:47.163 25101 25101 D  NetworkSecurityConfig_    No Network Security Config specified, using platform default
...
08-05 11:48:47.403 25101 25101 I  LogSender_                 Connecting to log receiver 
08-05 11:48:47.410 25101 25127 I  LogSender_                 Starting to read logs... 
08-05 11:48:47.497 25101 25113 E  ple.new252test_           failed to connect to jdwp control socket: Connection refused
08-05 11:48:48.248 25101 25113 E  ple.new252test_           failed to connect to jdwp control socket: Connection refused
...

### What's the expected behavior?

See actual log messages from the debug app

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
LogReceiverImpl           I   Connecting to client com.example.new252test2 
LogReceiverImpl           I   Total clients connected: 1 
MultiLogSenderHandler     I   A log sender has been connected 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
LogReceiverImpl           I   Disconnecting from client: 'com.example.new252test2' 
LogSenderHandler          D   Closing log sender handler... 
LogReceiverImpl           I   Total clients connected: 0 
LogSenderHandler          E   An error occurred while reading from socket 
LogSenderHandler          E  java.net.SocketException: Socket closed
LogSenderHandler          E  	at java.net.SocketInputStream.socketRead0(Native Method)
LogSenderHandler          E  	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
LogSenderHandler          E  	at java.net.SocketInputStream.read(SocketInputStream.java:176)
LogSenderHandler          E  	at java.net.SocketInputStream.read(SocketInputStream.java:144)
LogSenderHandler          E  	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
LogSenderHandler          E  	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
LogSenderHandler          E  	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
LogSenderHandler          E  	at java.io.InputStreamReader.read(InputStreamReader.java:184)
LogSenderHandler          E  	at java.io.BufferedReader.fill(BufferedReader.java:172)
LogSenderHandler          E  	at java.io.BufferedReader.readLine(BufferedReader.java:335)
LogSenderHandler          E  	at java.io.BufferedReader.readLine(BufferedReader.java:400)
LogSenderHandler          E  	at com.itsaky.androidide.services.log.LogSenderHandler.run(Unknown Source:39)
LogSenderHandler          E
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
> 08-05 11:48:47.497 25101 25113 E ple.new252test_ failed to connect to jdwp control socket: Connection refused

I don't think this is related to AndroidIDE. None of AndroidIDE components use JDWP. I'll look into the other issue you mentioned.

**Comment by gituser1000000** [comment]
I found out that if I turn on "USB Debugging" then the spamming errors stop. I don't remember seeing this as a requirement for using AndroidIDE (with app logs.) If docs for the IDE had it somewhere, I've apparently missed that.

Even if AndroidIDE does not use JDWP as you've said, the app logs feature seems to require it, hence, it has something to do with the IDE then right? :)

What if I prefered not to turn on USB Debugging? No other options?

**Comment by itsaky** [comment]
Are you using LineageOS? This seems to happen in debug builds of LineageOS 18.1 (maybe newer as well?). [Source](https://gitlab.com/LineageOS/issues/android/-/issues/4445).

**Comment by itsaky** [comment]
The `SocketException` was being incorrectly logged when the connection to logsender in the client application was closed. The above commit should fix it.

I'm not sure about the JDWP issue. It didn't occur on my test device.

**Comment by gituser1000000** [comment]
> Are you using LineageOS?

No, it's just a regular android 11, 64bit device with stock everything.

I've also tried on another device by the same maker, only with Android 12, and USB debugging disabled. It didn't spam that JDWP Connection refused error. Maybe you could test and confirm that it (is / or not) the case, and possibly a fix?

**Comment by itsaky** [comment]
The message is being logged from the ADB connection client in the Android system. [This](https://cs.android.com/android/platform/superproject/main/+/main:packages/modules/adb/libs/adbconnection/adbconnection_client.cpp;drc=305095b94db7aa46757a0eb35c100c55d785cb83;l=165) is the line that prints the message. It uses the `PLOG` macro to the message whose behavior is defined [here](https://cs.android.com/android/platform/superproject/main/+/main:system/libbase/include/android-base/logging.h;drc=087b6880b76b9034c5b098d94b7b7a1208c2a40b;l=33).

I don't think we could fix this from our side.

**Comment by gituser1000000** [comment]
So could we confirm that it's Android 11 in general, or only this particular Android 11 that I have?

**Comment by itsaky** [comment]
Honestly, I don't know much about this. That piece of code seems to be included in the latest Android as well. 

There might some configuration issues with the AOSP build that is installed on your device which may be why you're seeing this error on that specific device.

This issue can be closed in my opinion.

**Comment by gituser1000000** [comment]
Oh well... at least the other socket exception was noticed and got fixed.
