### ISSUE TITLE
[Bug]:Can't use Recyclerview 

### ISSUE THREAD

**Issue by TanTai97o** [AndroidIDEOfficial/AndroidIDE#1185]
### What happened?

![Screenshot_20230806_160240](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/107351062/b3193fe1-a839-4f98-ac74-3bfaec7ecb67)

I can't use Recyclerview, I use this code as on Youtube tutorial but got error

If this is an error from the application please fix it, if it is from me please help me to fix it

### What's the expected behavior?

If this is an error from the application please fix it, if it is from me please help me to fix it

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TanTai97o** [comment]
![Screenshot_20230806_161155](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/107351062/a95224a8-0bf1-41e9-9300-bb23448f9b01)

I re-uploaded this image because I wrote the wrong codes in the image above: <PostAdapter.ViewHolder>

**Comment by PranavPurwar** [comment]
Not a bug in the IDE. You haven't imported `ViewHolder` class or just imported the wrong one.

**Comment by BanDroid** [comment]
it is said you haven't override the method because you haven't give the right return value for each overrided method, it still gives error until you finished the logic code.

**Comment by TanTai97o** [comment]
Thank you very much, I solved the problem

**Comment by TanTai97o** [comment]
> Không phải lỗi trong IDE. Có thể bạn chưa nhập `ViewHolder`lớp hoặc chỉ nhập sai và làm sai chữ ký phương thức

Thank you very much, I solved the problem
