### ISSUE TITLE
[Bug]: loading initialize project can't stop

### ISSUE THREAD

**Issue by Rystars** [AndroidIDEOfficial/AndroidIDE#1197]
### What happened?

https://github.com/AndroidIDEOfficial/AndroidIDE/assets/96302690/66627af5-022d-4640-b1f8-115efc303184

loading initialize project can't stop and when I force the build of the project, the dependencies in the project are not detected

### What's the expected behavior?

fix this bug

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
no log
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
What is the exact version of AndroidIDE you're using? You can find this information in AndroidIDE's "About" screen or in the system's "App Info" screen.

**Comment by Rystars** [comment]
v2.5.2 (debug builds) but now it's not buggy anymore, I don't know what caused the bug to appear and then disappear again

**Comment by itsaky** [comment]
If you face the error again, please reopen this issue.

**Comment by itsvks19** [comment]
I can reproduce this issue.

**Comment by itsaky** [comment]
> I can reproduce this issue.

Please provide step-by-step instructions for the same.

**Comment by Rystars** [comment]
ok

**Comment by Rafael2616** [comment]
This error happened to me when resizing the app (switching from split screen to full screen or vice versa) But after 'rework-tooling-api' this no longer happens and I can resize the app at any time, I don't know if the cause for you is the same

**Comment by itsaky** [comment]
This used to happen after a configuration change. But as @Rafael2616 said (and I can confirm), this doesn't occur on after updates to the tooling API (even with the steps that @itsvks19 provided to reproduce this issue).

If the occurs again, feel free to reopen this issue.
