### ISSUE TITLE
[Bug]: Some untranslated texts in build output name

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1203]
### What happened?

This is a low priority error, just that some strings shown below are not appearing translated, like others like "project initialized", "preparing", etc.

I think this is the last error I found.My last issue for now🙂

Strings untranslateds:
![Screenshot_20230811-164942](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/b7857383-177a-4026-b35a-23607cd09a54)

![Screenshot_20230811-165449](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/330fa02e-2e05-4339-91a9-9751509d4d89)

![Screenshot_20230811-164933](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/9abb0d0a-2a81-4714-97b5-11f6430a0562)

### What's the expected behavior?

Some translated texts

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
> Strings untranslateds: ![Screenshot_20230811-164942](https://user-images.githubusercontent.com/93414086/260139716-b7857383-177a-4026-b35a-23607cd09a54.jpg)
> 
> ![Screenshot_20230811-165449](https://user-images.githubusercontent.com/93414086/260139744-330fa02e-2e05-4339-91a9-9751509d4d89.jpg)
> 
> ![Screenshot_20230811-164933](https://user-images.githubusercontent.com/93414086/260139784-9abb0d0a-2a81-4714-97b5-11f6430a0562.jpg)

All these outputs are printed by Gradle. We have no control over it and hence we can't localise them.

**Comment by Rafael2616** [comment]
Yes, but since the app has variables that store if the build failed or was a success, I thought that since to use them to overwrite the original string when they appear for a localized one. But as I said this has a low priority, since it does not interfere with the use
