### ISSUE TITLE
[Bug]: Error putting the app in the background

### ISSUE THREAD

**Issue by esalessandrxx** [AndroidIDEOfficial/AndroidIDE#1208]
### What happened?

I just put the application in the background and when I returned to it it showed me the error

`v2.5.3-beta`

### What's the expected behavior?

it won't close the app

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-G781V
ABI: arm64-v8a
SDK version: 33
App version: v2.5.3-beta (253)

 Stacktrace: 
java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.itsaky.androidide.services.builder.GradleServiceBinder
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(Unknown Source:5)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2348)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2381)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Hey @esalessandrxx,

I tried to reproduce this issue, but failed. Can you provide instructions for the same?

But here is what I think about the issue :
You closed the IDE and reopened it again quickly. An application's process is not immediately terminated by the Android system and as  the `buildServiceConnection` in `ProjectHandlerActivity` is stored as a static variable, it might have been reused from the previous application process. I added a commit which might fix the issue.

**Comment by esalessandrxx** [comment]
> Hey @esalessandrxx,
> 
> I tried to reproduce this issue, but failed. Can you provide instructions for the same?
> 
> But here is what I think about the issue : You closed the IDE and reopened it again quickly. An application's process is not immediately terminated by the Android system and as the `buildServiceConnection` in `ProjectHandlerActivity` is stored as a static variable, it might have been reused from the previous application process. I added a commit which might fix the issue.

I've been using the commit for two days, during that time period it hasn't happened again.

but now I'm having problems with autocompletion. Example:

`before i start writing my code`
![example1](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/117092624/69209885-e654-4f8f-9240-67fe029f49ec)

`while i write my code`
![example2](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/117092624/55fe43a7-38cc-4dfa-881f-e4cdb979f232)

**Comment by itsaky** [comment]
> I've been using the commit for two days, during that time period it hasn't happened again.

Okay. Reopen this issue if you encounter it again.

> but now I'm having problems with autocompletion.

Create a new issue with a detailed explanation and steps to reproduce the issue.
