### ISSUE TITLE
[Bug]: IDE freezes while typing code

### ISSUE THREAD

**Issue by TheGrim404** [AndroidIDEOfficial/AndroidIDE#1209]
## Video | issue starts happening in `0:04` seconds in the video were the ide starts freezing 

https://github.com/AndroidIDEOfficial/AndroidIDE/assets/142217270/bb4a3cba-3e95-4ef5-8aa5-67fdb6bbccf8

![Picsart_23-08-14_12-52-02-956](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/142217270/3675be46-a454-43c4-8fcc-c4b2feb6ab28)

### What's the expected behavior?

It should be fixed long ago.
Using of: Android 10
Using of: Custom rom

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
I'm aware of this issue and already working on it. I'll try to fix it ASAP.

**Comment by Rafael2616** [comment]
@itsaky For context, I use app to program only in Kotlin and I haven't seen any of these types of problems here, and Ross the people I saw showing this error were using Java in the screenshots provided

**Comment by itsaky** [comment]
> @itsaky For context, I use app to program only in Kotlin and I haven't seen any of these types of problems here, and all the people I saw showing this error were using Java in the screenshots provided

Some bug reports were provided by @itsvks19 and the logs in those indicate the same thing. After looking at those logs, I think there might be an issue with the `android-tree-sitter` library or the tree sitter implementation in the editor itself. However, I can only **try** various things until I find a way to reproduce this issue myself.

**Comment by TheGrim404** [comment]
> I'm aware of this issue and already working on it. I'll try to fix it ASAP.

Take your time bro and thanks for this perfection project much love 3>.

**Comment by itsaky** [comment]
@TheGrim404 @Rafael2616

Try out the latest debug build to see if the issue still exists.

**Comment by itsaky** [comment]
Fixed in v2.6.0-beta.
