### ISSUE TITLE
[Feature]: using gradlew in terminal

### ISSUE THREAD

**Issue by mesflit** [AndroidIDEOfficial/AndroidIDE#1212]
### Feature description

I enter the project file. I'm typing ./gradlew. It does not work it says no required permissions but i gave the permissions with chmod

### What version of AndroidIDE you're using?

v2.5.2

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BanDroid** [comment]
use `sh` or `bash` to run it

```bash
bash ./gradlew
```
