### ISSUE TITLE
[Bug]: in layout editor layout attribute in include tag disappear when entering visual editor and return to code editor 

### ISSUE THREAD

**Issue by xobyx** [AndroidIDEOfficial/AndroidIDE#1214]
### What happened?

layout attribute disappear from include tags when entering visual editor and exit to text editor

### What's the expected behavior?

layout attribute remains 

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AButterLamp** [comment]
I am currently experiencing this issue aswell
