### ISSUE TITLE
[Feature]: Make long multi-page selection faster

### ISSUE THREAD

**Issue by gituser1000000** [AndroidIDEOfficial/AndroidIDE#1215]
### Feature description

To make a long selection that spans across several pages, we should able to do the following (instead of currently having to drag our finger down to the bottom of the page and wait for a long time for it to scroll):

-Tap on the starting position to move the cursor there.
-Fling pages down to where we see the ending position.
-Hold SHIFT on the on-screen keyboard and tap on the ending position to make the selection.
-Release SHIFT state to prevent further modification of the selection.

An extra button on the UI to mark the selection would give another alternative to perform this action even without the keyboard.

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
I think it would be better if you create a feature request in the [sora-editor](https://github.com/Rosemoe/sora-editor) repository itself. It'll be hard to implement it from our side and it may break things.

**Comment by itsaky** [comment]
This has been implemented in Rosemoe/sora-editor@90c7b8cf9fabcde771d3932ddcb7ffe09c3f9d87

**Comment by gituser1000000** [comment]
Now that we have a faster way of making selections, all we need now is for the copied text to get pasted correctly. Can't wait to use these new features on the next release.
