### ISSUE TITLE
[Feature]: add rust-lang

### ISSUE THREAD

**Issue by mesflit** [AndroidIDEOfficial/AndroidIDE#1218]
### Feature description

add rust-lang and cargo

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This won't be worked on.

**Comment by mesflit** [comment]
> This won't be worked on.

Why
