### ISSUE TITLE
[Bug]: Open last project in preferrence not working

### ISSUE THREAD

**Issue by arunbhattarai** [AndroidIDEOfficial/AndroidIDE#1225]
### What happened?

https://github.com/AndroidIDEOfficial/AndroidIDE/assets/102624903/b0d95955-1653-400e-8723-6b02724f7e73

will this get an fix ?

### What's the expected behavior?

Should open last sync project.

### What version of AndroidIDE you're using?

v2.5.3(debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arunbhattarai** [comment]
@itsaky is this a bug.if it is then why this issue been unattended?

**Comment by itsaky** [comment]
> @itsaky is this a bug.if it is then why this issue been unattended?

It is indeed a bug, but we have other issues with more priority right now. That's why this hasn't been resolved yet.

I'll try to fix this before the next release.

**Comment by arunbhattarai** [comment]
> > @itsaky is this a bug.if it is then why this issue been unattended?
> 
> It is indeed a bug, but we have other issues with more priority right now. That's why this hasn't been resolved yet.
> 
> I'll try to fix this before the next release.

Thank you for noticing.
