### ISSUE TITLE
[Feature]: UI shortcut to instantly remove all log sender clients

### ISSUE THREAD

**Issue by gituser1000000** [AndroidIDEOfficial/AndroidIDE#1226]
### Feature description

A UI shortcut to instantly remove all log sender clients would be useful in cases where a log sender client refuses to stop even after the debug-app has been swiped off the recent task list. This would be faster than the current way of having to close the project and restart.

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Sure, we can implement this.
