### ISSUE TITLE
[Bug]: faild idesetup -c

### ISSUE THREAD

**Issue by ask9027** [AndroidIDEOfficial/AndroidIDE#1244]
### What happened?

After first installation of ide , idesetup is not working,
curl: (56) OpenSSL SSL_read: OpenSSL/3.1.2: error:0A000119:SSL routines::decryption failed or bad record mac, errno 0

### What's the expected behavior?

initial setup should work

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
curl: (56) OpenSSL SSL_read: OpenSSL/3.1.2: error:0A000119:SSL routines::decryption failed or bad record mac, errno 0
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Might be an issue with your network connection. Check if you've configured proxy, VPN, etc.

Recently, other people encountered errors related to cURL as well. Running `pkg update && pkg upgrade` fix those errors. You could try doing the same.

**Comment by ask9027** [comment]
okay, thanks

**Comment by ask9027** [comment]
i found that ipv6 is causing problem . So i switch to ipv4 now it is working
