### ISSUE TITLE
[Feature]: Do not let go of the scroll handle until finger is up

### ISSUE THREAD

**Issue by gituser1000000** [AndroidIDEOfficial/AndroidIDE#1258]
### Feature description

When doing fast scrolling using the handle on the right edge of the page, it would be better if it didn't let go of the handle until the finger is up.

Currently, if our finger moves a little to the left, the handle slips off and the right panel starts sliding in. This whole act seems a bit unpolished because we always need to be careful and try not to stray too much to the left.

My suggestion is that once the handle has been grabbed, we should ignore (until done scrolling) any horizontal movement of the finger, and do not start the sliding in of the right file tree panel.

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
> When doing fast scrolling using the handle on the right edge of the page, it would be better if it didn't let go of the handle until the finger is up.

The file tree has been merged into the left drawer view in the `rework-tooling-api` branch (will be merged into `dev` soon) and  the right drawer has been removed.

If you still think that the fast scrolling could be improved, please open an issue in the editor's repository as all the touch events are handled by the editor.
