### ISSUE TITLE
[Bug] Files are not saved if I click the sync button

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1259]
### What happened?

By clicking the sync project button if I am in a Gradle file that I just changed for example, and click to sync the project the files are not saved, I know that I just click on save first, but a behavior similar to this occurs if I have a file being edited and click on build. It saves automatically.

### What's the expected behavior?

Save file by clicking sync project if there are unsaved files

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gituser1000000** [comment]
I usually do builds frequently to test out to see the results right away. Every time seeing the message "All files saved" I thought, "Oh boy, I'm going to make the device's flash memory die so soon." I hope only the changed files are saved and not all.

With all the thousands and thousands of cache files written for every project, it's already hard on the flash. If synching and building are done back to back, it causes unnecesary file writting.

So, maybe it could be a preference for users who wouldn't mind wearing out the device too quickly and would like to enable it anyway.

**Comment by itsaky** [comment]
> I usually do builds frequently to test out to see the results right away. Every time seeing the message "All files saved" I thought, "Oh boy, I'm going to make the device's flash memory die so soon." I hope only the changed files are saved and not all.
> 
> With all the thousands and thousands of cache files written for every project, it's already hard on the flash. If synching and building are done back to back, it causes unnecesary file writting.
> 
> So, maybe it could be a preference for users who wouldn't mind wearing out the device too quickly and would like to enable it anyway.
> 
> EDIT: Saving only the gradle file could be another solution.

Only the files that have been modified since the last save operation are saved.

**Comment by Rafael2616** [comment]
Thanks for fixing this inconvenience 👍🙂
