### ISSUE TITLE
[Bug]: app freezes on clicking Quick run

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1268]
### What happened?

This error started to appear in the branch rework tooling api, I didn't know if I could report it before. Sometimes between 1 in every ~20 builds when clicking on the quick run button the app crashes and only returns to normal when The build ends (success or failure)

It looks like the UI thread gets blocked

https://drive.google.com/file/d/1928yMSXWbQs3WVg854WLJa4AMrh19bLs/view?usp=drivesdk

### What's the expected behavior?

Not freeze

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
The issue should be resolved with the above commit. Can you recheck?

Let me know if it's fixed for you or not.

**Comment by Rafael2616** [comment]
Ok, I'll check, maybe it will take an hour or 2 because this error sometimes took a while to happen and sometimes it didn't

**Comment by Rafael2616** [comment]
Yes, it didn't happen anymore!
