### ISSUE TITLE
Xml preview bug

### ISSUE THREAD

**Issue by Mohammad-Azizi** [AndroidIDEOfficial/AndroidIDE#1271]
When I press the back button in the XML preview, it seems to automatically modify the XML layout, removing most of its contents. Subsequently, when I attempt to preview it again, an error message is displayed.

#bug

**Comment by itsaky** [comment]
Can you provide sample XML file contents in order to reproduce this issue?

**Comment by Mohammad-Azizi** [comment]
Before preview

![Screenshot_2023-09-08-21-25-49-38_9ad8e654efd333b66ab21513aa36e36c.jpg](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/131323246/288dc62b-35bd-499a-b274-e6b2f58556c5)


<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="@color/colorPrimaryDark"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <include layout="@layout/toolbar"/>

    <ScrollView
        android:scrollbars="none"
        android:clipToPadding="false"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <LinearLayout
            android:orientation="vertical"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <com.google.android.material.card.MaterialCardView
                android:id="@+id/cardViewApp"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_margin="10dp"
                app:cardCornerRadius="15dp"
                app:contentPadding="10dp"
                style="@style/Widget.Material3.CardView.Elevated">

                <androidx.constraintlayout.widget.ConstraintLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">

                    <LinearLayout
                        android:orientation="horizontal"
                        android:id="@+id/topButtonRow"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_centerHorizontal="true"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toBottomOf="@+id/txtDescription">

                        <com.google.android.material.button.MaterialButton
                            android:textColor="@color/colorAccent"
                            android:id="@+id/btnDonate"
                            android:layout_width="wrap_content"
                            android:layout_height="45dp"
                            android:layout_margin="5dp"
                            android:text="@string/remove_ads"
                            style="@style/Widget.Material3.Button.OutlinedButton"/>

                        <com.google.android.material.button.MaterialButton
                            android:textColor="@color/colorAccent"
                            android:id="@+id/btnTranslate"
                            android:layout_width="wrap_content"
                            android:layout_height="45dp"
                            android:layout_margin="5dp"
                            android:text="@string/translate"
                            style="@style/Widget.Material3.Button.OutlinedButton"/>

                    </LinearLayout>

                    <ImageView
                        android:id="@+id/imgIcon"
                        android:layout_width="60dp"
                        android:layout_height="60dp"
                        android:layout_marginTop="10dp"
                        android:contentDescription="@string/app_description"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent"
                        app:srcCompat="@mipmap/ic_launcher"/>

                    <TextView
                        android:textSize="14sp"
                        android:textStyle="bold"
                        android:id="@+id/txtVersion"
                        android:paddingLeft="20dp"
                        android:paddingRight="20dp"
                        android:layout_width="0dp"
                        android:layout_height="wrap_content"
                        android:textAlignment="center"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toBottomOf="@+id/txtAppNameAbout"/>

                    
                                          <TextView android:textSize="14sp" android:textStyle="bold" android:id="@+id/txtPackageName" android:paddingLeft="20dp" android:paddingRight="20dp" android:layout_width="0dp" android:layout_height="wrap_content" android:textAlignment="center" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/txtVersion"/>
                    <TextView android:textSize="12sp" android:id="@+id/txtDescription" android:layout_width="wrap_content" android:layout_height="match_parent" android:layout_marginTop="5dp" android:text="@string/app_description" android:textAllCaps="false" android:textAlignment="center" android:layout_marginStart="5dp" android:layout_marginEnd="5dp" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/txtPackageName"/>
                    <TextView android:textSize="22sp" android:textStyle="bold" android:id="@+id/txtAppNameAbout" android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginTop="10dp" android:text="@string/app_name" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/imgIcon"/>
                </androidx.constraintlayout.widget.ConstraintLayout>
            </com.google.android.material.card.MaterialCardView>
            <com.google.android.material.card.MaterialCardView android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginBottom="10dp" android:layout_marginStart="10dp" android:layout_marginEnd="10dp" app:cardCornerRadius="15dp" app:contentPadding="10dp" style="@style/Widget.Material3.CardView.Elevated">
                <androidx.constraintlayout.widget.ConstraintLayout android:layout_width="match_parent" android:layout_height="wrap_content">
                    <com.google.android.material.button.MaterialButton android:textColor="@color/colorAccent" android:id="@+id/btnEmail" android:layout_width="wrap_content" android:layout_height="45dp" android:layout_margin="5dp" android:text="@string/email" app:icon="@drawable/ic_email" app:iconTint="@color/colorAccent" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/txtTagline" style="@style/Widget.Material3.Button.OutlinedButton.Icon"/>
                    <ImageView android:id="@+id/circleImgDeveloper" android:layout_width="50dp" android:layout_height="50dp" android:contentDescription="@null" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toTopOf="parent" app:srcCompat="@drawable/developer"/>
                    <TextView android:textSize="12sp" android:id="@+id/txtTagline" android:paddingLeft="20dp" android:paddingRight="20dp" android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginTop="2dp" android:text="@string/developer_tagline" android:textAlignment="center" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/txtDeveloperName"/>
                    <TextView android:textSize="14sp" android:textStyle="bold" android:id="@+id/txtDeveloperName" android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="@string/developer" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/circleImgDeveloper"/>
                </androidx.constraintlayout.widget.ConstraintLayout>
            </com.google.android.material.card.MaterialCardView>
            <com.google.android.material.card.MaterialCardView android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginBottom="10dp" android:layout_marginStart="10dp" android:layout_marginEnd="10dp" app:cardCornerRadius="15dp" app:contentPadding="10dp" style="@style/Widget.Material3.CardView.Elevated">
                <androidx.constraintlayout.widget.ConstraintLayout android:layout_width="match_parent" android:layout_height="wrap_content">
                    <com.google.android.material.button.MaterialButton android:textColor="@color/colorAccent" android:id="@+id/btnTelegramJoin" android:layout_width="wrap_content" android:layout_height="45dp" android:layout_margin="5dp" android:text="@string/telegram" app:icon="@drawable/ic_telegram" app:iconTint="@color/colorAccent" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/txtTranlateDescription" style="@style/Widget.Material3.Button.OutlinedButton.Icon"/>
                    <TextView android:textSize="12sp" android:id="@+id/txtTranlateDescription" android:paddingLeft="10dp" android:paddingRight="10dp" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="2dp" android:text="@string/suggestions_description" android:textAlignment="center" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toBottomOf="@+id/txtTranslateName"/>
                    <TextView android:textSize="14sp" android:textStyle="bold" android:id="@+id/txtTranslateName" android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="@string/suggestions_title" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toTopOf="parent"/>
                </androidx.constraintlayout.widget.ConstraintLayout>
            </com.google.android.material.card.MaterialCardView>
        </LinearLayout>
    </ScrollView>
</androidx.coordinatorlayout.widget.CoordinatorLayout>







After preview 
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout
     xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:app="http://schemas.android.com/apk/res-auto"
     android:layout_height="match_parent"
     android:layout_width="match_parent"
     android:background="@color/colorPrimaryDark">

    <include
         android:layout_height="wrap_content"
         android:layout_width="wrap_content" />

    <ScrollView
         android:layout_height="match_parent"
         android:layout_width="match_parent"
         android:scrollbars="none"
         app:layout_behavior="@string/appbar_scrolling_view_behavior"
         android:clipToPadding="false">

        <LinearLayout
             android:layout_height="wrap_content"
             android:layout_width="match_parent"
             android:orientation="vertical">

            <com.google.android.material.card.MaterialCardView
                 android:layout_height="wrap_content"
                 android:layout_width="match_parent"
                 android:layout_margin="10dp"
                 style="@style/Widget.Material3.CardView.Elevated"
                 app:cardCornerRadius="15dp"
                 app:contentPadding="10dp"
                 android:id="@+id/cardViewApp">

                <androidx.constraintlayout.widget.ConstraintLayout
                     android:layout_height="wrap_content"
                     android:layout_width="match_parent">

                    <LinearLayout
                         android:layout_height="wrap_content"
                         android:layout_width="wrap_content"
                         android:orientation="horizontal"
                         app:layout_constraintStart_toStartOf="parent"
                         android:layout_centerHorizontal="true"
                         app:layout_constraintEnd_toEndOf="parent"
                         app:layout_constraintTop_toBottomOf="@+id/txtDescription"
                         android:id="@+id/topButtonRow">

                        <com.google.android.material.button.MaterialButton
                             android:layout_height="45dp"
                             android:layout_width="wrap_content"
                             android:layout_margin="5dp"
                             android:textColor="@color/colorAccent"
                             style="@style/Widget.Material3.Button.OutlinedButton"
                             android:id="@+id/btnDonate"
                             android:text="@string/remove_ads" />

                        <com.google.android.material.button.MaterialButton
                             android:layout_height="45dp"
                             android:layout_width="wrap_content"
                             android:layout_margin="5dp"
                             android:textColor="@color/colorAccent"
                             style="@style/Widget.Material3.Button.OutlinedButton"
                             android:id="@+id/btnTranslate"
                             android:text="@string/translate" />

                    </LinearLayout>

                    <ImageView
                         android:layout_height="60dp"
                         android:layout_width="60dp"
                         android:contentDescription="@string/app_description"
                         app:layout_constraintTop_toTopOf="parent"
                         app:layout_constraintStart_toStartOf="parent"
                         app:layout_constraintEnd_toEndOf="parent"
                         android:layout_marginTop="10dp"
                         app:srcCompat="@mipmap/ic_launcher"
                         android:id="@+id/imgIcon" />

                    <TextView
                         android:layout_height="wrap_content"
                         android:layout_width="0dp"
                         android:paddingRight="20dp"
                         android:textAlignment="center"
                         app:layout_constraintStart_toStartOf="parent"
                         android:textSize="14sp"
                         android:paddingLeft="20dp"
                         app:layout_constraintEnd_toEndOf="parent"
                         app:layout_constraintTop_toBottomOf="@+id/txtAppNameAbout"
                         android:textStyle="bold"
                         android:id="@+id/txtVersion" />

                    <TextView
                         android:layout_height="wrap_content"
                         android:layout_width="0dp"
                         android:paddingRight="20dp"
                         android:textAlignment="center"
                         app:layout_constraintStart_toStartOf="parent"
                         android:textSize="14sp"
                         android:paddingLeft="20dp"
                         app:layout_constraintEnd_toEndOf="parent"
                         app:layout_constraintTop_toBottomOf="@+id/txtVersion"
                         android:textStyle="bold"
                         android:id="@+id/txtPackageName" />

                    <TextView
                         android:layout_height="match_parent"
                         android:layout_width="wrap_content"
                         android:layout_marginEnd="5dp"
                         android:textSize="12sp"
                         android:layout_marginTop="5dp"
                         android:layout_marginStart="5dp"
                         app:layout_constraintTop_toBottomOf="@+id/txtPackageName"
                         android:textAlignment="center"
                         app:layout_constraintStart_toStartOf="parent"
                         android:textAllCaps="false"
                         app:layout_constraintEnd_toEndOf="parent"
                         android:id="@+id/txtDescription"
                         android:text="@string/app_description" />

                    <TextView
                         android:layout_height="wrap_content"
                         android:layout_width="wrap_content"
                         app:layout_constraintStart_toStartOf="parent"
                         android:textSize="22sp"
                         app:layout_constraintEnd_toEndOf="parent"
                         android:layout_marginTop="10dp"
                         app:layout_constraintTop_toBottomOf="@+id/imgIcon"
                         android:textStyle="bold"
                         android:id="@+id/txtAppNameAbout"
                         android:text="@string/app_name" />

                </androidx.constraintlayout.widget.ConstraintLayout>

            </com.google.android.material.card.MaterialCardView>

            <com.google.android.material.card.MaterialCardView
                 android:layout_height="wrap_content"
                 android:layout_width="match_parent"
                 android:layout_marginBottom="10dp"
                 android:layout_marginEnd="10dp"
                 style="@style/Widget.Material3.CardView.Elevated"
                 android:layout_marginStart="10dp"
                 app:cardCornerRadius="15dp"
                 app:contentPadding="10dp">

                <androidx.constraintlayout.widget.ConstraintLayout
                     android:layout_height="wrap_content"
                     android:layout_width="match_parent">

                    <com.google.android.material.button.MaterialButton
                         android:layout_height="45dp"
                         android:layout_width="wrap_content"
                         app:icon="@drawable/ic_email"
                         android:layout_margin="5dp"
                         app:layout_constraintStart_toStartOf="parent"
                         app:iconTint="@color/colorAccent"
                         android:textColor="@color/colorAccent"
                         app:layout_constraintEnd_toEndOf="parent"
                         style="@style/Widget.Material3.Button.OutlinedButton.Icon"
                         app:layout_constraintTop_toBottomOf="@+id/txtTagline"
                         android:id="@+id/btnEmail"
                         android:text="@string/email" />

                    <ImageView
                         android:layout_height="50dp"
                         android:layout_width="50dp"
                         android:contentDescription="@null"
                         app:layout_constraintTop_toTopOf="parent"
                         app:layout_constraintStart_toStartOf="parent"
                         app:layout_constraintEnd_toEndOf="parent"
                         app:srcCompat="@drawable/developer"
                         android:id="@+id/circleImgDeveloper" />

                    <TextView
                         android:layout_height="wrap_content"
                         android:layout_width="wrap_content"
                         android:paddingRight="20dp"
                         android:textAlignment="center"
                         app:layout_constraintStart_toStartOf="parent"
                         android:textSize="12sp"
                         android:paddingLeft="20dp"
                         app:layout_constraintEnd_toEndOf="parent"
                         android:layout_marginTop="2dp"
                         app:layout_constraintTop_toBottomOf="@+id/txtDeveloperName"
                         android:id="@+id/txtTagline"
                         android:text="@string/developer_tagline" />

                    <TextView
                         android:layout_height="wrap_content"
                         android:layout_width="wrap_content"
                         app:layout_constraintStart_toStartOf="parent"
                         android:textSize="14sp"
                         app:layout_constraintEnd_toEndOf="parent"
                         app:layout_constraintTop_toBottomOf="@+id/circleImgDeveloper"
                         android:textStyle="bold"
                         android:id="@+id/txtDeveloperName"
                         android:text="@string/developer" />

                </androidx.constraintlayout.widget.ConstraintLayout>

            </com.google.android.material.card.MaterialCardView>

            <com.google.android.material.card.MaterialCardView
                 android:layout_height="wrap_content"
                 android:layout_width="match_parent"
                 android:layout_marginBottom="10dp"
                 android:layout_marginEnd="10dp"
                 style="@style/Widget.Material3.CardView.Elevated"
                 android:layout_marginStart="10dp"
                 app:cardCornerRadius="15dp"
                 app:contentPadding="10dp">

                <androidx.constraintlayout.widget.ConstraintLayout
                     android:layout_height="wrap_content"
                     android:layout_width="match_parent">

                    <com.google.android.material.button.MaterialButton
                         android:layout_height="45dp"
                         android:layout_width="wrap_content"
                         app:icon="@drawable/ic_telegram"
                         android:layout_margin="5dp"
                         app:layout_constraintStart_toStartOf="parent"
                         app:iconTint="@color/colorAccent"
                         android:textColor="@color/colorAccent"
                         app:layout_constraintEnd_toEndOf="parent"
                         style="@style/Widget.Material3.Button.OutlinedButton.Icon"
                         app:layout_constraintTop_toBottomOf="@+id/txtTranlateDescription"
                         android:id="@+id/btnTelegramJoin"
                         android:text="@string/telegram" />

                    <TextView
                         android:layout_height="wrap_content"
                         android:layout_width="match_parent"
                         android:paddingRight="10dp"
                         android:textAlignment="center"
                         app:layout_constraintStart_toStartOf="parent"
                         android:textSize="12sp"
                         android:paddingLeft="10dp"
                         app:layout_constraintEnd_toEndOf="parent"
                         android:layout_marginTop="2dp"
                         app:layout_constraintTop_toBottomOf="@+id/txtTranslateName"
                         android:id="@+id/txtTranlateDescription"
                         android:text="@string/suggestions_description" />

                    <TextView
                         android:layout_height="wrap_content"
                         android:layout_width="wrap_content"
                         app:layout_constraintTop_toTopOf="parent"
                         app:layout_constraintStart_toStartOf="parent"
                         android:textSize="14sp"
                         app:layout_constraintEnd_toEndOf="parent"
                         android:textStyle="bold"
                         android:id="@+id/txtTranslateName"
                         android:text="@string/suggestions_title" />

                </androidx.constraintlayout.widget.ConstraintLayout>

            </com.google.android.material.card.MaterialCardView>

        </LinearLayout>

    </ScrollView>

</androidx.coordinatorlayout.widget.CoordinatorLayout>


![Screenshot_2023-09-08-21-24-09-11_9ad8e654efd333b66ab21513aa36e36c.jpg](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/131323246/8a70d33f-c9fc-42ef-a31e-6e679d3b5016)

**Comment by itsaky** [comment]
@Mohammad-Azizi

Sorry for the delayed response. Upon inspecting the layout you provided, the two XML layouts seem to be similar and the issue about the `<include>` tags was fixed recently (#1060).

**Comment by Mohammad-Azizi** [comment]
Ok thanks
