### ISSUE TITLE
[Bug]: UI buttons after 'rework-tooling-api' are missorted

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1272]
### What happened?

Several buttons on the interface are in not very nice positions and that made me confused in the first days until today after rework tooling api 

### What's the expected behavior?

1 - Close file buttons

Before: 
- close it
- close others
- close all

After:
- close others
- close it
- close all

2- Quick Actions:
Before:
![Screenshot_20230908-112320](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/83438154-81bd-4dfa-b5bc-f60b2774a9cb)

After:
![Screenshot_20230908-111615~2](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/7c5f12aa-2ed5-4750-b502-9f4aa709e6eb)

3- Top app buttons:
Before:
![Screenshot_20230908-112755](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/8696d2e3-e4d9-40ba-8f6a-6a558642d917)

After:
![Screenshot_20230908-112002~2](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/501ac2fa-3428-43ff-93da-9dc78cc31cc5)

To compile the app now I need to go to the 3 dots

As you can see the old model was more intuitive and accurate

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
There were some changes regarding the order of the menu items in the Actions API. I forgot to update existing actions accordingly. Will fix this soon.
