### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE "curl"

### ISSUE THREAD

**Issue by MirageMind** [AndroidIDEOfficial/AndroidIDE#1275]
### What happened?

When I run "idesetup -c" I get the following error:

![IMG_20230910_002014](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/144500846/0f7521ed-33bc-4578-b4d1-ce5ec29b2d53)

CANNOT LINK EXECUTABLE "curl": cannot locate symbol "libssh2_session_set_read_timeout" referenced by "/data/data/com.itsaky.androidide/files/usr/lib/libcurl.so"...

### What's the expected behavior?

solve it

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JUDE122-MAX** [comment]
To fix it do run this command in the terminal

`pkg install libssh2`

Then try again. Worked for me

**Comment by MirageMind** [comment]
thanks, problem solved.

**Comment by MirageMind** [comment]
I think there is another problem... Since I can't access raw.githubusercontent.com directly, I need to use a VPN, but when I open the VPN, neither apt nor curl can get anything.
