### ISSUE TITLE
[Bug]: curl error

### ISSUE THREAD

**Issue by Kofe97** [AndroidIDEOfficial/AndroidIDE#1277]
### What happened?

![Screenshot_2023-09-10-10-13-39-642_com itsaky androidide](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/62602114/79bf61bc-83ac-4e9b-a617-1b7227786f42)
![Screenshot_2023-09-10-10-14-55-451_com itsaky androidide](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/62602114/5687f2c5-0413-41b8-947c-f18e12e03b27)

### What's the expected behavior?

curl should work

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimplyVoid** [comment]
do `pkg update && pkg upgrade` then run idesetup

**Comment by itsaky** [comment]
Use the solution provided by @SimplyVoid.

**Comment by Kofe97** [comment]
Fix
