### ISSUE TITLE
App crush

### ISSUE THREAD

**Issue by garawaa** [AndroidIDEOfficial/AndroidIDE#1278]
### What happened?

When I try drag a widget to layout in layout view it just crushes.

### What's the expected behavior?

When I try drag a widget to layout in layout view it just crushes.

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Provide the crash logs (stacktrace).
