### ISSUE TITLE
[功能]: 添加apk签名的支持

### ISSUE THREAD

**Issue by sianqin** [AndroidIDEOfficial/AndroidIDE#1282]
### Feature description

希望能在AndroidIDE中支持Android studio的apk自定义签名密钥的功能

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhosni** [comment]
It's already supported thanks to Gradle. [Here's the official documentation for that ](https://androidide.com/blogs/apk-signing/2023/03/23/create-a-signed-release-apk-of-your-project-with-androidide/)

**Comment by sianqin** [comment]
按照官方文档的操作，在进行keytool -genkey -v -keystore signing-key.jks -keyalg RSA -keysize 2048 -validity 9125 -alias myAlias命令操作后，提示Enter keystore password:命令后就无法进行任何操作

**Comment by sianqin** [comment]
> 它已经得到了Gradle的支持。[这是官方文件](https://androidide.com/blogs/apk-signing/2023/03/23/create-a-signed-release-apk-of-your-project-with-androidide/)按照官方文档的操作，在进行keytool -genkey -v -keystore signing-key.jks -keyalg RSA -keysize 2048 -validity 9125 -alias myAlias命令操作后，提示Enter keystore password:命令后就无法进行任何操作

**Comment by itsaky** [comment]
Follow this guide to setup APK signing in AndroidIDE:

https://androidide.com/blogs/apk-signing/2023/03/23/create-a-signed-release-apk-of-your-project-with-androidide/
