### ISSUE TITLE
you must call start parse(androidModule) first

### ISSUE THREAD

**Issue by Majestychen** [AndroidIDEOfficial/AndroidIDE#1283]
My cloned “https://github.com/13767004362/Camera2App.git”  project prompts "you must call start parse (androidModule) first" when using the preview layout. My mobile phone system is HarmonyOS3.0. How can I solve this problem? 
Thank you!

**Comment by Majestychen** [comment]
LogReceiverImpl           I   Starting log sender handler.. 
MultiLogSenderHandler     I   Starting log receiver server socket at port 39283 
GradleBuildService        I   Showing notification to user... 
EditorActivity            I   Connected to Gradle build service 
ToolingServerRunner       I   Starting tooling API server... 
ToolingServerRunner       E   Unable to start tooling API server 
ToolingServerRunner       E  java.io.IOException: error=2, No such file or directory
ToolingServerRunner       E  	at java.lang.UNIXProcess.forkAndExec(Native Method)
ToolingServerRunner       E  	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
ToolingServerRunner       E  	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
ToolingServerRunner       E  	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
ToolingServerRunner       E   Caused by: java.io.IOException: Cannot run program "/data/data/com.itsaky.androidide/files/usr/opt/openjdk/bin/java" (in directory "/data/data/com.itsaky.androidide/files/home"): error=2, No such file or directory
ToolingServerRunner       E  	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
ToolingServerRunner       E  	at com.sun.jna.FromNativeContext.execAsync(Unknown Source:36)
ToolingServerRunner       E  	at com.itsaky.androidide.services.builder.ToolingServerRunner.run(Unknown Source:84)
ToolingServerRunner       E  
ToolingServerRunner       E  
EditorActivity            I   Opening file at index:  0  file:   /storage/emulated/0/AppProjects/MyVideosRecApp/app/src/main/res/layout/main.xml 
LanguageSpecProvider      W   Scheme file 'locals' for type 'xml' not found 
CodeEditorView            I   main.xml 
CodeEditorView            I   File was not modified. Skipping save operation. 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AppProjects/MyVideosRecApp/app/src/main/res/layout/main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AppProjects/MyVideosRecApp/app/src/main/res/layout/main.xml, selection=Range(start=Position(line=0, column=0, index=-1), end=Position(line=0, column=0, index=-1)))]) 
ProjectManager            W   Project is not initialized yet! 
ProjectManager            W   Project is not initialized yet! 
DesignerWorkspaceFragment E  
DesignerWorkspaceFragment E  java.lang.IllegalStateException: You must call startParse(AndroidModule) first
DesignerWorkspaceFragment E  	at com.google.common.base.Strings.getModule(Unknown Source:9)
DesignerWorkspaceFragment E  	at com.itsaky.androidide.inflater.internal.LayoutInflaterImpl.inflate(Unknown Source:24)
DesignerWorkspaceFragment E  	at com.itsaky.androidide.uidesigner.fragments.DesignerWorkspaceFragment.onViewCreated(Unknown Source:116)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentStateManager.createView(Unknown Source:253)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(Unknown Source:145)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentManagerImpl.moveToState(Unknown Source:62)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(Unknown Source:35)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentActivity.onStart(Unknown Source:34)
DesignerWorkspaceFragment E  	at androidx.appcompat.app.AppCompatActivity.onStart(Unknown Source:0)
DesignerWorkspaceFragment E  	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1447)
DesignerWorkspaceFragment E  	at android.app.Activity.performStart(Activity.java:8237)
DesignerWorkspaceFragment E  	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4089)
DesignerWorkspaceFragment E  	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
DesignerWorkspaceFragment E  	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
DesignerWorkspaceFragment E  	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
DesignerWorkspaceFragment E  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
DesignerWorkspaceFragment E  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2618)
DesignerWorkspaceFragment E  	at android.os.Handler.dispatchMessage(Handler.java:110)
DesignerWorkspaceFragment E  	at android.os.Looper.loop(Looper.java:219)
DesignerWorkspaceFragment E  	at android.app.ActivityThread.main(ActivityThread.java:8673)
DesignerWorkspaceFragment E  	at java.lang.reflect.Method.invoke(Native Method)
DesignerWorkspaceFragment E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
DesignerWorkspaceFragment E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
DesignerWorkspaceFragment E  
DesignerWorkspaceFragment E  
UIDesignerActivity        E   Failed to generate XML code because 'Inflation failed, layout has errors.' 
EditorActivity            W   UI Designer returned invalid result  0  null 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AppProjects/MyVideosRecApp/app/src/main/res/layout/main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AppProjects/MyVideosRecApp/app/src/main/res/layout/main.xml, selection=Range(start=Position(line=0, column=0, index=-1), end=Position(line=0, column=0, index=-1)))]) 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AppProjects/MyVideosRecApp/app/src/main/res/layout/main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AppProjects/MyVideosRecApp/app/src/main/res/layout/main.xml, selection=Range(start=Position(line=0, column=0, index=-1), end=Position(line=0, column=0, index=-1)))]) 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AppProjects/MyVideosRecApp/app/src/main/res/layout/main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AppProjects/MyVideosRecApp/app/src/main/res/layout/main.xml, selection=Range(start=Position(line=0, column=0, index=-1), end=Position(line=0, column=0, index=-1)))])

**Comment by itsaky** [comment]
> Caused by: java.io.IOException: Cannot run program "/data/data/com.itsaky.androidide/files/usr/opt/openjdk/bin/java"

You have not installed JDK 17. Please follow [this guide](https://androidide.com/blogs/getting-started/2023/03/15/getting-started-with-androidide/) to install and setup AndroidIDE.

When you open a project, wait for the initialization to finish preview opening the UI designer.

**Comment by Majestychen** [comment]
LogReceiverImpl           I   Starting log sender handler.. 
GradleBuildService        I   Showing notification to user... 
MultiLogSenderHandler     I   Starting log receiver server socket at port 44745 
EditorActivity            I   Connected to Gradle build service 
ToolingServerRunner       I   Starting tooling API server... 
ToolingApiServer          D   ToolingApiMain             Server started. Will run until shutdown message is received...  
CachingProject            W   No tasks found in project '' 
CachingProject            D   Empty module data returned by tooling server. Ignoring... 
EditorActivity            D   Is project initialized: false 
EditorActivity            D   Sending init request to tooling server.. 
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiServer          D   ToolingApiServerImpl       Got initialize request  InitializeProjectMessage(directory=/storage/emulated/0/AndroidIDEProjects/Camera2App, gradleInstallation=)  
ToolingApiErrorStream     E   SLF4J: No SLF4J providers were found. 
ToolingApiErrorStream     E   SLF4J: Defaulting to no-operation (NOP) logger implementation 
ToolingApiErrorStream     E   SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details. 
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle wrapper for build...  
ToolingApiServer          D   StopWatch                  Connector created in 140ms  
ToolingApiServer          D   StopWatch                  Project connection established in 107ms  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2]  
ToolingApiServer          W   ProjectReader              Starting build. See build output for more details...  
ToolingApiServer          E   ToolingApiServerImpl      
ToolingApiServer          E  java.lang.IllegalArgumentException
ToolingApiServer          E  	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:169)
ToolingApiServer          E  	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.serialization.ClasspathInferer.find(ClasspathInferer.java:105)
ToolingApiServer          E   Caused by: org.gradle.api.GradleException: Could not determine the class-path for class com.itsaky.androidide.tooling.impl.util.ProjectReader.
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.serialization.ClasspathInferer.find(ClasspathInferer.java:142)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.serialization.ClasspathInferer.getClassPathFor(ClasspathInferer.java:60)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.serialization.ClientSidePayloadClassLoaderRegistry$1.visitClass(ClientSidePayloadClassLoaderRegistry.java:78)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.serialization.WellKnownClassLoaderRegistry$1.visitClass(WellKnownClassLoaderRegistry.java:65)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.serialization.PayloadSerializerObjectOutputStream.writeClassLoader(PayloadSerializerObjectOutputStream.java:63)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.serialization.PayloadSerializerObjectOutputStream.writeClass(PayloadSerializerObjectOutputStream.java:55)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.serialization.PayloadSerializerObjectOutputStream.writeClassDescriptor(PayloadSerializerObjectOutputStream.java:43)
ToolingApiServer          E  	at java.base/java.io.ObjectOutputStream.writeNonProxyDesc(ObjectOutputStream.java:1295)
ToolingApiServer          E  	at java.base/java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:1244)
ToolingApiServer          E  	at java.base/java.io.ObjectOutputStream.writeClass(ObjectOutputStream.java:1226)
ToolingApiServer          E  	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1133)
ToolingApiServer          E  	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1582)
ToolingApiServer          E  	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1539)
ToolingApiServer          E  	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448)
ToolingApiServer          E  	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191)
ToolingApiServer          E  	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1582)
ToolingApiServer          E  	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1539)
ToolingApiServer          E  	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1448)
ToolingApiServer          E  	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1191)
ToolingApiServer          E  	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.serialization.PayloadSerializer.serialize(PayloadSerializer.java:45)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:123)
ToolingApiServer          E  	at org.gradle.tooling.internal.provider.DefaultConnection.run(DefaultConnection.java:208)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.CancellableActionRunner.execute(CancellableActionRunner.java:64)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.CancellableActionRunner.run(CancellableActionRunner.java:52)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:69)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:56)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter$1.run(DefaultBuildActionExecuter.java:81)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:143)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:61)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:67)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
ToolingApiServer          E  	at java.base/java.lang.Thread.run(Thread.java:833)
ToolingApiServer          E   Caused by: org.gradle.tooling.GradleConnectionException: Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-4.1-all.zip'.
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:43)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:69)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
ToolingApiServer          E  	at java.base/java.lang.Thread.run(Thread.java:833)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(DefaultBuildActionExecuter.java:67)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.util.ProjectReader.read(ProjectReader.java:107)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.ToolingApiServerImpl.initialize$lambda$0(ToolingApiServerImpl.kt:109)
ToolingApiServer          E  	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
ToolingApiServer          E  	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
ToolingApiServer          E  
ToolingApiServer          E   
CachingProject            W   No tasks found in project '' 
CachingProject            D   Empty module data returned by tooling server. Ignoring... 
ILanguageServerRegistry   D   Dispatching ProjectInitializedEvent to language servers... 
EditorActivity            D   [onPause]  No opened files.  Opened files cache reset to null. 
EditorActivity            D   [onPause]  No opened files.  Opened files cache reset to null. 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
EditorActivity            I   Opening file at index:  0  file:   /storage/emulated/0/AndroidIDEProjects/Camera2App/app/src/main/res/layout/activity_main.xml 
LanguageSpecProvider      W   Scheme file 'locals' for type 'xml' not found 
CodeEditorView            I   activity_main.xml 
CodeEditorView            I   File was not modified. Skipping save operation. 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AndroidIDEProjects/Camera2App/app/src/main/res/layout/activity_main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Camera2App/app/src/main/res/layout/activity_main.xml, selection=Range(start=Position(line=0, column=0, index=-1), end=Position(line=0, column=0, index=-1)))]) 
DesignerWorkspaceFragment E  
DesignerWorkspaceFragment E  java.lang.IllegalStateException: You must call startParse(AndroidModule) first
DesignerWorkspaceFragment E  	at com.google.common.base.Strings.getModule(Unknown Source:9)
DesignerWorkspaceFragment E  	at com.itsaky.androidide.inflater.internal.LayoutInflaterImpl.inflate(Unknown Source:24)
DesignerWorkspaceFragment E  	at com.itsaky.androidide.uidesigner.fragments.DesignerWorkspaceFragment.onViewCreated(Unknown Source:116)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentStateManager.createView(Unknown Source:253)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(Unknown Source:145)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentManagerImpl.moveToState(Unknown Source:62)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(Unknown Source:35)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentActivity.onStart(Unknown Source:34)
DesignerWorkspaceFragment E  	at androidx.appcompat.app.AppCompatActivity.onStart(Unknown Source:0)
DesignerWorkspaceFragment E  	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1447)
DesignerWorkspaceFragment E  	at android.app.Activity.performStart(Activity.java:8237)
DesignerWorkspaceFragment E  	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4089)
DesignerWorkspaceFragment E  	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
DesignerWorkspaceFragment E  	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
DesignerWorkspaceFragment E  	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
DesignerWorkspaceFragment E  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
DesignerWorkspaceFragment E  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2618)
DesignerWorkspaceFragment E  	at android.os.Handler.dispatchMessage(Handler.java:110)
DesignerWorkspaceFragment E  	at android.os.Looper.loop(Looper.java:219)
DesignerWorkspaceFragment E  	at android.app.ActivityThread.main(ActivityThread.java:8673)
DesignerWorkspaceFragment E  	at java.lang.reflect.Method.invoke(Native Method)
DesignerWorkspaceFragment E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
DesignerWorkspaceFragment E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
DesignerWorkspaceFragment E  
DesignerWorkspaceFragment E  
UIDesignerActivity        E   Failed to generate XML code because 'Inflation failed, layout has errors.' 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
EditorActivity            W   UI Designer returned invalid result  0  null 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AndroidIDEProjects/Camera2App/app/src/main/res/layout/activity_main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Camera2App/app/src/main/res/layout/activity_main.xml, selection=Range(start=Position(line=0, column=0, index=-1), end=Position(line=0, column=0, index=-1)))]) 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
DefaultActionsRegistry    I   Action 'editor_fileTree' completed in 4ms 
EditorActivity            I   Opening file at index:  1  file:   /storage/emulated/0/AndroidIDEProjects/Camera2App/app/src/main/res/layout-land/activity_picture.xml 
LanguageSpecProvider      W   Scheme file 'locals' for type 'xml' not found 
DefaultActionsRegistry    I   Action 'editor_fileTree' completed in 0ms 
EditorActivity            I   Opening file at index:  2  file:   /storage/emulated/0/AndroidIDEProjects/Camera2App/app/src/main/res/layout-land/fragment_camera.xml 
LanguageSpecProvider      W   Scheme file 'locals' for type 'xml' not found 
CodeEditorView            I   activity_main.xml 
CodeEditorView            I   File was not modified. Skipping save operation. 
CodeEditorView            I   activity_picture.xml 
CodeEditorView            I   File was not modified. Skipping save operation. 
CodeEditorView            I   fragment_camera.xml 
CodeEditorView            I   File was not modified. Skipping save operation. 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AndroidIDEProjects/Camera2App/app/src/main/res/layout-land/fragment_camera.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Camera2App/app/src/main/res/layout/activity_main.xml, selection=Range(start=Position(line=0, column=0, index=-1), end=Position(line=0, column=0, index=-1))), OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Camera2App/app/src/main/res/layout-land/activity_picture.xml, selection=Range(start=Position(line=0, column=0, index=-1), end=Position(line=0, column=0, index=-1))), OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Camera2App/app/src/main/res/layout-land/fragment_camera.xml, selection=Range(start=Position(line=0, column=0, index=-1), end=Position(line=0, column=0, index=-1)))]) 
DesignerWorkspaceFragment E  
DesignerWorkspaceFragment E  java.lang.IllegalStateException: You must call startParse(AndroidModule) first
DesignerWorkspaceFragment E  	at com.google.common.base.Strings.getModule(Unknown Source:9)
DesignerWorkspaceFragment E  	at com.itsaky.androidide.inflater.internal.LayoutInflaterImpl.inflate(Unknown Source:24)
DesignerWorkspaceFragment E  	at com.itsaky.androidide.uidesigner.fragments.DesignerWorkspaceFragment.onViewCreated(Unknown Source:116)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentStateManager.createView(Unknown Source:253)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(Unknown Source:145)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentManagerImpl.moveToState(Unknown Source:62)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(Unknown Source:35)
DesignerWorkspaceFragment E  	at androidx.fragment.app.FragmentActivity.onStart(Unknown Source:34)
DesignerWorkspaceFragment E  	at androidx.appcompat.app.AppCompatActivity.onStart(Unknown Source:0)
DesignerWorkspaceFragment E  	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1447)
DesignerWorkspaceFragment E  	at android.app.Activity.performStart(Activity.java:8237)
DesignerWorkspaceFragment E  	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4089)
DesignerWorkspaceFragment E  	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
DesignerWorkspaceFragment E  	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
DesignerWorkspaceFragment E  	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
DesignerWorkspaceFragment E  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
DesignerWorkspaceFragment E  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2618)
DesignerWorkspaceFragment E  	at android.os.Handler.dispatchMessage(Handler.java:110)
DesignerWorkspaceFragment E  	at android.os.Looper.loop(Looper.java:219)
DesignerWorkspaceFragment E  	at android.app.ActivityThread.main(ActivityThread.java:8673)
DesignerWorkspaceFragment E  	at java.lang.reflect.Method.invoke(Native Method)
DesignerWorkspaceFragment E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
DesignerWorkspaceFragment E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
DesignerWorkspaceFragment E  
DesignerWorkspaceFragment E  
UIDesignerActivity        E   Failed to generate XML code because 'Inflation failed, layout has errors.' 
EditorActivity            W   UI Designer returned invalid result  0  null 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar
