### ISSUE TITLE
UI design[Feature]: 

### ISSUE THREAD

**Issue by Majestychen** [AndroidIDEOfficial/AndroidIDE#1286]
### Feature description

Can XML preview refer to sketchware? Using the UI design of sketchware and the code editing function of AndroidIDE is perfect!

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This doesn't make any sense.

Also, we already have our own UI designer.
