### ISSUE TITLE
[Upgrade]: Update Gradle to 8.1.1 and SDK to 34

### ISSUE THREAD

**Issue by Ruan625Br** [AndroidIDEOfficial/AndroidIDE#1287]
### Feature description

Please update AGP to version 8.1.1 and the SDKto API level 34. I was in the process of implementing Room Database with version "2.6.0-beta01." However, the dependency "'androidx.sqlite:sqlite-framework:2.4.0-beta01'" (which is included in Room Database) requires that libraries and applications depending on it compile with Android APIs version 34 or later.

I plan to explore the possibility of temporarily using an older version of Room Database to work around this issue.

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
I looked into the [build failure for the AGP v8.1.1](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/6161124785/job/16719635260#step:6:2549) update and I remembered that I previously upgraded AGP to v8.1.1 but had to downgrade to v8.0.2 due to [this issue](https://issuetracker.google.com/issues/293547829).

So for now, we won't be able to upgrade to Android Gradle Plugin v8.1.1.

**Comment by Ruan625Br** [comment]
Thank you very much for the update. Regarding the Room Database, I initially implemented it using an older version (2.5.2) that supports SDK 33. I will soon provide more comprehensive information on how the Room Database implementation went. I prefer that you create a new Room Database implementation for this project.

I would like to inform you that I have already implemented the [list of recently opened projects](https://github.com/AndroidIDEOfficial/AndroidIDE/issues/1284) using Room Database and now I am in the final phase of some refinements. I will soon upload videos showing the list of works along with additional information extracted.

**Comment by Rafael2616** [comment]
This issue can now be closed  @itsaky by https://github.com/AndroidIDEOfficial/AndroidIDE/commit/81c9a5b0a5f04b711ee70317a1a52408d6dff36b
