### ISSUE TITLE
[Migrate]: Migrate from kapt to KSP

### ISSUE THREAD

**Issue by Ruan625Br** [AndroidIDEOfficial/AndroidIDE#1331]
### Feature description

**Background:**
Currently, AndroidIDE relies on KAPT (Kotlin Annotation Processing Tool) for annotation processing tasks. However, Kotlin Symbol Processing (KSP) has gained significant traction and offers several advantages over KAPT, such as better performance and better integration with the Kotlin compiler.

**Proposal:**

I propose that we migrate our project from KAPT to KSP to take advantage of the benefits it offers. KSP is actively developed and supported by JetBrains, the company behind Kotlin, and is becoming the preferred choice for annotation processing in Kotlin projects.

**Benefits of migrating to KSP:**
1. **Performance:** KSP is known for its improved performance compared to KAPT. It can significantly reduce build time, especially in projects with complex annotation processing requirements.

2. **Kotlin Compiler Integration:** KSP is fully integrated with the Kotlin compiler, making it a perfect choice for Kotlin projects. It provides better support for specific Kotlin features and languages.

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
> Currently, AndroidIDE relies on KAPT (Kotlin Annotation Processing Tool) for annotation processing tasks.

This is not entirely true. `kapt` is used only for EventBus and Google's AutoService annotations. I haven't really checked, but I don't think Google's AutoService supports KSP. EventBus uses Java's `AnnotationProcessor` API which I don't think is compatible with KSP.

Our own annotation processors (for `xml-inflater` module) do support KSP.
