### ISSUE TITLE
last opened files

### ISSUE THREAD

**Issue by yzjdev** [AndroidIDEOfficial/AndroidIDE#1334]
remember last opened files this is necessary

**Comment by itsaky** [comment]
This feature is already available. If you're facing issues with the current implementation, please reopen this issue and explain the problem.

**Comment by yzjdev** [comment]
> This feature is already available. If you're facing issues with the current implementation, please reopen this issue and explain the problem.![Screenshot_2023-09-25-09-37-19-558_com.itsaky.androidide.jpg](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/121114254/25214638-6275-43c7-9276-516b13468cdf)

每次编译都会关闭 哪里来的已实现？2.5.3-beta版本

**Comment by yzjdev** [comment]
i don't know whether you use it. Project always get stuck and cannot be edit in first open ide.  Even if close the ide. it still happen when open it again. my device is android14 miui14
