### ISSUE TITLE
[Feature]: Enhance APK Install/Run

### ISSUE THREAD

**Issue by CyberXCoder-6649** [AndroidIDEOfficial/AndroidIDE#1336]
### Feature description

Whenever Building apk sometime APK installation gets canceled and we need to manually open from File Tree so add "Install APK" option in Options Menu to Install APK

Like this:
![Screenshot_20230925-150426_AndroidIDE](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/86068846/ad778ad1-fb6f-45e1-86d7-39a3256b1427)

Additionally we can also add:
1. When Clicked on "Install APK" show list of multiple apps (variants) if available in build directory Like for example AndroidIDE has 2 variant it will ask which app to install. Maybe by searching ".apk" file in build directory or any other way
2. Launch Installed APP ("Launch APP") Option in Options Menu

3. If user want apk to automatically launch apk after installation, can configure in Settings  "Run APK after installation" or instead of Settings option can be shown in Options Menu or Drawer to whether Run apk or not
### What version of AndroidIDE you're using?
v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
I have added a preference to allow the user to choose whether the application must be launched automatically post-installation (after quick run).

However, I'm not sure about these two features :
> When Clicked on "Install APK" show list of multiple apps (variants) if available in build directory Like for example AndroidIDE has 2 variant it will ask which app to install.

> Launch Installed APP ("Launch APP") Option in Options Menu

Users might get confused about the "build", "install" and "launch" actions. They seem similar.

**Comment by CyberXCoder-6649** [comment]
> When Clicked on "Install APK" show list of multiple apps (variants) if available in build directory Like for example AndroidIDE has 2 variant it will ask which app to install.

By this i mean to say like AndroidIDE has 2 variants one for 64aarch and 32 after build it will ask user which one to install same for Sketchware Pro has 2 variants one for min api 21 and one for min api 26 so it will ask user which app to run

Means it will search .apk file in build directories and show list of those apks to user whichever user will select will be installed

> Launch Installed APP ("Launch APP") Option in Options Menu

For second one we can go for "OPEN APP"  or we can use appropriate icon for better understanding

**Comment by itsaky** [comment]
> By this i mean to say like AndroidIDE has 2 variants one for 64aarch and 32 after build it will ask user which one to install same for other project like for example lets take Sketchware Pro it has 2 variants one for min api 21 and one for min api 26 so it will ask user which app to run

This has already been added (not released yet). In the newer versions, you can select the build variant that the `Quick run` action builds.
