### ISSUE TITLE
[Особенность]: creating cpp h files

### ISSUE THREAD

**Issue by LIBBBhhh** [AndroidIDEOfficial/AndroidIDE#1346]
### Feature description

I made a utility for the Termux terminal of Android Idea that allows you to create .h or cpp as in Android studio

repo link: https://github.com/LIBBBhhh/AndroidIDE_File_Creator

I would like to see this in android ide

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
> I made a utility for the Termux terminal of Android Idea that allows you to create .h or cpp as in Android studio
> 
> repo link: https://github.com/LIBBBhhh/AndroidIDE_File_Creator
> 
> I would like to see this in android ide

I appreciate that you want to contribute to the AndroidIDE project, but we can't add this in the application. Feature for creating new files should be totally GUI based and not in terminal.
