### ISSUE TITLE
[Feature]: add package MC from Termux

### ISSUE THREAD

**Issue by Alex3474247** [AndroidIDEOfficial/AndroidIDE#1355]
### Feature description

Hi! 
I want you to add Midnight Commander to AndroidIDE to navigate the AndroidIDE filesystem more comfortably and then copy the files from IDE to internal memory or sdcard more simple. I tried to install it using pkg install or apt install but no luck.:
![Screenshot_20231001_123614_com itsaky androidide](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/17110303/2a085eb4-7a07-4cf9-b23e-88d48bd1549d)

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
It'll be added soon.

**Comment by itsaky** [comment]
Package `mc` has been added. Install with `pkg install mc`.
