### ISSUE TITLE
[Feature Request]: Add the library to the project level folder.

### ISSUE THREAD

**Issue by sb-codz** [AndroidIDEOfficial/AndroidIDE#1361]
### Feature description

I need to add a library to the project-level folder, similar to how we add files and folders.

![IMG_20231003_082845](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/6895597/8ed4502d-c092-4abe-a01d-df30797d871a)

There's a small exception when adding the library project. At that time, it should be automatically included() in the {project}/settings.gradle file, and in the {app}/build.gradle file, it should be automatically implemented(). I hope you understand. Thank you 🙏.

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
> ### Code of Conduct
> * [ ]  I agree to follow this project's Code of Conduct

You have to accept the Code of Conduct.
