### ISSUE TITLE
[Bug]: Improve getIndentAdvance() in tree sitter lang to reduce lag

### ISSUE THREAD

**Issue by itsaky** [AndroidIDEOfficial/AndroidIDE#1364]
### What happened?

When working with large files, if the editor receives an 'enter' key event, it leads to the call of `TreeSitterLanguage.getIndentAdvance()`. In this method, the language implementation parses the whole source code in order to compute the indent which results in a lag (about 1 second for 35K+ lines).

### What's the expected behavior?

The indent should be computed as quick as possible.

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by raredeveloper** [comment]
This problem can be fixed by analyzing just the current code block, right?

**Comment by itsaky** [comment]
Fixed in cdb15cea835d9e5c431535b769ddbda69849fd50.
