### ISSUE TITLE
[Bug]: auto complete cannot be exited

### ISSUE THREAD

**Issue by Rystars** [AndroidIDEOfficial/AndroidIDE#1371]
### What happened?

auto complete cannot be exited when starting projects without adding the android library (not an android project)

### What's the expected behavior?

auto complete can exit when starting projects without adding android libraries (not android projects, but projects like Java console logger)
https://github.com/AndroidIDEOfficial/AndroidIDE/assets/96302690/1791d59c-4dc8-452f-811c-c9c321750bd7

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
no output
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
The "Relevant log output" field is expected to be filled with the IDE logs.

Also, note that AndroidIDE is NOT supposed to be used for anything other than working with Android projects. Provide the IDE logs, let me examine it, but I'll work on this issue only if it could affect working with Android projects as well.

**Comment by Rystars** [comment]
> The "Relevant log output" field is expected to be filled with the IDE logs.
> 
> Also, note that AndroidIDE is NOT supposed to be used for anything other than working with Android projects. Provide the IDE logs, let me examine it, but I'll work on this issue only if it could affect working with Android projects as well.

![Screenshot_2023-10-15-14-50-01-963_com.itsaky.androidide.jpg](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/96302690/941d931a-c57b-45a9-922b-e6ec7424547f)

Maybe the problem is OpenJDK or others🤔, because when I downgraded the OpenJDK-21 version to OpenJDK-17, the complete version automatically appeared.

**Comment by Rystars** [comment]
![IMG_20231016_120340.jpg](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/96302690/96308f58-eda6-469e-8131-913da1a1cc93)

oh yes now I know what is the cause of auto complete not being able to come out.

It turns out that auto complete can't be done when sourceCompatibility in build.gradle is set to anything other than java17 version, for example: sourceCompatibility = '21'

**Comment by itsaky** [comment]
AndroidIDE's Java Compiler that is used for code completions is based on Java 17 and hence does not support newer versions of Java.

Support for Java 21 will be added in future.
