### ISSUE TITLE
[Bug]: xml preview doesn't work correctly I can't press the back button.  Pull-out menus do not appear when you click on an added view in the layout preview screen AndroidIDE

### ISSUE THREAD

**Issue by StalkerExplorer** [AndroidIDEOfficial/AndroidIDE#1372]
### What happened?

xml preview doesn't work correctly
I can't press the back button.

Pull-out menus do not appear when you click on an added view in the layout preview screen AndroidIDE

### What's the expected behavior?

correct work with xml preview

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in v2.6.0 (#1280).
