### ISSUE TITLE
[Bug]: Excessive freezing

### ISSUE THREAD

**Issue by appt2** [AndroidIDEOfficial/AndroidIDE#1376]
### What happened?

The speed of the program is extremely low

### What's the expected behavior?

Hello, thanks for making your good program. Your program is very slow when typing the code, and sometimes the code completer is not displayed at all, and it does not have any practical pictures after reloading.

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [ ] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Freeze issue was fixed in v2.6.0-beta. Try out the latest version and if the issue still persists, file a new bug report with necessary information.
