### ISSUE TITLE
[Bug]: File create failed

### ISSUE THREAD

**Issue by yzjdev** [AndroidIDEOfficial/AndroidIDE#1378]
### What happened?

Projects cannot be created with the same name
The closed project opens again, and the file list always collapses.
The build tool version is not sync with the template

### What's the expected behavior?

Projects cannot be created with the same name
The closed project opens again, and the file list always collapses.
The build tool version is not sync with the template

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Need more explanation on this issue. Also, could you provide steps to reproduce this issue (we need to know if this happens with a specific template or all of them, along with other things).

**Comment by yzjdev** [comment]
oh god!  i am so sorry!!  I excpted follow as:
1   auto rename dirctory name when create same name project.
2  expand last opend folder is failed after kill app and restart. I do not know what happen. I do not kown how to retrive the problem

**Comment by yzjdev** [comment]
https://github.com/AndroidIDEOfficial/AndroidIDE/assets/121114254/5f9cf609-4061-48c4-bbc3-8a8c7a9aa784

 for my question like this
