### ISSUE TITLE
[Bug]: 'Save' action should be disabled if the file save operation is in progress

### ISSUE THREAD

**Issue by itsaky** [AndroidIDEOfficial/AndroidIDE#1391]
### What happened?

Currently, if the user has opened a large file or the saving the file takes a long time, the 'Save' action in the toolbar is not disabled which can lead to multiple save tasks being started by the user.

### What's the expected behavior?

The 'Save' action should be disabled if the files are being saved.

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ask9027** [comment]
please, place save button after run button , so user can easily save file instead of save from menu button.
