### ISSUE TITLE
[suggestion]: Optimizing User Experience: Relocating Disconnect Logsender Options

### ISSUE THREAD

**Issue by sb-codz** [AndroidIDEOfficial/AndroidIDE#1410]
### Feature description

Dear developer,

I have a suggestion to make the app more user-friendly. Instead of having the Disconnect Logsender Options in the menu, it would be better to place them in the app's log tab at the bottom, right next to the share and clear buttons. This change would make it easier for users to access these options.

Thank you for taking this into consideration.

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
The "Disconnect log senders" button will be moved to the log view, when we work to add support for filtering and other things. But for now, I think it should stay where it is.
