### ISSUE TITLE
[Bug] Build Tools Is Installed But It Wont Usable On IDE After Setting Up by "idesetup -c"

### ISSUE THREAD

**Issue by Shinori12** [AndroidIDEOfficial/AndroidIDE#1418]
### What happened?

While at the IDE To make a new app on java/kotlin, it's settled up properly but when i want to try to build it for the first time, it won't run and didn't build the app

### What's the expected behavior?

I wasn't expecting the ide didn't run the build for the first time... And i have use AndroidIDE Since V2.1.3 and there's no such of error on the build tools...

### What version of AndroidIDE you're using?

v2.5.3

### Relevant log output

```shell
Run tasks : [assembleDebug]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.
Observed package id 'tools' in inconsistent location '/data/data/com.itsaky.androidide/files/home/android-sdk/cmdline-tools/latest' (Expected '/data/data/com.itsaky.androidide/files/home/android-sdk/tools')

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > Failed to find Build Tools revision 33.0.3

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by frknkrc44** [comment]
Try to use 33.0.2 or just remove the buildToolsVersion line in your app/build.gradle. Not a AndroidIDE issue because Google was removed the build tools 33.0.3.

**Comment by itsaky** [comment]
You can follow @frknkrc44's suggestion and update your build tools version to a valid version, or you can simply remove the `buildToolsVersion` declaration in your `build.gradle[.kts]` file.
