### ISSUE TITLE
[Feature]: Please add "true", "false", and "null" literals to auto completion.

### ISSUE THREAD

**Issue by gituser1000001** [AndroidIDEOfficial/AndroidIDE#1420]
These words are very common and this would reduce a lot of typing.

**Comment by Rystars** [comment]
and one more class that is originally built into the jdk (such as java.util.stream.Stream) is not in auto complete, so please fix it and add all the classes to AndroidIDE's auto complete

**Comment by Rystars** [comment]
and one more class that is originally built into the jdk (such as java.util.stream.Stream) is not in auto complete, so please fix it and add all the classes to AndroidIDE's auto complete
