### ISSUE TITLE
NDk SUPPORT!!

### ISSUE THREAD

**Issue by am-studios-7** [AndroidIDEOfficial/AndroidIDE#1427]
### Feature description

It is time to support NDK. This is the best Android application development environment for Android phones so far, so how can it not support NDK?
I hope this future will be given priority.

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [ ] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
> - [ ] This issue has not been reported yet.

Duplicate.
