### ISSUE TITLE
[Bug]: Unable to type letters with symbols like "í" sometimes

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1438]
### What happened?

Sometimes it is not possible to add letters that have symbols like ã, á, é, this makes it more difficult to update or write the strings in certain languages

Video showing the bug:

https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/1a12ca32-13a4-405d-99a1-65e85da84620

### What's the expected behavior?

Able to type letters with symbols in xml files

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafael2616** [comment]
Update: I noticed that this error also occurs in Kotlin files, so it's not just restricted to XML, but as I generally don't need to use these characters in KT files, I hadn't noticed before

**Comment by itsaky** [comment]
Fixed in Rosemoe/sora-editor@0667e05
