### ISSUE TITLE
[Bug]: Java fomatter indentation bug

### ISSUE THREAD

**Issue by CyberXCoder-6649** [AndroidIDEOfficial/AndroidIDE#1443]
### What happened?

When formatting code it don't use indentation which is set in settings always using indentation size: 2

### What's the expected behavior?

Must use indentation which is specified in Settings likw 4, 6, 8 In my case it's 4

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
No Error logs.
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
AndroidIDE uses Google Java Format for formatting Java source code which only has two presets :
- Google Style - 2-space indentation
- AOSP Style - 4-space indentation

Unfortunately, updating GJF's implementation is not a good idea. We have plans to add support for Eclipse's Java formatter which is much more customizable.
