### ISSUE TITLE
[Bug]: Background color is not applied to some fragments in new themes

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1457]
### What happened?

Themes that are not the original "sunny glow" do not have the background color applied to some fragments and parts of the app. The following:

- Code Editor
- App log fragment
- IDE log fragment

They continues with the "Sunny Glow" 
This causes a design inconsistency in the app. 

![Screenshot_20231112-113958](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/ada9f323-3036-4edc-8401-d4072a6b4bfe)

![Screenshot_20231112-114007](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/3e9cba2e-6f39-469c-8d06-31a14677f60d)
![Screenshot_20231112-114031](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/37de69fb-fe89-408f-956f-e91b67c246f5)

### What's the expected behavior?

Consistent color

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Editor instances that use JSON color schemes use the background color from those schemes, and hence, the Material You theming (or a normal theme) is not applied to those editors.
