### ISSUE TITLE
[Feature]: Please change the cursor position when pressing the volume keys

### ISSUE THREAD

**Issue by JohnOlowe** [AndroidIDEOfficial/AndroidIDE#1458]
### Feature description

I have used some editors designed for Android in which one can press the up volume key to move the cursor position to the right, and the down volume key to move the cursor position to the left. Please add the feature to this app and also allow us to be able to toggle the feature on or off.
This will be highly beneficial. Thank you.

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gituser1000001** [comment]
Wouldn't that quickly wear out your hardware keys? Don't you think arrow keys on your onscreen keyboard are better?

**Comment by JohnOlowe** [comment]
The onscreen keyboard that I prefer using doesn't have the arrow keys on the main letters page. And besides, those who don't want their hardware keys to wear out will just turn of the feature.

**Comment by itsaky** [comment]
I don't think mapping the volume keys to arrow keys is a good idea. The numbers of states is limited for volume keys, so it won't be sufficient for arrow keys. However, we could think of mapping those keys to `Ctrl` and `Shift` keys when we add keybinding support to the IDE. This would be disabled by default.
