### ISSUE TITLE
Projects still uses java 11 instead of 17

### ISSUE THREAD

**Issue by Baturax** [AndroidIDEOfficial/AndroidIDE#1459]
### What happened?

idesetup -c installs java17 as default and sdk 34.04 but projects still uses java11 and sdk 33.

### What's the expected behavior?

Project's default sdk and java version should be changed.

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
The JDK installation shouldn't affect the source and target versions in projects. Also, the minimum supported AGP version in AndroidIDE is 7.2.0 which doesn't support Java 17.

Even when creating a new project in Android Studio, it still sets the source and target Java versions to Java 8.

**Comment by Baturax** [comment]
> The JDK installation shouldn't affect the source and target versions in projects. Also, the minimum supported AGP version in AndroidIDE is 7.2.0 which doesn't support Java 17. Users should manually update the Java version if they want to use Java 17.
> 
> Even when creating a new project in Android Studio, it still sets the source and target Java versions to Java 8.

Thwn i tiink idesetup should install java11 as default
