### ISSUE TITLE
Unable to parse secondary library

### ISSUE THREAD

**Issue by chengzhuangjie** [AndroidIDEOfficial/AndroidIDE#1491]
### What happened?

rootProject.name = "bbs"
include ':app'
include ':library:base'
include ':library:widget'
include ':library:dkplayer-ui'
include ':library:dkplayer-java'

### What's the expected behavior?

Unable to parse secondary library

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Need more explanation on this. Why do you mean by "parse" and "secondary library"? And what's the exact issue you're facing?

**Comment by chengzhuangjie** [comment]
二级目录无法使用
include ':library:dkplayer-ui'

**Comment by chengzhuangjie** [comment]
> 对此需要更多解释。为什么你说“解析”和“辅助库”？您面临的具体问题是什么？

rootProject.name = "bbs"
include ':app'
include ':library:base'
include ':library:widget'
include ':library:dkplayer-ui'
include ':library:dkplayer-java'

二级目录无法使用

**Comment by itsaky** [comment]
Please use a translator. I'm do not speak Chinese.

**Comment by chengzhuangjie** [comment]
> 请使用翻译器。我不说中文。



> 请使用翻译器。我不说中文。

settings.gradle
include ':library:base'
include ':library:widget'
include ':library:dkplayer-ui'
include ':library:dkplayer-java'

Unable to construct, project is pulled from Android Studio dropdown

**Comment by itsaky** [comment]
Okay, so what's the error? Can you provide the build output and IDE logs?

**Comment by itsaky** [comment]
I think the issue is with the AndroidIDE's init-script plugin which tries to add dependencies to all sub-projects without considering whether the project is a real project (has a build script).

I'll test if this is correct and patch the bug ASAP.
