### ISSUE TITLE
[Feature]: ndk support for all abi

### ISSUE THREAD

**Issue by LIBBBhhh** [AndroidIDEOfficial/AndroidIDE#1492]
### Feature description

a great replacement for android studio, but not enough for complete happiness, ndk for all abi

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
Duplicate of #162.
