### ISSUE TITLE
[Bug]:  ndk project result in errors

### ISSUE THREAD

**Issue by Tanzin01** [AndroidIDEOfficial/AndroidIDE#1493]
### What happened?

Im not sure not exactlt is the error. may be cmake or environment variable. anyway idk. leaving to the experts.
[build_output.txt](https://github.com/AndroidIDEOfficial/AndroidIDE/files/13454437/build_output.txt)

### What's the expected behavior?

builds succesfully

### What version of AndroidIDE you're using?

v2.6.0

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
We do not officially support NDK in AndroidIDE.
