### ISSUE TITLE
[Bug]: Cannot access java.lang

### ISSUE THREAD

**Issue by rxvoid** [AndroidIDEOfficial/AndroidIDE#1538]
### What happened?

When I edit the java (class) file, a red line error always appeared although I did all of the setup in the terminal correctly.
![Screenshot_2023-12-06-18-37-36-70](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/51464863/84f70b29-e4d7-4a6c-9f1f-f2cfe64496db)

### What's the expected behavior?

No error should be appeared.

### What version of AndroidIDE you're using?

v2.5.0

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This issue was fixed in the recent AndroidIDE releases. Please update to the latest version of AndroidIDE.

Feel free to reopen this issue if the error is not fixed in the latest release as well.
