### ISSUE TITLE
Warning in logs when opening any xml file

### ISSUE THREAD

**Issue by gituser1000001** [AndroidIDEOfficial/AndroidIDE#1559]
This is the warning
```
LanguageSpecProvider      W   Scheme file 'locals' for type 'xml' not found
```
Is this normal?

**Comment by itsaky** [comment]
In tree sitter languages, `locals.scm` file defines the query for searching local variable declarations and their usage. This warning doesn't affect anything as we don't have any local variables in XML. But this warning should probably be removed.
