### ISSUE TITLE
These warnings show up after initializing a project

### ISSUE THREAD

**Issue by gituser1000001** [AndroidIDEOfficial/AndroidIDE#1560]
The warnings:
```
ResourceTableRegistry     W   Failed to compile /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-33/data/res/values/symbols.xml 
ResourceTableRegistry     W   Failed to compile /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-33/data/res/values/public-staging.xml 
ResourceTableRegistry     W   Failed to compile /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-33/data/res/values/public-final.xml 
ResourceTableRegistry     W   Failed to compile /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-33/data/res/values/config_telephony.xml 
```
Is it normal?

**Comment by itsaky** [comment]
> Is it normal?

Those files are not used by AndroidIDE in any manner. So, yes. It doesn't affect anything.

**Comment by gituser1000001** [comment]
Is there a way to still keep the warnings for references but also somehow have a way to inform the user to avoid possible eyebrow raising seeing them in the logs? Maybe a preference to suppress errors/warnings that are okay to ignore (with an explanation for each)?

**Comment by itsaky** [comment]
> Is there a way to still keep the warnings for references but also somehow have a way to inform the user to avoid possible eyebrow raising seeing them in the logs?

One solution could be to not parse these files at all (based on their names). But this may cause issues in future as the files under the `values` resource directory can define any type of resource. For example, a file named `colors.xml` can define `<string>` entries as well. The file names are ignored when parsing those values. Ignoring files on the basis of their names may cause issues in future. We can't ignore the warnings as the logs will be helpful in case the compiler fails to compile other necessary files.

> Maybe a preference to suppress errors/warnings that are okay to ignore (with an explanation for each)?

Adding a preference for this purpose is not a good idea in my opinion.

A possible solution could be that we log the warnings only for the first time the error is reported (or maybe randomly).

**Comment by gituser1000001** [comment]
I did mention
```
...still keep the warnings for references...
```
So I agree. Making them disappear without a trace isn't a good idea.

How about we just leave everything as is and wait until we have the log filtering feature. We then just include a default filter to exclude these okay-to-ignore errors/warnings from the logs. Users would uncheck the exclusion to see them.

**Comment by itsaky** [comment]
Sure. Closing this issue as we already have a feature request for log filtering in #1027.
