### ISSUE TITLE
[Bug]: error in build

### ISSUE THREAD

**Issue by code-with-prabhat** [AndroidIDEOfficial/AndroidIDE#1561]
### What happened?

problem occurred configuring project ':crashreporter'.
> Could not resolve all files for configuration ':crashreporter:classpath'.
   > Cannot resolve external dependency com.itsaky.androidide:gradle-plugin:2.6.1-beta because no repositories are defined.
     Required by:
         project :crashreporter
> Plugin with id 'com.itsaky.androidide' not found.

### What's the expected behavior?

problem occurred configuring project ':crashreporter'.
> Could not resolve all files for configuration ':crashreporter:classpath'.
   > Cannot resolve external dependency com.itsaky.androidide:gradle-plugin:2.6.1-beta because no repositories are defined.
     Required by:
         project :crashreporter
> Plugin with id 'com.itsaky.androidide' not found.

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
problem occurred configuring project ':crashreporter'.
> Could not resolve all files for configuration ':crashreporter:classpath'.
   > Cannot resolve external dependency com.itsaky.androidide:gradle-plugin:2.6.1-beta because no repositories are defined.
     Required by:
         project :crashreporter
> Plugin with id 'com.itsaky.androidide' not found.
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
In your Gradle builds scripts, replace

```groovy
apply plugin: ...
```

with plugin blocks :

```kt
plugins {
    id ("...")
    ...
}
