### ISSUE TITLE
[Feature]: update node js version to 20.10.0

### ISSUE THREAD

**Issue by Rystars** [AndroidIDEOfficial/AndroidIDE#1568]
### Feature description

please update nodejs version to 20.10.0 in AndroidIDE

https://nodejs.org/en

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Terminal packages are provided by [termux-packages](https://githbub.com/termux/termux-packages). It is better to wait for the package to be updated upstream for the best stability.

Also, NodeJS package is added in AndroidIDE based on community requests to only provide basic support for React Native projects. Do not expect us to add full support anytime soon.
