### ISSUE TITLE
Arabic Language Support

### ISSUE THREAD

**Issue by hussin7466** [AndroidIDEOfficial/AndroidIDE#1569]
### Feature description

 i can support for translate our app **androidide** to native arabic language to request the help from me please contact :@LookHide in telegram, thks❤️

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
You can contribute to Arabic translations on our [Crowdin project page](https://crowdin.com/project/androidide).
