### ISSUE TITLE
How to deal with it.

### ISSUE THREAD

**Issue by zjyzip** [AndroidIDEOfficial/AndroidIDE#1575]
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all files for configuration ':app:classpath'.
   > Could not download gradle-plugin-config-2.6.1-beta.jar (com.itsaky.androidide:gradle-plugin-config:2.6.1-beta)
      > Could not get resource 'https://plugins.gradle.org/m2/com/itsaky/androidide/gradle-plugin-config/2.6.1-beta/gradle-plugin-config-2.6.1-beta.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/com/itsaky/androidide/gradle-plugin-config/2.6.1-beta/gradle-plugin-config-2.6.1-beta.jar'. Received status code 403 from server: Forbidden
> Plugin with id 'com.itsaky.androidide' not found.
****

![Screenshot_20231222-235114.png](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/76038670/1d9c5002-91f4-4ead-8a2d-f8f2bdfddf24)

**Comment by itsaky** [comment]
Remove the `jcenter` repository from your project, then try again.
