### ISSUE TITLE
[Bug]: AAPT2 .androidide Daemon #1: Daemon startup failed

### ISSUE THREAD

**Issue by hacking-uajjs** [AndroidIDEOfficial/AndroidIDE#1596]
### What happened?

AAPT2 .androidide Daemon #1: Daemon startup failed

### What's the expected behavior?

AAPT2 .androidide Daemon #1: Daemon startup failed

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AAPT2 .androidide Daemon #1: Daemon startup failed
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
Show full log

**Comment by hacking-uajjs** [comment]
Run tasks : [:app:assembleDebug]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.
Adding LogSender dependency (version '2.7.0-beta') to variant 'debug' of project ':app'

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:dataBindingMergeDependencyArtifactsDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:mergeDebugResources
> Task :app:packageDebugResources
> Task :app:javaPreCompileDebug
> Task :app:mapDebugSourceSetPaths
> Task :app:checkDebugAarMetadata
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :app:parseDebugLocalResources
> Task :app:processDebugMainManifest
> Task :app:processDebugManifest
> Task :app:dataBindingGenBaseClassesDebug
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets
> Task :app:compressDebugAssets
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:checkDebugDuplicateClasses
> Task :app:desugarDebugFileDependencies
> Task :app:mergeDebugJavaResource
> Task :app:processDebugManifestForPackage
> Task :app:mergeExtDexDebug
> Task :app:mergeDebugJniLibFolders
> Task :app:mergeLibDexDebug
> Task :app:mergeDebugNativeLibs NO-SOURCE
> Task :app:stripDebugDebugSymbols NO-SOURCE
> Task :app:validateSigningDebug
> Task :app:writeDebugAppMetadata
> Task :app:writeDebugSigningConfigVersions
AAPT2 .androidide Daemon #1: Unexpected error output: /data/data/com.itsaky.androidide/files/home/.androidide/aapt2[5]: syntax error: unexpected '('
AAPT2 .androidide Daemon #0: Unexpected error output: /data/data/com.itsaky.androidide/files/home/.androidide/aapt2[5]: syntax error: unexpected '('
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform appcompat-1.6.1.aar (androidx.appcompat:appcompat:1.6.1) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/a6c4c081a78c7687adb6938b551c24c3/transformed/appcompat-1.6.1.
         > AAPT2 .androidide Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 43s
27 actionable tasks: 27 executed

**Comment by MrIkso** [comment]
[/data/data/com.itsaky.androidide/files/home/.androidide/aapt2[5]: syntax error: unexpected '(']
It not normal behaviour. Use _rm $HOME/.androidide/aapt2_ and restart androidide

**Comment by LeKruistz** [comment]
Tried deleting this and it still doesn't work

**Comment by hacking-uajjs** [comment]
Android Ide 2.6.1 Version does not have Error

**Comment by hacking-uajjs** [comment]
Android Ide 2.6.1 Version does not have Error

**Comment by anthony-china** [comment]
Has it been repaired?

**Comment by anthony-china** [comment]
No solution has been found.

**Comment by itsaky** [comment]
Can you show me the output of the following command?

```
pkg in file && file $HOME/.androidide/aapt2
```

**Comment by LeKruistz** [comment]
> Can you show me the output of the following command?
> 
> ```
> pkg in file && file $HOME/.androidide/aapt2
> ```

it installs a "file" package, and after that it shows this:

`/data/data/com.itsaky.androidide/files/home/.androidide/aapt2: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped`

**Comment by MrIkso** [comment]
> > Can you show me the output of the following command?
> > ```
> > pkg in file && file $HOME/.androidide/aapt2
> > ```
> 
> it installs a "file" package, and after that it shows this:
> 
> `/data/data/com.itsaky.androidide/files/home/.androidide/aapt2: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped`

aapt2 not for your architecture. Correct
`ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped`

**Comment by LeKruistz** [comment]
Okay then how could I correct it? Reinstalling? I knew something was wrong when it says x86

**Comment by LeKruistz** [comment]
Also is there any way to reinstall only AAPT2? I don't want to reinstall the whole tools again

**Comment by itsaky** [comment]
> > Can you show me the output of the following command?
> > ```
> > pkg in file && file $HOME/.androidide/aapt2
> > ```
> 
> it installs a "file" package, and after that it shows this:
> 
> `/data/data/com.itsaky.androidide/files/home/.androidide/aapt2: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped`

Are you using AndroidIDE is an emulator? If not, then, unless you have a `x86_64` CPU, you have installed the wrong version of AndroidIDE. Check the architecture of your CPU, then download AndroidIDE for that CPU architecture. You'll have to reinstall.

You can use CPU-Z to check your device's CPU arch. The following architectures are supported by AndroidIDE:
- `arm64-v8a` - 64-bit ARM
- `armeabi-v7a` - 32-bit ARM
- `x86_64` - 64-bit version of x86 (mostly used in PCs).

**Comment by LeKruistz** [comment]
![Screenshot_20240104-185247_CPU-Z](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/85934291/1f8e5ff1-d55d-49a5-9647-783e7f1410b7)
Well, mine is a phone with aarch64 architecture

**Comment by itsaky** [comment]
Then why did you download x86_64 variant? Anyways, I'm closing this issue.

**Comment by LeKruistz** [comment]
Seems like when i install it with idesetup -a aarch64 and reinstalling it again with idesetup -c worked, or it's just fixed and I do not need to manually set the architecture
