### ISSUE TITLE
[Bug]: Failed to bind to AndroidIDE

### ISSUE THREAD

**Issue by hacking-uajjs** [AndroidIDEOfficial/AndroidIDE#1599]
### What happened?

Failed to bind to AndroidIDE

### What's the expected behavior?

Failed to bind to AndroidIDE

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
Failed to bind to AndroidIDE
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hacking-uajjs** [comment]
![Uploading Screenshot_20240102-090210.jpg…]()

**Comment by BanDroid** [comment]
it is not a bug, this is shown if you're installing debug version of you apk in device that has no AndroidIDE

**Comment by hacking-uajjs** [comment]
Hide Failed to bind to AndroidIDE

**Comment by BanDroid** [comment]
> Hide Failed to bind to AndroidIDE

no need to hide, just install the release version if you dont need to debug it

**Comment by binx6** [comment]
**Hey bro, u gotta do this, type release, default is debug**
![IMG_20231231_212613.jpg](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/123862842/11c87f45-ce57-4ac6-986d-07456c31ec4f)

**Comment by hacking-uajjs** [comment]
assembleRelease thank you👍 not apk sign I'm use apk-singer app sign apk Install successfully

**Comment by binx6** [comment]
> assembleRelease thank you👍 not apk sign I'm use apk-singer app sign apk Install successfully

**Yeap, the default is unsigned, thus you have to sign manually**

**Comment by itsaky** [comment]
As mentioned before, `debug` builds are for testing purposes only. If you want to share your application, share its `release` build.
