### ISSUE TITLE
[Bug]: Release app not Install

### ISSUE THREAD

**Issue by hacking-uajjs** [AndroidIDEOfficial/AndroidIDE#1601]
### What happened?

app:assembleRelease apk not install

### What's the expected behavior?

App not install 

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hacking-uajjs** [comment]
![Uploading Screenshot_20240102-112125.jpg…]()

**Comment by MrIkso** [comment]
You must configure signconfig for release build

**Comment by itsaky** [comment]
Reopen this issue when you have the logs or the build output.
