### ISSUE TITLE
[Feature]: add godot project compilation feature

### ISSUE THREAD

**Issue by bitesgame** [AndroidIDEOfficial/AndroidIDE#1603]
### Feature description

![Screenshot_2024-01-03-15-23-12-912_com android chrome](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/65835193/f1afa87a-e77d-4dee-927e-d96776c75c93)

Maybe you can add it to the Android version of the Godot project compilation as well as the template for Android

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
There are no plans for this at the moment, but we might consider this in future.
