### ISSUE TITLE
[Feature]: How to install JDK 21

### ISSUE THREAD

**Issue by anthony-china** [AndroidIDEOfficial/AndroidIDE#1606]
### Feature description

Found the command for jdk17 installed, but there doesn't seem to be a command for 21

Starting build...

> Configure project :app
Adding LogSender dependency (version '2.6.1-beta') to variant 'debug' of project ':app'
Fetch 'IdeaProject' model completed in 86567ms
Fetch 'BasicAndroidProject' model completed in 597ms
Fetch 'AndroidProject' model completed in 3184ms
 2 build variants found for project ':app': [debug, release]
 Selected build variant 'debug' for project ':app'
Fetch 'VariantDependencies' model completed in 9076ms

CONFIGURE SUCCESSFUL in 1m 44s

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
To install:
```
pkg in openjdk-21
```

Then using terminal, edit the `$PREFIX/ide-environment.properties` file and put this entry (if there is already an entry with the same name, update it) :
```
JAVA_HOME=/data/data/com.itsaky.androidide/files/usr/opt/openjdk-21
```

After this, restart AndroidIDE.
