### ISSUE TITLE
[Feature]: Auto Import

### ISSUE THREAD

**Issue by therobokedi** [AndroidIDEOfficial/AndroidIDE#1607]
### Feature description

Hi.

Please add auto import like intellij idea.

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itSMcodez** [comment]
It's already added in AndroidIDE

**Comment by therobokedi** [comment]
How? I dont seen it?

**Comment by AmanRajAryan** [comment]
Just long press in Java code anywhere (not on code ) and you will see the option for "fix imports" , "remove unused imports" and many more
