### ISSUE TITLE
[Bug]: Daemon Failed!

### ISSUE THREAD

**Issue by AllanFuego** [AndroidIDEOfficial/AndroidIDE#1612]
### What happened?

Run tasks : [:app:processDebugResources]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.
Adding LogSender dependency (version '2.7.0-beta') to variant 'debug' of project ':app'

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:mapDebugSourceSetPaths UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:packageDebugResources UP-TO-DATE
> Task :app:parseDebugLocalResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
AAPT2 .androidide Daemon #0: Unexpected error output: /data/data/com.itsaky.androidide/files/home/.androidide/aapt2[5]: syntax error: unexpected '('
AAPT2 .androidide Daemon #1: Unexpected error output: /data/data/com.itsaky.androidide/files/home/.androidide/aapt2[5]: syntax error: unexpected '('
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform appcompat-1.6.1.aar (androidx.appcompat:appcompat:1.6.1) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/a6c4c081a78c7687adb6938b551c24c3/transformed/appcompat-1.6.1.
         > AAPT2 .androidide Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.9.0.aar (androidx.core:core:1.9.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/235a55cb36ea386bc8e2d997cc49aa1a/transformed/core-1.9.0.
         > AAPT2 .androidide Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
12 actionable tasks: 1 executed, 11 up-to-date

### What's the expected behavior?

Build failed !!
Version :- 2.7.0

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pavel5750cz** [comment]
I got this:
AAPT2 .androidide Daemon #0: Unexpected error output: /data/data/com.itsaky.androidide/files/home/.androidide/aapt2[5]: syntax error: unexpected '('
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > AAPT2 .androidide Daemon #0: Daemon startup failed
     This should not happen under normal circumstances, please file an issue if it does.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by AllanFuego** [comment]
> I got this, updated the ide and glad i can type lot of commas when caling function with no crashy building apo caueed this to me:
> 
> AAPT2 .androidide Daemon #0: Unexpected error output: /data/data/com.itsaky.androidide/files/home/.androidide/aapt2[5]: syntax error: unexpected '('
> 
> > Task :app:processDebugResources FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:processDebugResources'.
> 
> > A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
> > AAPT2 .androidide Daemon #0: Daemon startup failed
> > This should not happen under normal circumstances, please file an issue if it does.
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org

Got any solution bro??i m again downgrading to 2.5 beta i guess

**Comment by pavel5750cz** [comment]
I had 2.6.0 and updated coz blank file name and content when opened the file, was blank up and in and reset of data i did and idesetup c gave errors like server no anymore there so i went update

**Comment by pavel5750cz** [comment]
I have problem fixed with newest 32bit version even if phone is 64bit. Apt update AND upgrade and setup c and u go it works, dont leave the termin start i sugest so it no disconect.  If theres an syntax error in ide files, you canaccess em in data/data of the ide app. You can acces only this app data thou coz its private memory andif u wanna aces other aps, u need root which loses g pay partial or whole for example

**Comment by itsaky** [comment]
There was a problem with the `aapt2` binary in the v2.7.0-beta release. The [GitHub release](https://github.com/AndroidIDEOfficial/AndroidIDE/releases/tag/v2.7.0-beta) has been updated the issue has been fixed. Please re-download the APK and the issue should be resolved after that.
