### ISSUE TITLE
Hope to update Kotlin soon.

### ISSUE THREAD

**Issue by anthony-china** [AndroidIDEOfficial/AndroidIDE#1614]
### Feature description

希望可以快点更新科特林

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Duplicate of #211

Also, please use English when creating issues or pull requests.
