### ISSUE TITLE
[Bug]: Installation loop

### ISSUE THREAD

**Issue by equin0X35** [AndroidIDEOfficial/AndroidIDE#1616]
### What happened?

this is the first time i install the app, the latest pre-release. so i just go with the flow and at the SDK Installation, i leave all the settings where it was, i just change the JDK version to 21. after the installation of packages has complete, it close the terminal, and the app is still at the SDK Installation page.

### What's the expected behavior?

I am expecting the app to proceed into the home page (e.g where we create/open existing project, preference, etc).

### What version of AndroidIDE you're using?

v2.7.0-beta

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BanDroid** [comment]
"i leave all the settings where it was" and then "i just change the JDK version to 21" does not have the same meaning.

fyi, jdk 21 still experimental.

**Comment by equin0X35** [comment]
so okay, yeah, however i also try JDK version 17, but it is same, i wonder why...

**Comment by itsaky** [comment]
Thanks for the report, I'll look into the issue.

**Comment by equin0X35** [comment]
i see, it is just a minor bug.. for now i have found a simple temporary solution, i renamed the "jdk-21.0.1" folder to "jdk-17.0" and it works as expected😁, i hope it'll fix soon.
