### ISSUE TITLE
[Bug]: Missing Components

### ISSUE THREAD

**Issue by equin0X35** [AndroidIDEOfficial/AndroidIDE#1619]
### What happened?

after the gradle initialization and building the app, this what i get:

**Failed to install the following SDK components: 
build-tools;30.0.3 Android SDK Build-Tools 30.0.3**

even i install the Android SDK BUILD-TOOL 30.0.3 ( _the build-tool is from the previous version of this app_ ),  this exception still appears.. where did i get wrong?? Thanks.

### What's the expected behavior?

builds the app.

### What version of AndroidIDE you're using?

v2.7.0-beta

### Relevant log output

```shell
Run tasks : [:app:assembleDebug]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.
Adding LogSender dependency (version '2.7.0-beta') to variant 'debug' of project ':app'
Warning: Dependant package with key emulator not found!

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > Failed to install the following SDK components:
         build-tools;30.0.3 Android SDK Build-Tools 30.0.3
     Install the missing components using the SDK manager in Android Studio.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
v33.0.3 of the build tools was removed from the Google components repository for some reason. You can upgrade (or downgrade) your build tools version to fix the error. You can also remove the `buildToolsVersion` from your module level build script to let Android Gradle Plugin automatically determine the build tools.

**Comment by equin0X35** [comment]
there is no buildToolsVersion in the script but it end up specifiying the buildToolsVersion to the latest version. Thanks, keep improving the app🎉🎉

**Comment by Jisu-Woniu** [comment]
So where and how to add the configuration? Can you specify it?

**Comment by itsaky** [comment]
> So where and how to add the configuration? Can you specify it?

You can specify the `buildToolsVersion` in your module-level `build.gradle` or `build.gradle.kts` file. It is usually the `app/build.gradle[.kts]` file.

In that module-level build script, you can specify the buildToolsVersion like the following :

```kt
android {
    ...
    buildToolsVersion("34.0.0")
}
```

**Comment by Jisu-Woniu** [comment]
There's a new error message:

```
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform core-1.8.0.aar (androidx.core:core:1.8.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/ef7e1b98507d7d4bda90d03defcba420/transformed/core-1.8.0.
         > AAPT2 .androidide Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.8.0.aar (androidx.core:core:1.8.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/ef7e1b98507d7d4bda90d03defcba420/transformed/core-1.8.0.
         > AAPT2 .androidide Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.

```
