### ISSUE TITLE
Settings/Code Editor/Color Scheme

### ISSUE THREAD

**Issue by timscriptov** [AndroidIDEOfficial/AndroidIDE#1622]
### What happened?

AndroidIDE Crash Report
Version : v2.7.0-beta (27001)
CI Build : true
Branch : main
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : 22101320G

Stacktrace:
java.lang.IllegalArgumentException: Entries must have exactly one item checked, however, 0 were checked
	at com.itsaky.androidide.preferences.SingleChoicePreference.onConfigureDialogChoices(Unknown Source:78)
	at com.itsaky.androidide.preferences.ChoiceBasedDialogPreference.onConfigureDialog(Unknown Source:26)
	at com.itsaky.androidide.preferences.DialogPreference.onPreferenceClick(Unknown Source:38)
	at org.apache.commons.io.FileUtils$$ExternalSyntheticLambda0.onPreferenceClick(Unknown Source:23)
	at androidx.preference.Preference.performClick(Unknown Source:19)
	at androidx.preference.Preference$1.onClick(Unknown Source:260)
	at android.view.View.performClick(View.java:7556)
	at android.view.View.performClickInternal(View.java:7533)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29663)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8400)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

    

### What's the expected behavior?

Should have offered to select an editor theme

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timscriptov** [comment]
Compose Template Build:

Запустить задачу : [:app:assembleDebug]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.
Adding LogSender dependency (version '2.7.0-beta') to variant 'debug' of project ':app'
Warning: Dependant package with key emulator not found!

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > Failed to install the following SDK components:
         build-tools;30.0.3 Android SDK Build-Tools 30.0.3
     Install the missing components using the SDK manager in Android Studio.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by itsaky** [comment]
@timscriptov Could you provide a little context here? What preference were you changing when the IDE crashed?

For the build tools issue, see #1619.

**Comment by timscriptov** [comment]
@itsaky Запустить задачу : [:app:assembleDebug]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.
w: file:///storage/emulated/0/AndroidIDEProjects/ExCompose/app/build.gradle.kts:11:5: 'buildToolsVersion(String): Unit' is deprecated. Replaced by buildToolsVersion property
w: file:///storage/emulated/0/AndroidIDEProjects/ExCompose/app/build.gradle.kts:43:5: 'packagingOptions(Packaging.() -> Unit): Unit' is deprecated. Renamed to packaging
Adding LogSender dependency (version '2.7.0-beta') to variant 'debug' of project ':app'
WARNING: We recommend using a newer Android Gradle plugin to use compileSdk = 34

This Android Gradle plugin (8.0.0) was tested up to compileSdk = 33.

You are strongly encouraged to update your project to use a newer
Android Gradle plugin that has been tested with compileSdk = 34.

If you are already using the latest version of the Android Gradle plugin,
you may need to wait until a newer version with support for compileSdk = 34 is available.

To suppress this warning, add/update
    android.suppressUnsupportedCompileSdk=34
to this project's gradle.properties.

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:generateDebugResValues
> Task :app:checkDebugAarMetadata
> Task :app:mapDebugSourceSetPaths
> Task :app:generateDebugResources
> Task :app:packageDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :app:parseDebugLocalResources
> Task :app:mergeDebugResources
> Task :app:processDebugMainManifest
> Task :app:processDebugManifest
> Task :app:javaPreCompileDebug
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets
> Task :app:compressDebugAssets
> Task :app:desugarDebugFileDependencies
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:checkDebugDuplicateClasses
> Task :app:mergeDebugJniLibFolders
> Task :app:processDebugManifestForPackage
> Task :app:mergeExtDexDebug
> Task :app:mergeDebugNativeLibs NO-SOURCE
> Task :app:stripDebugDebugSymbols NO-SOURCE
> Task :app:mergeLibDexDebug
> Task :app:validateSigningDebug
> Task :app:writeDebugAppMetadata
> Task :app:writeDebugSigningConfigVersions
AAPT2 .androidide Daemon #0: Unexpected error output: /data/data/com.itsaky.androidide/files/home/.androidide/aapt2[5]: syntax error: unexpected '('
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform core-1.8.0.aar (androidx.core:core:1.8.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/ef7e1b98507d7d4bda90d03defcba420/transformed/core-1.8.0.
         > AAPT2 .androidide Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.8.0.aar (androidx.core:core:1.8.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/ef7e1b98507d7d4bda90d03defcba420/transformed/core-1.8.0.
         > AAPT2 .androidide Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 49s
24 actionable tasks: 24 executed
