### ISSUE TITLE
Never stop loading

### ISSUE THREAD

**Issue by limelect** [AndroidIDEOfficial/AndroidIDE#1658]
### What happened?

I made a  new project, and it works.
opened the application a second time it never stopped loading.
phone s21

### What's the expected behavior?

to load

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
> I made a new project, and it works.
opened the application a second time it never stopped loading.
phone s21

You need to provide more information (like the build output and the IDE logs) so that we can help you.

**Comment by limelect** [comment]
After a few days, it works. Very erratic
