### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Mohammad-Azizi** [AndroidIDEOfficial/AndroidIDE#1661]
Fixed a bug which caused the LogSenderService to disconnect (#1385).

This isn't fixed still it is pressist

**Comment by Mohammad-Azizi** [comment]
Because reporting as a bug it is required to do it on the web so the only option is allowed is this 

Ok fine i'm going to report it through the bug issue

**Comment by gituser1000001** [comment]
I'm using the github app and have the same problem. When we click the report templates, the app does not open it directly but tries to send it to a web browser where we need to log in again (which I don't like doing). The blank issue opens fine inside the app.
