### ISSUE TITLE
Log not clearing

### ISSUE THREAD

**Issue by CyberXCoder-6649** [AndroidIDEOfficial/AndroidIDE#1672]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

https://github.com/AndroidIDEOfficial/AndroidIDE/assets/86068846/23a044c7-555c-403a-935f-8d314c9cbb37

Log not clearing when cleared it shows again and again as you can see in video

### Expected behavior

Should clear log properly

### Version name

Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 29
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-G965F

### Download source

GitHub

### Relevant log output

```bash
No logs
```

**Comment by itsaky** [comment]
I don't think this affects anything.
