### ISSUE TITLE
[BUG]Cannot resolve external dependency com.itsaky.androidide:gradle-plugin:2.7.0-beta because no repositories are defined.

### ISSUE THREAD

**Issue by dudu-Dev0** [AndroidIDEOfficial/AndroidIDE#1675]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

> Cannot resolve external dependency com.itsaky.androidide:gradle-plugin:2.7.0-beta because no repositories are defined.
     Required by:
         project :DanmakuFlameMaster
> Plugin with id 'com.itsaky.androidide' not found.

### Expected behavior

sync success

### Version name

Version : v2.7.0-beta (27001)
CI Build : true
Branch : main
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 31
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : HUAWEI
Device : NCO-AL00

### Download source

GitHub

### Relevant log output

```bash
Starting build...

> Configure project :app
AGPBI: {"kind":"warning","text":"The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.","sources":[{}]}
Adding LogSender dependency (version '2.7.0-beta') to variant 'debug' of project ':app'

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':DanmakuFlameMaster'.
> Could not resolve all artifacts for configuration ':DanmakuFlameMaster:classpath'.
   > Cannot resolve external dependency com.itsaky.androidide:gradle-plugin:2.7.0-beta because no repositories are defined.
     Required by:
         project :DanmakuFlameMaster
> Plugin with id 'com.itsaky.androidide' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE FAILED in 1m 57s
```

**Comment by MrIkso** [comment]
Use latest version from GitHub actions

**Comment by dudu-Dev0** [comment]
> Use latest version from GitHub actions

solved
