### ISSUE TITLE
Facing a issue :- Unable to find package Java.lang in class path 

### ISSUE THREAD

**Issue by mohammad-ayan-008** [AndroidIDEOfficial/AndroidIDE#1683]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

I've been facing this issue in the latest beta version 

### Expected behavior

GradleBuildService        I   Showing notification to user... 
EditorActivity            I   Connected to Gradle build service 
ToolingServerRunner       I   Starting tooling API server... 
EditorActivity            D   No variant selection information available. Default build variants will be selected. 
EditorActivity            D   Is project initialized: false 
EditorActivity            D   Sending init request to tooling server.. 
EditorActivity            D   onBuildStatusChanged: isInitializing: true, isBuildInProgress: false 
ToolingApiServer          D   ToolingApiMain             Server started. Will run until shutdown message is received...  
ToolingApiServer          D   ToolingApiMain             Running on Java version:  17-internal  
ToolingApiServer          D   ToolingApiServerImpl       Got initialize request  InitializeProjectParams(directory=/storage/emulated/0/AndroidIDEProjects/My Application2, gradleDistribution=GradleDistributionParams(type=GRADLE_WRAPPER, value=), androidParams=AndroidInitializationParams(variantSelections={}))  
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiErrorStream     E   SLF4J: No SLF4J providers were found. 
ToolingApiErrorStream     E   SLF4J: Defaulting to no-operation (NOP) logger implementation 
ToolingApiErrorStream     E   SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details. 
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle wrapper for build...  
ToolingApiServer          D   StopWatch                  Connector created in 71ms  
EditorActivity            D   onBuildStatusChanged: isInitializing: true, isBuildInProgress: true 
ToolingApiServer          D   StopWatch                  Project connection established in 27ms  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2, -Pandroidide.logsender.isEnabled=true]  
ToolingApiServer          W   ProjectReader              Starting build. See build output for more details...  
EditorActivity            I   Opening file at index:  0  file:   /storage/emulated/0/AndroidIDEProjects/My Application2/app/src/main/java/com/example/myapplication2/MainActivity.java 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AndroidIDEProjects/My Application2/app/src/main/java/com/example/myapplication2/MainActivity.java, allFiles=[OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/My Application2/app/src/main/java/com/example/myapplication2/MainActivity.java, selection=Range(start=Position(line=0, column=0, index=0), end=Position(line=0, column=0, index=0)))]) 
ToolingApiServer          D   ProjectReader              Build action executed. Result:  com.itsaky.androidide.tooling.impl.internal.ProjectImpl@3f2b8540  
ToolingApiServer          D   StopWatch                  Project read successful in 36446ms  
ToolingApiServer          D   StopWatch                  Connection to project completed in 36553ms  
StopWatch                 D   Transform project proxy completed in 358ms 
ProjectManagerImpl        I   Found 1 project sync issues: [DefaultSyncIssue(data=build-tools;30.0.3, message=Failed to install the following SDK components:
ProjectManagerImpl        I      build-tools;30.0.3 Android SDK Build-Tools 30.0.3
ProjectManagerImpl        I  Install the missing components using the SDK manager in Android Studio.
ProjectManagerImpl        I  , multiLineMessage=null, severity=2, type=24)] 
JavaModule                I   Indexing sources and classpaths for project:  : 
AndroidModule             I   Indexing sources and classpaths for project:  :app 
StopWatch                 D   Indexing sources completed in 0ms 
JavaModule                D   Found 0 source files. 
StopWatch                 D   Indexing classpaths completed in 0ms 
JavaModule                D   Found 0 classpaths. 
StopWatch                 D   Indexing sources completed in 16ms 
AndroidModule             D   Found 1 source files. 
StopWatch                 D   Indexing classpaths completed in 336ms 
AndroidModule             D   Found 2301 classpaths. 
StopWatch                 D   Indexing 0 bootclasspaths completed in 0ms 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
AndroidModule             I   Created 20 resource tables for 20 dependencies of module ':app' 
StopWatch                 D   Read resources for module : :app completed in 739ms 
StopWatch                 D   Setup project completed in 1097ms 
StopWatch                 D   Indexing sources completed in 0ms 
JavaModule                D   Found 0 source files. 
StopWatch                 D   Indexing sources completed in 5ms 
AndroidModule             D   Found 1 source files. 
ILanguageServerRegistry   D   Dispatching ProjectInitializedEvent to language servers... 
SourceFileManager         I   Creating source file manager instance for module:  AndroidModule: :app 
StopWatch                 D   Indexing 0 bootclasspaths completed in 0ms 
Parser_Builder            D   Analyzing:  /storage/emulated/0/AndroidIDEProjects/My Application2/app/src/main/java/com/example/myapplication2/MainActivity.java 
StopWatch                 D   Parsed treees in 67ms 
StopWatch                 D   Processed trees in 0ms 
StopWatch                 D   Analyzed all trees in 6ms 
Parser_Builder            I   Analyze file completed. Found 8 diagnostic items 
EditorActivity            D   onBuildStatusChanged: isInitializing: false, isBuildInProgress: false 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
EditorActivity            D   onBuildStatusChanged: isInitializing: false, isBuildInProgress: false 

### Version name

![Screenshot_2024-01-28-16-45-14-787_com itsaky androidide](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/107920513/20b4419f-54e7-4b0a-8117-ee15652266e9)
![Screenshot_2024-01-28-16-45-18-291_com itsaky androidide](https://github.com/AndroidIDEOfficial/Andro
![Screenshot_2024-01-28-16-45-58-959_com itsaky androidide](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/107920513/5cb56e3e-76a0-4e73-a9e6-f37a50b5b5d1)
idIDE/assets/107920513/c97ee9ed-cc0b-4762-8185-12f0f8b34484)
![Screenshot_2024-01-28-16-45-37-047_com itsaky androidide](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/107920513/f8c3217b-07b5-4f32-b800-28bc198988c6)

### Download source

GitHub

### Relevant log output

```bash
Starting build...

> Configure project :app
Adding LogSender dependency (version '2.7.1-beta') to variant 'debug' of project ':app'
Fetch 'IdeaProject' model completed in 709ms
Warning: Dependant package with key emulator not found!
Fetch 'BasicAndroidProject' model completed in 370ms
Fetch 'AndroidProject' model completed in 21ms
 2 build variants found for project ':app': [debug, release]
 Selected build variant 'debug' for project ':app'
Fetch 'VariantDependencies' model completed in 306ms

CONFIGURE SUCCESSFUL in 1s
```

**Comment by itsaky** [comment]
> Failed to install the following SDK components:
ProjectManagerImpl I build-tools;30.0.3 Android SDK Build-Tools 30.0.3

Edit your `app/build.gradle` file and change the `buildToolsVersion` to `34.0.4` (or any other version that you would like to use in your project).
