### ISSUE TITLE
Consider reducing minimimum value of minSDK

### ISSUE THREAD

**Issue by StevanWhite** [AndroidIDEOfficial/AndroidIDE#1684]
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

I build some simple apps in Android Studio with a minSDK set to 8, and I actually test them on old phones.

But the minimum minSDK allowed by AndroidIDE is currently 16.  
If there was no technical reason for this particular value, please reduce it.

### Use Case

Some people hold on to their phones for a long time.  I have friends that do.  
As a developer, I like to make apps that support their phones, rather than insisting they get a new one.

### Benefits

Users would gain the ability to build for older phones.

**Comment by itsaky** [comment]
> But the minimum minSDK allowed by AndroidIDE is currently 16.

There are no restrictions on the minimum SDK version that you can use in your projects. If you want to use an older version, just update your build configuration (min SDK and dependencies) and it should work fine.

The current templates have minimum SDK of API 16, which is not too old, not too new and good enough for starting new projects. Unless there are more requests from the community to do so, I don't think this will be implemented.
