### ISSUE TITLE
Error while Remotely adding dependencies from github

### ISSUE THREAD

**Issue by bkayJnr12** [AndroidIDEOfficial/AndroidIDE#1690]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

I'm trying to add some new dependencies like from androidx and github ,,, the project synchronises perfectly but there's an error while building the project please help

How do I cache a dependency for offline mode

### Expected behavior

Build error

### Version name

Android IDE 2.7.1-beta

### Download source

F-Droid

### Relevant log output

```bash
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.github.dakatso:livebutton:1.0.0.
     Required by:
         project :app
      > No cached version of com.github.dakatso:livebutton:1.0.0 available for offline mode.
      > No cached version of com.github.dakatso:livebutton:1.0.0 available for offline mode.
      > No cached version of com.github.dakatso:livebutton:1.0.0 available for offline mode.
      > No cached version of com.github.dakatso:livebutton:1.0.0 available for offline mode.
      > No cached version of com.github.dakatso:livebutton:1.0.0 available for offline mode.
      > No cached version of com.github.dakatso:livebutton:1.0.0 available for offline mode.
      > No cached version of com.github.dakatso:livebutton:1.0.0 available for offline mode.
```

**Comment by itsaky** [comment]
You have offline mode enabled. Go to IDE Preferences -> Build & Run -> Additional Gradle Commands and deselect the `--offline` option. Then try to build the project again.
