### ISSUE TITLE
Is it possible to use Gradle in offline mode?

### ISSUE THREAD

**Issue by Lucky390163** [AndroidIDEOfficial/AndroidIDE#1695]
Can i work on my projects offline like same as online please tell as i have updated all gradle tools help please.

**Comment by itsaky** [comment]
You can enable the `--offline` flag from IDE preferences -> Build & Run -> Additional Gradle commands. You can learn more about this flag [here](https://docs.gradle.org/current/userguide/dynamic_versions.html#sec:offline-mode).

Please note that you before you enable offline mode, you should build your project at least once. This will ensure that all the required dependencies are downloaded and cached. Once you have done that, you can enable offline mode. However, if you update your Gradle build scripts (build.gradle files) to add a new dependency and you have offline mode enabled, the build will fail. You'll have to disable offline mode in that case.

Important: Give a proper title to the issues and pull requests you create. This won't be tolerated again.
