### ISSUE TITLE
No more nonsense or spam

### ISSUE THREAD

**Issue by Lucky390163** [AndroidIDEOfficial/AndroidIDE#1709]
You locked my feedback because of spam.For improving your app experience but you are completely not sn good developer.I thought i will make an small donation plan canceled i will give it to someone else who really expect and need it.

I will use Official android studio ide instead of this Better luck next time i also do not like disturbance or you will be reported.

**Comment by BanDroid** [comment]
sometimes what you gotta do is read, especially the code of conduct, if you're not happy with the result, dont cry and dont being toxic, your account could be banned by official github support for being abusive and not following the code of conduct.

**Comment by BanDroid** [comment]
i had to report it to official github support for abusive content, next time, just read and follow, it's not that hard, see other people doing it correctly.

**Comment by Lucky390163** [comment]
Go asshole
