### ISSUE TITLE
Installation error in terminal

### ISSUE THREAD

**Issue by everskyblue** [AndroidIDEOfficial/AndroidIDE#1719]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

Installation cannot be completed because the server cannot find the packages . There is no termux-change-repo command

### Expected behavior

Change repository or the server will work 

### Version name

2.7.1-beta

### Download source

GitHub

### Relevant log output

```bash
Installation directory does not exist. Creating directory...
Update packages...
Ign:1 https://androidide.com/packages/apt/termux-main stable InRelease
Err:2 https://androidide.com/packages/apt/termux-main stable Release
  404  Not Found [IP: 85.13.147.150 443]
Reading package lists... Done
E: The repository 'https://androidide.com/packages/apt/termux-main stable Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.

[Process completed (code 100) - press Enter]
```

**Comment by BanDroid** [comment]
update androidide to latest version, or update the repository manually from androidide.com to packages.androidide.com.

also, androidide did not have `termux-change-repo` because androidide and termux are different apk, that command was specific for termux, not androidide.
