### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method readNBytes(I) while cloning git repository

### ISSUE THREAD

**Issue by kisonix** [AndroidIDEOfficial/AndroidIDE#1720]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

I believed it's cause by jgit dependency version.
Downgrading it should be worked.
`readNBytes()` was only available in API 33 =<
Ref
[Same issues on eclipse's bug report form](https://bugs.eclipse.org/bugs/show_bug.cgi?id=582423)
and
[Android 13 New APIs](https://developer.android.com/about/versions/13/features#core-libraries)

[Screenshot](https://i.imgur.com/AU74TzJ.jpeg)

### Expected behavior

To not be crashed

### Version name

v2.7.1-beta-armeabi-v7a

### Download source

GitHub

### Relevant log output

```bash
`java.lang.NoSuchMethodError: No virtual method readNBytes(I)[B in class Lorg/eclipse/jgit/util/io/SilentFileInputStream; or its super classes (declaration of 'org.eclipse.jgit.util.io.SilentFileInputStream`
```

**Comment by itsaky** [comment]
Fixed with 7705c06dcce95d35ef6d0b9360d916dcaf5d0624 and a8b1ac41a166bfdc3c8ef26dadf2e6ff1c22f91f.
