### ISSUE TITLE
Project Initialization Failed

### ISSUE THREAD

**Issue by LenicoMarak** [AndroidIDEOfficial/AndroidIDE#1723]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

Could not open cp_init generic class cache for initialization script '/data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle' (/data/data/com.itsaky.androidide/files/home/.gradle/caches/8.1.1/scripts/6qdjkb6rq0cppo2sendc74wks).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

### Expected behavior

When creating project it says first time Initialization may take 10-15 minutes I wait but it was not as I expected 

### Version name

Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 29
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : motorola
Device : motorolaonepower

### Download source

F-Droid

### Relevant log output

```bash
ToolingApiServer          W   ProjectReader              Starting build. See build output for more details...  
ToolingApiServer          E   ToolingApiServerImpl       Failed to initialize project 
ToolingApiServer          E  java.lang.IllegalArgumentException: Unsupported class file major version 65
ToolingApiServer          E  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
ToolingApiServer          E  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
ToolingApiServer          E  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
ToolingApiServer          E  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
ToolingApiServer          E   Caused by: BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65
```

**Comment by itsaky** [comment]
It seems like you're using Java 21 (class file major version 65). Update Gradle to v8.4 or newer to resolve the issue (support for JDK 21 was added in Gradle 8.4).

**Comment by LenicoMarak** [comment]
Thank you for your help..
Where should I update the gradle .I didn't find package named Gradle

**Comment by itsaky** [comment]
Here's how you can update to Gradle 8.6 :

You can edit the `gradle/wrapper/gradle-wrapper.properties` file in your project and update the `distributionUrl` to use Gradle 8.6 :
```properties
distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-bin.zip
```

There are other ways to update the Gradle version. Read the [documentation](https://docs.gradle.org/current/userguide/upgrading_version_8.html) to learn more.
