### ISSUE TITLE
Typing Lag

### ISSUE THREAD

**Issue by pavel5750cz** [AndroidIDEOfficial/AndroidIDE#1725]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

Android unlike windows sucks at handling large text files, i have 1704 lines and 49 277 characters/bytes, it is getting lagy across the file as i type so i gotta use external File Manager Plus for it.

### Expected behavior

Well the issue glcould be solved by spliting tbe string somehow, file manager plus does it somehow and this app, got a way u can implement too: https://play.google.com/store/apps/details?id=com.lapay.xmleditor (Its not for java but it handles large text good too. For now i will likely be using external editor for the large file. Else IDE works Good and game gonna be released at 2025 year from it.

### Version name

Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A202F
Model: Samsung Galaxy A20e

### Download source

F-Droid

**Comment by itsaky** [comment]
This seems to be similar to #1364.
