### ISSUE TITLE
logsender cant be cached

### ISSUE THREAD

**Issue by BanDroid** [AndroidIDEOfficial/AndroidIDE#1730]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

the sync or build always need internet connection, no matter what flag is being used (--build-cache or --offline), giving error of logsender cant be downloaded.

### Expected behavior

build or sync successfully.

### Version name

Version : v2.7.1-beta (27102)
CI Build : true
Branch : dev
Commit : 77bfdea16
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 29
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : INFINIX MOBILITY LIMITED
Device : InfinixX692

### Download source

GitHub

**Comment by itsaky** [comment]
@BanDroid Can you provide a sample project to reproduce this issue?

**Comment by BanDroid** [comment]
no sample project, any project i just created from template having the same behavior, i have send you [the video](https://t.me/AndroidIDE_Discussions/63735/114335) record on telegram before.

**Comment by itsaky** [comment]
I'm unable to reproduce this issue by enabling `--build-cache` in preferences. However, I suspect that this issue might be occurring due to changing SNAPSHOT dependency of the `gradle-plugin`. I added a fix for the same. Can you try out the latest build and let me know the results?

**Comment by BanDroid** [comment]
yeah, i'll try it tonight.

edit:
it does work fine now. i'll close this.
