### ISSUE TITLE
[Bug]: files app crashing

### ISSUE THREAD

**Issue by saifmukhtar** [AndroidIDEOfficial/AndroidIDE#1731]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

when opening project from "open existing projects" files app crashes and return to home screen 
[AndroidIDE-LOG-2024-02-17_19:44:39.686.txt](https://github.com/AndroidIDEOfficial/AndroidIDE/files/14319098/AndroidIDE-LOG-2024-02-17_19.44.39.686.txt)

### Expected behavior

File app must be open so that project folder can be selected 

### Version name

Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : realme
Device : Realme5i

### Download source

GitHub

**Comment by itsaky** [comment]
If the IDE crashes, you are required to provide the crash report containing the stack trace. The log file you provided does not contain anything relevant to a crash.
