### ISSUE TITLE
[Bug] AGP 8.3.0 fails

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1744]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

Just a remind to you to add support for Android Gradle Plugin 8.3.0 launched today

### Expected behavior

Sync project successful

### Version name

Lastest Dev Version

### Download source

GitHub

### Relevant log output

```bash
No stacktraces
```

**Comment by binx6** [comment]
See #1737

**Comment by Rafael2616** [comment]
> See #1737

I saw this issue, but this problem refers to version 8.4 alpha XX, which will not be supported until it becomes stable, as these are about the release version of the plugin which has priority in support

**Comment by itsaky** [comment]
Support for AGP 8.3.0 has been added in d5762bddb84996aa1f8929de253004e8a26b516b.

**Comment by Rafael2616** [comment]
Thanks, i`ii test 👍
