### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by elmehdiouldabou** [AndroidIDEOfficial/AndroidIDE#1763]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

com.MyPackage.databinding.ActivityMainBinding does not exist

### Expected behavior

Error

### Version name

Version : v2.7.1-beta (27101)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : armeabi-v7a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27101
SDK Version : 29
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : HUAWEI
Device : MAR-LX1A

### Download source

F-Droid

**Comment by itsaky** [comment]
Ensure view binding is enabled, then build your project.
