### ISSUE TITLE
Code formatting suggestions

### ISSUE THREAD

**Issue by LsxMm** [AndroidIDEOfficial/AndroidIDE#1770]
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

Suggest Java code formatting
1. When formatting, do not wrap lines automatically or choose whether to split attributes into new lines like in XML
2. When formatting, I always select all options. This is a complicated operation. I suggest adding a formatting option in the Tabs section to format the entire file. Alternatively, I can add an additional option to organize the import package

### Use Case

More convenient to operate

### Benefits

Writing code is more comfortable

**Comment by itsaky** [comment]
> When formatting, do not wrap lines automatically or choose whether to split attributes into new lines like in XML

Currently, only Google Java Format is supported for formatting Java files, which does not allow customizing the format operation. However, we have plans to implement a customizable formatter like Eclipse's (#1466) or our own formatter.

> When formatting, I always select all options. This is a complicated operation. I suggest adding a formatting option in the 
> Tabs section to format the entire file.

If nothing is selected, the formatter formats all of the text. To achieve this, you can click on the cursor and the editor will show the text actions without selecting any text.

> Alternatively, I can add an additional option to organize the import package.

The `Organize imports` action for Java files is available in the code actions menu (accessible from editor text actions). See [Java code actions](https://docs.androidide.com/user/editor/java-code-actions.html) for more details.
