### ISSUE TITLE
AndroidIDE crashes

### ISSUE THREAD

**Issue by trindadeDevAndroid** [AndroidIDEOfficial/AndroidIDE#1772]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

I'm creating a project and it happened that when I got to the app:mergeDebugResources task, AndroidIDE simply closed it and reopened it again, this happened more than once!

### Expected behavior

I wanted my project to compile normally and generate an apk

### Version name

2.7.1 beta

### Download source

GitHub

**Comment by BanDroid** [comment]
please provide your device information

**Comment by itsaky** [comment]
Reopen this issue with the crash log, device information and the steps to reproduce this issue (or a sample project, if applicable).

**Comment by trindadeDevAndroid** [comment]
my device is Samsung galaxy a20, have 3GB of ram, 32 of rom, Error it happens  in my project made on android 12 4gb ram  , Other projects compile normal and with sucess, Project with error is: https://github.com/GamEngine/GamEngine/
