### ISSUE TITLE
databinding.ActivityMainBinding fails resolution

### ISSUE THREAD

**Issue by ihtarlik** [AndroidIDEOfficial/AndroidIDE#1775]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

I can open any project or create a project from the template choices, and everything works fine until I attempt to open MainActivity.java. Then the IDE informs me the "package com.example.myapplication.databinding.ActivityMainBinding does not exist." This occurs even in a fresh template (I have tried several), but also in other projects previously developed under AndroidIDE. I tried removing AndroidIDE entirely and reinstalling from scratch, and got the same result, even using the previous two versions of the app.

### Expected behavior

I expect it to be able to locate the package under development and its XML layouts.

### Version name

Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Google
Device : Pixel5

### Download source

F-Droid

**Comment by ihtarlik** [comment]
![Uploading Screenshot_20240324-165818_Trebuchet.png…]()

**Comment by ihtarlik** [comment]
![Screenshot_20240324-165818_Trebuchet](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/106271293/aa0c919c-3624-411e-ad86-570849a018be)

**Comment by ihtarlik** [comment]
![Screenshot_20240324-174907_Trebuchet](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/106271293/e6870260-bdf4-48a0-8191-02a16a29db3a)

**Comment by MrIkso** [comment]
You must first build project, it autogenerate classes

**Comment by ihtarlik** [comment]
I can build the project just fine, but the IDE still says that class doesn't exist. See below:

![Screenshot_20240327-132604_Trebuchet](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/106271293/2ec442b6-6633-44cd-b9ee-ee98b1af0622)

**Comment by ihtarlik** [comment]
This is from the Basic Project template:
![Screenshot_20240327-132849_Trebuchet](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/106271293/18b6d287-2c47-405c-87d1-66b14f65e772)

**Comment by ihtarlik** [comment]
I upgraded to LineageOS 21 from 20, and the problem appears to have resolved itself. Annoyingly random solution...
