### ISSUE TITLE
not support Android Gradle plugin 8.3

### ISSUE THREAD

**Issue by zjyzip** [AndroidIDEOfficial/AndroidIDE#1776]
lead to "The application module was not found in the project and the application cannot be run." 

And ide log.... 
![Screenshot_20240325-184251.png](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/76038670/f08e2779-2e63-46e5-b68c-cb59d7f57655)

**Comment by Rafael2616** [comment]
This is already supported, just update the IDE to the latest version in the GitHub actions tab.

**Comment by zjyzip** [comment]
> This is already supported, just update the IDE to the latest version in the GitHub actions tab.

The latest version is v2.7.1-beta, which does not support the.

**Comment by BanDroid** [comment]
wait for next release, or use the ci build from github actions.

**Comment by zjyzip** [comment]
> wait for next release, or use the ci build from github actions.

Okay, thanks. I found action latest version，Sorry to bother you.
