### ISSUE TITLE
Warning: android.aapt2FromMavenOverride... is experimental

### ISSUE THREAD

**Issue by surajsharma** [AndroidIDEOfficial/AndroidIDE#1786]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

On build i get the warning

`WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.`

pls help suppress or eliminate/understand

### Expected behavior

Should build without warnings

### Version name

Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : 22071219CI

### Download source

GitHub

**Comment by frknkrc44** [comment]
Not a bug. It's a warning because AndroidIDE overrides the aapt2 binary location.

**Comment by surajsharma** [comment]
> Not a bug. It's a warning because AndroidIDE overrides the aapt2 binary location.

can it be fixed/ warning suppressed?

**Comment by BanDroid** [comment]
> can it be fixed/ warning suppressed? 

no, from what i know, aapt2 from official android is not compatible with android.

also, why? the warning only happen in androidide and it wont bother anything else.

**Comment by itsaky** [comment]
Not a bug. The flag is set in order to use custom AAPT2 binary in the build process.
