### ISSUE TITLE
How to download a lower version of java and add it to path?

### ISSUE THREAD

**Issue by Tanzin01** [AndroidIDEOfficial/AndroidIDE#1787]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

Due to  major version 61 and like so error, sometimes it's way easier and less time consuming to download a lower version of java.
Hence my question.

It seems like the repo only has jdk 17 and 21.

[I did downloaded from somewhere but getting this error-
```
[*] Downloading JDK-8 (~70Mb) for aarch64...  🕛This will take some time, so better make a coffee.🕛
[*] Moving JDK to system...
[*] Extracting JDK...
[*] Seting-up %JAVA_HOME%...
[*] Coping Java wrapper scripts to bin...
cp: cannot create regular file '/data/data/com.itsaky.androidide/files/usr/bin/java': Text file busy
```

### Expected behavior

Can use multi jdk

### Version name

Version : v2.7.1-beta (27102)

### Download source

GitHub

**Comment by itsaky** [comment]
Currently, only JDK 17 and **experimental** version of JDK 21 is available for use. We do not have any plans to support older JDK versions.

> Due to major version 61 and like so error,

For such errors, you have to update your Gradle distribution version.
