### ISSUE TITLE
Sync your project to github

### ISSUE THREAD

**Issue by blinlincom** [AndroidIDEOfficial/AndroidIDE#1790]
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

How to synchronize your project with github from time to time

### Use Case

How to synchronize your project with github from time to time

### Benefits

How to synchronize your project with github from time to time

**Comment by itsaky** [comment]
https://giybf.com/
