### ISSUE TITLE
Camera APIs missing

### ISSUE THREAD

**Issue by pavel5750cz** [AndroidIDEOfficial/AndroidIDE#1795]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

Hello. I was following https://developer.android.com/media/camera/camera-deprecated/camera-api#java tutorial to add camera finctionality to app i make and there are some undefined methods. I prefer coding on phone than coding on pc for android. I also had issue with androidx long time ago to add runtime permissions coz there were undefined references. But that does not concern like the Camera API. I am gonna work on diferent part of app and i hope i can add those camera methods later like tutorial says,to have camera functuonality. I also sent a screenshot where itshows some of undefined methods that in tutorial were used to make camera do its things. I also cebsored my own errors at the time(not of camera api) and app name. For its not needed to solve problem.

![InShot_20240430_131416218](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/79662536/bb106d2f-068f-4238-a9c4-9fca5df3d142)

### Expected behavior

Already said it

### Version name

Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A202F

### Download source

F-Droid

**Comment by itsvks19** [comment]
It is not an issue of AndroidIDE. Add the dependency of the API if you want to use any API.

**Comment by BanDroid** [comment]
first of all, why would you censor many things? do you want us to help or doing some kind of mind reading magic to know what you're thinking right now?

second, dont skip tutorials, and i dont know if you're using java or kotlin, but it seems kotlin and you haven't import most of the things that need to be imported.

**Comment by itsaky** [comment]
You need to add the dependency for the APIs you're using, unless those are system APIs. Then add import statements for those APIs.

**Comment by pavel5750cz** [comment]
Thank you. I will try to add the dependency

**Comment by pavel5750cz** [comment]
Oohh i see its for camera2.  Sorry a lot for this. Ima coming back to coding. U can removethis post if u want
