### ISSUE TITLE
第一次初始化项目时失败

### ISSUE THREAD

**Issue by Hnphqs** [AndroidIDEOfficial/AndroidIDE#1796]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [x] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

首次使用，创建项目，无论是任何项目，初始化项目时都会出现错误

### Expected behavior

1. 打开VPN
2. 打开AndroidIDE
3. 授权AndroidIDE所要求的权限
4. 使用自动安装AndroidIDE要求的openJDK-21和SDK33
5. 新建任意项目
6. 提示初始化中
7. 提示初始化失败
![Screenshot_20240501_211828](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/119466205/a62eb26a-c2dc-4a1e-b39b-783a65a3c650)

### Version name

v2.7.1-beta

### Download source

GitHub

### Relevant log output

```bash
Starting build...

FAILURE: Build failed with an exception.

* What went wrong:
Could not open cp_init generic class cache for initialization script '/data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle' (/data/data/com.itsaky.androidide/files/home/.gradle/caches/8.1.1/scripts/6qdjkb6rq0cppo2sendc74wks).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 42s
```

**Comment by Hnphqs** [comment]
经过尝试，更换jdk-17后就解决了。后搜索到AndroidStudio中有类似问题，在导入旧项目时会出现，但是我在AndroidIDE中是新建项目而不是打开项目，所以肯定在哪里还有问题。在这个问题解决前，如果有其它人使用jdk-21时遇到了跟我一样的问题，请跟换jdk-17试试

**Comment by itsaky** [comment]
Please use English for communicating with others in this repository. Not everyone understands Chinese.
