### ISSUE TITLE
[Feature]: Kotlin Code Helper

### ISSUE THREAD

**Issue by dev-Maghraby** [AndroidIDEOfficial/AndroidIDE#1798]
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

Kotlin code suggestions and auto complete.

### Use Case

null

### Benefits

It improves user's coding productivity levels.

**Comment by mohammad-ayan-008** [comment]
It's under development it will take time

**Comment by itsaky** [comment]
Duplicate of #211
