### ISSUE TITLE
Активность

### ISSUE THREAD

**Issue by asalphotostudio** [AndroidIDEOfficial/AndroidIDE#1810]
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

Можно было создать функцию чтобы можно было создать вторую активность на языке котлин

### Use Case

Если программист не знает языка джава

### Benefits

Неудобно работать только с джава

**Comment by itsaky** [comment]
Kotlin language support is not available as of now (#211).
