### ISSUE TITLE
The issue of project prompt building successfully but unable to compile

### ISSUE THREAD

**Issue by yuwaixingtian** [AndroidIDEOfficial/AndroidIDE#1811]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

The build output when initializing the project appears to be fine：
`Starting build...

> Configure project :app
Adding LogSender dependency (version '2.7.1-beta') to variant 'freeDebug' of project ':app'
Fetch 'IdeaProject' model completed in 12592ms
Fetch 'BasicAndroidProject' model completed in 647ms
Fetch 'AndroidProject' model completed in 124ms
 2 build variants found for project ':app': [freeDebug, freeRelease]
 Selected build variant 'freeDebug' for project ':app'
Fetch 'VariantDependencies' model completed in 1850ms
Fetch 'BasicAndroidProject' model completed in 1ms
Fetch 'AndroidProject' model completed in 17ms
 2 build variants found for project ':library-base': [debug, release]
 Selected build variant 'debug' for project ':library-base'
Fetch 'VariantDependencies' model completed in 262ms
Fetch 'BasicAndroidProject' model completed in 2ms
Fetch 'AndroidProject' model completed in 15ms
 2 build variants found for project ':library-picture': [debug, release]
 Selected build variant 'debug' for project ':library-picture'
Fetch 'VariantDependencies' model completed in 178ms

CONFIGURE SUCCESSFUL in 20s
`

But during compilation, "Application module not found in the project, unable to run the application" will appear.

The project compiled completely normally in version 2.6.1-bate, but the issue of not being able to compile after downloading the latest version of 2.7.1-bate is currently unknown for some reason.

Finally, if you stay in the background of your phone for a long time in the "IDE log" function, clicking the clear output log button after returning will suddenly crash.

### Expected behavior

EditorActivity            I   Connected to Gradle build service 
ToolingServerRunner       I   Starting tooling API server... 
EditorActivity            D   No variant selection information available. Default build variants will be selected. 
EditorActivity            D   Is project initialized: false 
EditorActivity            D   Sending init request to tooling server.. 
EditorActivity            D   onBuildStatusChanged: isInitializing: true, isBuildInProgress: false 
ToolingApiServer          D   ToolingApiMain             Server started. Will run until shutdown message is received...  
ToolingApiServer          D   ToolingApiMain             Running on Java version:  17-internal  
ToolingApiServer          D   ToolingApiServerImpl       Got initialize request  InitializeProjectParams(directory=/storage/emulated/0/AndroidIDEProjects/NewOrangeWebProject/OrangeWeb3, gradleDistribution=GradleDistributionParams(type=GRADLE_WRAPPER, value=), androidParams=AndroidInitializationParams(variantSelections={}))  
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiErrorStream     E   SLF4J: No SLF4J providers were found. 
ToolingApiErrorStream     E   SLF4J: Defaulting to no-operation (NOP) logger implementation 
ToolingApiErrorStream     E   SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details. 
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle wrapper for build...  
ToolingApiServer          D   StopWatch                  Connector created in 43ms  
ToolingApiServer          D   StopWatch                  Project connection established in 13ms  
EditorActivity            D   onBuildStatusChanged: isInitializing: true, isBuildInProgress: true 
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2, -Pandroidide.logsender.isEnabled=true, --scan, --warning-mode, all, --offline]  
ToolingApiServer          W   ProjectReader              Starting build. See build output for more details...  
ToolingApiServer          D   ProjectReader              Build action executed. Result:  com.itsaky.androidide.tooling.impl.internal.ProjectImpl@31e3ce3b  
ToolingApiServer          D   StopWatch                  Project read successful in 21262ms  
ToolingApiServer          D   StopWatch                  Connection to project completed in 21324ms  
EditorActivity            D   onBuildStatusChanged: isInitializing: true, isBuildInProgress: false 
ToolingApiErrorStream     E   May 18, 2024 2:48:29 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError 
ToolingApiErrorStream     E   SEVERE: Internal error: org.gradle.tooling.model.UnsupportedMethodException: Unsupported method: AndroidProject.getModelSyncFiles(). 
ToolingApiErrorStream     E   The version of Gradle you connect to does not support that method. 
ToolingApiErrorStream     E   To resolve the problem you can change/upgrade the target version of Gradle you connect to. 
ToolingApiErrorStream     E   Alternatively, you can ignore this exception and read other information from the model. 
ToolingApiErrorStream     E   java.util.concurrent.CompletionException: org.gradle.tooling.model.UnsupportedMethodException: Unsupported method: AndroidProject.getModelSyncFiles(). 
ToolingApiErrorStream     E   The version of Gradle you connect to does not support that method. 
ToolingApiErrorStream     E   To resolve the problem you can change/upgrade the target version of Gradle you connect to. 
ToolingApiErrorStream     E   Alternatively, you can ignore this exception and read other information from the model. 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) 
ToolingApiErrorStream     E   Caused by: org.gradle.tooling.model.UnsupportedMethodException: Unsupported method: AndroidProject.getModelSyncFiles(). 
ToolingApiErrorStream     E   The version of Gradle you connect to does not support that method. 
ToolingApiErrorStream     E   To resolve the problem you can change/upgrade the target version of Gradle you connect to. 
ToolingApiErrorStream     E   Alternatively, you can ignore this exception and read other information from the model. 
ToolingApiErrorStream     E   	at org.gradle.tooling.model.internal.Exceptions.unsupportedMethod(Exceptions.java:33) 
ToolingApiErrorStream     E   	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter$InvocationHandlerImpl.invoke(ProtocolToModelAdapter.java:468) 
ToolingApiErrorStream     E   	at jdk.proxy2/jdk.proxy2.$Proxy32.getModelSyncFiles(Unknown Source) 
ToolingApiErrorStream     E   	at com.itsaky.androidide.tooling.impl.internal.AndroidProjectImpl.getModelSyncFiles$lambda$9(AndroidProjectImpl.kt:168) 
ToolingApiErrorStream     E   	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) 
ToolingApiErrorStream     E   	... 6 more 
ToolingApiErrorStream     E    
FromNativeContext         E   Unable to transform project 
FromNativeContext         E  org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
FromNativeContext         E  	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(Unknown Source:54)
FromNativeContext         E  	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(Unknown Source:26)
FromNativeContext         E  	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(Unknown Source:48)
FromNativeContext         E  	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(Unknown Source:95)
FromNativeContext         E  	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(Unknown Source:7)
FromNativeContext         E  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
FromNativeContext         E  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
FromNativeContext         E  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
FromNativeContext         E  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
FromNativeContext         E  	at java.lang.Thread.run(Thread.java:922)
FromNativeContext         E   Caused by: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
FromNativeContext         E  	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:361)
FromNativeContext         E  	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1923)
FromNativeContext         E  	at com.sun.jna.FromNativeContext.transform(SourceFile:35)
FromNativeContext         E  	at com.sun.jna.FromNativeContext.transform(SourceFile:69)
FromNativeContext         E  	at com.itsaky.androidide.projects.ProjectManagerImpl$setupProject$2$1.invokeSuspend(Unknown Source:116)
FromNativeContext         E  	at com.itsaky.androidide.projects.ProjectManagerImpl$setupProject$2$1.invoke(Unknown Source:12)
FromNativeContext         E  	at kotlin.jdk7.AutoCloseableKt.startUndispatchedOrReturn(Unknown Source:4)
FromNativeContext         E  	at okio.Base64.withContext(Unknown Source:73)
FromNativeContext         E  	at com.itsaky.androidide.projects.ProjectManagerImpl.setupProject(Unknown Source:129)
FromNativeContext         E  	at com.itsaky.androidide.activities.editor.ProjectHandlerActivity$onProjectInitialized$1.invokeSuspend(Unknown Source:43)
FromNativeContext         E  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
FromNativeContext         E  	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
FromNativeContext         E  	at androidx.work.Worker$2.run(Unknown Source:39)
FromNativeContext         E  	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
FromNativeContext         E  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)
FromNativeContext         E  
FromNativeContext         E  
StopWatch                 D   Transform project proxy completed in 341ms 
EditorActivity            W   GradleProject not initialized. Skipping initial setup... 
EditorActivity            D   onBuildStatusChanged: isInitializing: false, isBuildInProgress: false 

### Version name

Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 31
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : vivo
Device : V2049A

### Download source

GitHub

**Comment by itsaky** [comment]
Update your Android Gradle Plugin version.  The minimum supported AGP version is 7.2.0 and the latest supported is 8.4.0.

**Comment by yuwaixingtian** [comment]
Okay, thank you very much. However, currently the project Gradle is in version 8.6 bin and AGP is in version 8.3.2. This combination can be compiled normally in version 2.6.0 beta. I just tried to modify Gradle to 8.4.0, but it still has the same issue of initialization but cannot be compiled

**Comment by yuwaixingtian** [comment]
> Update your Android Gradle Plugin version. The minimum supported AGP version is 7.2.0 and the latest supported is 8.4.0.

Okay, thank you very much. However, currently the project Gradle is in version 8.6 bin and AGP is in version 8.3.2. This combination can be compiled normally in version 2.6.0 beta. I just tried to modify Gradle to 8.4.0, but it still has the same issue of initialization but cannot be compiled
