### ISSUE TITLE
Issue: AutoComplete Window Pops Up on Keyboard and Auto-Selects Unwanted Suggestions

### ISSUE THREAD

**Issue by sb-codz** [AndroidIDEOfficial/AndroidIDE#1812]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Description
While typing, the AutoComplete window unexpectedly pops up over the keyboard, causing unintentional selection of autocomplete suggestions. This behavior disrupts the typing process and leads to incorrect code or text entries.

### Steps to Reproduce
1. Open the application on an Android device.
2. Navigate to a text input field where AutoComplete is enabled.
3. Start typing to trigger the AutoComplete suggestions.
4. Observe the behavior of the AutoComplete window as it pops up on the keyboard.
### Actual Behavior
- The AutoComplete window pops up over the keyboard, obscuring visibility and causing unintentional selections from the list.
- The AutoComplete window sometimes selects a suggestion automatically without user intention, leading to incorrect text or code entries.
- 
![IMG_20240519_031349](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/6895597/39640955-ad0f-40bb-8e7b-877b8f5f6cba)
https://github.com/AndroidIDEOfficial/AndroidIDE/assets/6895597/91d16986-7645-4eeb-b017-2b1262ffbb31

### Expected behavior

- The AutoComplete window should appear above the keyboard, allowing users to see and select suggestions without unintentional selections.
- Users should have full control over selecting suggestions, without the AutoComplete window automatically selecting an item from the list.
- 

### Version name

Version : v2.7.1-beta (27102)
CI Build : true
Branch : dev
Commit : 971a5dc12
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 28
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : Redmi6Pro

### Download source

GitHub

**Comment by itsaky** [comment]
Fixed in cfc0aed74e6f273bbfd69908e8a562086dcb9ab4.
