### ISSUE TITLE
Package Corruption Issue with assembleRelease in AndroidIDE.

### ISSUE THREAD

**Issue by itsakc-me** [AndroidIDEOfficial/AndroidIDE#1827]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

So, here's the deal - when we try to make apps on AndroidIDE using the assembleRelease task, the package turns out all waste. It's like, totally invalid and won't install. But get this, when we run the same project on Android Studio and run the assembleRelease, bam! The app installs perfectly fine.

This glitch is a major buzzkill as it messes up the whole app-making process and delays our progress to release and develop apps. We gotta fix this bug.

*Files :
  -- Build Output While Syncing.
  [build_output syncing.zip](https://github.com/user-attachments/files/15595463/build_output.syncing.zip)

  -- Build Output While Running.
  [build_output running.zip](https://github.com/user-attachments/files/15595469/build_output.running.zip)

  -- IDE Logs.
  [ide_logs.zip](https://github.com/user-attachments/files/15595476/ide_logs.zip)

  -- Apk Of The Project.
  [app-release-unsigned.zip](https://github.com/user-attachments/files/15595470/app-release-unsigned.zip)

  -- Package Installer Screenshot.
[com.google.android.packageinstaller.zip](https://github.com/user-attachments/files/15595472/com.google.android.packageinstaller.zip)

Also while syncing or running project both AndroidIDE and Android Studio didn't gave any problem on Build Output not even in IDE Logs (AndroidIDE) otherthan the installation failed message.

And when running the project with assembleDebug task it runs perfectly.

### Expected behavior

The behaviour should be normal just like Android Studio and we can install the release instead of failing.

### Version name

Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : 22071219CI

### Download source

GitHub

**Comment by BanDroid** [comment]
could you check the package name of release apk? using mt manager could work or apk editor

**Comment by itsakc-me** [comment]
@BanDroid Yah I check and the package appears perfect but when installing it fails and also I found how to overcome this issue but I still want that AndroidIDE have by default apk signer for assembleRelease that it won't fail again to install.

**Comment by itsakc-me** [comment]
@everyone that have this issue, simply goes to any apk signer app or make a own keystore for signing apk. It will resolve your issue thnks regarding.

**Comment by BanDroid** [comment]
your problem seems about your signing key, unfortunately it was unrelated to androidide in this matter.

**Comment by itsakc-me** [comment]
Yah I see but the fact I didn't use any signing key to sign my apk. So I want a by default signing key that signs apk to install successfully instead of failing.

**Comment by BanDroid** [comment]
about that, we wouldn't provide it, because the build process is handled by gradle and we leave 100% on any configuration to the user for freedom.

**Comment by itsakc-me** [comment]
I know but if user don't provide any signing key then the default key signer will be used. So that the user didn't confuse and but onwards no one will confuse because this issue gave them there answer. So it's choice to add by default or not.
