### ISSUE TITLE
Build variant showing no data and not able to use quick run

### ISSUE THREAD

**Issue by CyberXCoder-6649** [AndroidIDEOfficial/AndroidIDE#1830]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

https://github.com/AndroidIDEOfficial/AndroidIDE/assets/86068846/731b69a5-0ebc-48b5-861d-58433d5167ee

So as you can see it shows no data in Build Variant page and quick run not working but project compiles well with run task menu tried restarting ide and settings.gradle is correct but still not showing variants or running. I am trying to run Termux in AndroidIDE

### Expected behavior

Should show variants and quick run should work as expected

### Version name

Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-G781B

### Download source

GitHub

### Relevant log output

```bash
None
```

**Comment by itsaky** [comment]
@CyberXCoder-6649 Can you share the IDE logs?

**Comment by CyberXCoder-6649** [comment]
> @CyberXCoder-6649 Can you share the IDE logs?

@itsaky There are no IDE logs but let me check once again

**Comment by CyberXCoder-6649** [comment]
> @CyberXCoder-6649 Can you share the IDE logs?

This is after initialization:

[ide_logs.txt](https://github.com/user-attachments/files/15783029/ide_logs.txt)

And this is while quick run clicked:
[ide_logs (1).txt](https://github.com/user-attachments/files/15783061/ide_logs.1.txt)

Nothing is there in logs

**Comment by CyberXCoder-6649** [comment]
@itsaky when will this issue get fixed

**Comment by CyberXCoder-6649** [comment]
@itsaky when will this issue get fixed and what about it shows lot of errors? Even theres are zero error in compilation maybe due to application module not found? or something else? does ide support suggestions and resolutions of classes through different module? if yes then this might be the problem of "No application module found error" else please add this feature too to support suggestions through different modules and resolution of classes through different modules

**Comment by itsaky** [comment]
> when will this issue get fixed

No ETA. I'll work on it when I'm free.

> what about it shows lot of errors? Even theres are zero error in compilation maybe due to application module not found? or something else?

Provide a detailed bug report in a new issue.

> does ide support suggestions and resolutions of classes through different module? if yes then this might be the problem of "No application module found error" else please add this feature too to support suggestions through different modules and resolution of classes through different modules

Yes, the IDE can handle symbol resolution in a multi module project. The "No application module found" error is usually misleading and mostly occurs because the IDE fails to build project models in the Android Runtime. The cause for this is usually shown in the IDE logs.

**Comment by CyberXCoder-6649** [comment]
Ok bro i am waiting for next update regarding this issue and i will create new issue on:
>what about it shows lot of errors? Even theres are zero error in compilation maybe due to application module not found? or something else?

**Comment by ByteSculptor07** [comment]
I have the same issue, first this: 
![Screenshot_AndroidIDE_1](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/144029412/d85a2fe3-d7a5-4cf0-a2cb-fa526e692a60)
Then I closed the project and opened it again, now this:
![Screenshot_AndroidIDE_2](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/144029412/b0004311-617d-4100-9c13-1ea88a1779c9)
I can't even run tasks because it isn't initialized.

**Comment by CyberXCoder-6649** [comment]
> I have the same issue, first this: ![Screenshot_AndroidIDE_1](https://private-user-images.githubusercontent.com/144029412/341975854-d85a2fe3-d7a5-4cf0-a2cb-fa526e692a60.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzYzNDgsIm5iZiI6MTcxOTA3NjA0OCwicGF0aCI6Ii8xNDQwMjk0MTIvMzQxOTc1ODU0LWQ4NWEyZmUzLWQ3YTUtNGNmMC1hMmNiLWZhNTI2ZTY5MmE2MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQxNzA3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDAwZWU4YWVjOTEyZGVmYjdhOGE5NzlkMjcxMDg1MDFiNjY5NTNlZjAxMjVjNGNhMjJiOTgyZTAwMWMzYjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y9ysTO4S9kWPyJ0C9NCziKZey9oCrlL62bKQi98u8pc) Then I closed the project and opened it again, now this: ![Screenshot_AndroidIDE_2](https://private-user-images.githubusercontent.com/144029412/341975853-b0004311-617d-4100-9c13-1ea88a1779c9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzYzNDgsIm5iZiI6MTcxOTA3NjA0OCwicGF0aCI6Ii8xNDQwMjk0MTIvMzQxOTc1ODUzLWIwMDA0MzExLTYxN2QtNDEwMC05YzEzLTFlYTg4YTE3NzljOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQxNzA3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2U1YmMxMDViNjlhODhlNDg2MDQ0MGE5NDE2OThiMzZiYzczMTExMDEwMTBjYmQ3NGM3ZmY3ZmU1OTY0YjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RCNeiOgDSDTixyAS_LxD9tTkyoZvtTX6uqDCgAJSjLw) I can't even run tasks because it isn't initialized.

But that don't work in my case

**Comment by CyberXCoder-6649** [comment]
@itsaky i think the issue is with old gradle so maybe some kind of parsing issue and also one thing more i tried to run termux in first video and now when i try to run this small old project same issue: 
https://github.com/jusss/BluetoothKeyboard.git
So maybe old gradle configuration or maybe with gradle groovy it's not a big project so you can test this above github project in android ide by cloning same issue like termux CONFIGURE SUCCESSFUL and also BUILD SUCCESSFUL by run task but quick run fails and no data is shown in Variant Menu i will do some more experiments on this issue try to figure out exact issue i will update you soon if i got any other hints

**Comment by CyberXCoder-6649** [comment]
BTW which file do AndroidIDE parse for Build Variant i will try updating those file and test it if i am able to see quick run, and Variants
