### ISSUE TITLE
How long to support Kotlin?

### ISSUE THREAD

**Issue by blinlincom** [AndroidIDEOfficial/AndroidIDE#1833]
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

How long to support Kotlin? Now sometimes when it's not convenient to write code on the computer, I can't find my mobile phone because of Kotlin.

### Use Case

Write Kotlin and pack Kotlin.

### Benefits

Let the developer

**Comment by itsaky** [comment]
No ETA.

Relevant: #211
