### ISSUE TITLE
MANIFEST STUCK ON ZERO PROGRESS

### ISSUE THREAD

**Issue by xoureldeen** [AndroidIDEOfficial/AndroidIDE#1834]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

![Screenshot_20240620-033141_AndroidIDE](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/79816069/cad6b112-98c0-4eb7-b5b4-6bca26509ff0)

### Expected behavior

First setup

### Version name

2.7.1-betaMarkdown is supported
https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

### Download source

GitHub

### Relevant log output

```bash
------------------------------------------
Installation directory    : /data/data/com.itsaky.androidide/files/home
SDK version               : 33.0.1
JDK version               : 17
With command line tools   : true
Extra packages            : libcurl jq tar
------------------------------------------
Confirm configuration ([y]es/[n]o): y
Installation directory does not exist. Creating directory...
Update packages...
Hit:1 https://packages.androidide.com/apt/termux-main stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Hit:1 https://packages.androidide.com/apt/termux-main stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing required packages..
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libcurl is already the newest version (8.5.0).
jq is already the newest version (1.7).
tar is already the newest version (1.35).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Packages installed

Downloading manifest file...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:45 --:--:--     0



  0     0    0     0    0     0      0      0 --:--:--  0:04:42 --:--:--     0
```

**Comment by itsaky** [comment]
Check your network connection. The service might be blocked in your country or there may be issues with your ISP. You can try using a VPN.

**Comment by xoureldeen** [comment]
[](url)

> Check your network connection. The service might be blocked in your country or there may be issues with your ISP. You can try using a VPN.

Fixed by vpn but now i got another issue



Run tasks : [:app:assembleDebug]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.
Adding LogSender dependency (version '2.7.1-beta') to variant 'debug' of project ':app'
WARNING: We recommend using a newer Android Gradle plugin to use compileSdk = 34

This Android Gradle plugin (8.0.0) was tested up to compileSdk = 33.

You are strongly encouraged to update your project to use a newer
Android Gradle plugin that has been tested with compileSdk = 34.

If you are already using the latest version of the Android Gradle plugin,
you may need to wait until a newer version with support for compileSdk = 34 is available.

To suppress this warning, add/update
    android.suppressUnsupportedCompileSdk=34
to this project's gradle.properties.
Warning: Dependant package with key emulator not found!

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > Failed to install the following SDK components:
         build-tools;30.0.3 Android SDK Build-Tools 30.0.3
     Install the missing components using the SDK manager in Android Studio.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
