### ISSUE TITLE
[Feature]: Support for AGP 8.5.*

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1837]
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

Add support for Android Gradle Plugin 8.5.*

### Use Case
.

### Benefits
Keep our apps up to date

**Comment by Rafael2616** [comment]
There also seems something new to be implemented in the IDE, as this warning has been appearing since version 8.4.2 in the Android IDE only

This appears both during project startup and in the mentioned task:

```
> Task :app:processDebugResources
Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
```

**Comment by ArtsphereOfficial** [comment]
> There also seems something new to be implemented in the IDE, as this warning has been appearing since version 8.4.2 in the Android IDE only
> 
> This appears both during project startup and in the mentioned task:
> 
> ```
> > Task :app:processDebugResources
> Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
> ```
> 

Did you added 8.5 support in gradle?

**Comment by Wjxfi** [comment]
yeah that's what everyone needs, almost all applications don't compile and my applications remain obsolete

**Comment by arjan-s** [comment]
Same here, I wanted to use this for Gadgetbridge. Too bad it can't be used right now. Does anyone know whether a fix for this issue is planned?

**Comment by Alex3474247** [comment]
Gradle plugin 8.7, the same error as in #1862

**Comment by Wjxfi** [comment]
> Gradle plugin 8.7, the same error as in #1862 

+++

**Comment by itsaky** [comment]
@Rafael2616 The issue has been resolved with commit 308bcb5b0c06371445be4cb8150d5527a78c54e6 and dba601b71ed95dca6fe827193a3a9014931189fa. The tooling API tests [here](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/10115746264/job/27977185899) verify this with AGP 8.5.0 and Gradle 8.7.

Reopen this issue if thats not the case, or if there are any other issues related to AGP 8.5.*.

**Comment by arjan-s** [comment]
@itsaky That's great! Thanks! Do you also plan on making a (beta) release with these fixes?

**Comment by itsaky** [comment]
> @itsaky That's great! Thanks! Do you also plan on making a (beta) release with these fixes?

Currently, no. I've been working on a few things which are incomplete at the moment.
