### ISSUE TITLE
BUG : LAYOUT PREVIEW : Constraint layout not showing correctly.

### ISSUE THREAD

**Issue by PrashantRawatCoder** [AndroidIDEOfficial/AndroidIDE#1858]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

i added a button in a constraint layout and then I used constraint layout bottom, left and right on that button. but when I tried layout preview it was not showing button where it should be:
![Screenshot_2024-07-26-10-22-32-829_com gallery player](https://github.com/user-attachments/assets/714b179c-001d-45af-8c94-4fdb66e90aa6)

![Screenshot_2024-07-26-10-22-44-584_com gallery player](https://github.com/user-attachments/assets/fb87cf54-9181-457e-b676-9701437a0c12)

But when I install the app, The button shows correctly in the app.(Because Android phone itself is Showing it)
![Screenshot_2024-07-26-10-23-32-507_com gallery player](https://github.com/user-attachments/assets/8f67dd80-01b3-4ecb-b576-c4545fcbd8b6)

So layout preview is not correct for constraint layout. Please Fix it.

### Expected behavior

It must have shown button In bottom middle of layout.

### Version name

Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 29
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : Redmi8

### Download source

F-Droid

### Relevant log output

```bash
No log Needed.
```

**Comment by itsaky** [comment]
ConstraintLayout is not supported in UI designer.

**Comment by PrashantRawatCoder** [comment]
Thank you .
Can you please tell us when will you add constraints layout support just asking for curiosity.

**Comment by itsaky** [comment]
> Can you please tell us when will you add constraints layout support just asking for curiosity.

No ETA.
