### ISSUE TITLE
There a AndroidIDE copy in googleplay

### ISSUE THREAD

**Issue by Sunlightsunglasses** [AndroidIDEOfficial/AndroidIDE#1859]
The app was called CodeAssist
This is the image inside the app![Screenshot_20240726_145115_CodeAssist.jpg](https://github.com/user-attachments/assets/cea268c2-db80-4a2c-b945-79561b81ae5e)

![Screenshot_20240726_145119_CodeAssist.jpg](https://github.com/user-attachments/assets/b29327fb-764c-4dba-98f2-5408286d3a32)

**Comment by CyberXCoder-6649** [comment]
Bro it's not a copy Please close this issue

**Comment by itsaky** [comment]
It's not a copy.
