### ISSUE TITLE
Support for Flutter, Python

### ISSUE THREAD

**Issue by tct123** [AndroidIDEOfficial/AndroidIDE#1877]
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

Support for Flutter,
Support for Python(flet, briefcase/toga, kivy/kivymd/buildozer)

### Use Case

I  use python for easy app development.
For flet, flutter is required.

### Benefits

Using python is easier than kotlin.

**Comment by CyberXCoder-6649** [comment]
AndroidIDE is under development and there is no big team to develop this IDE so maybe this feature will not be implemented or maybe it will take a lot of time to implement. And still AndroidIDE is beta and has bugs, crashes, etc and also lack of some important basic features when this is solved maybe devs in feature implement advance features

**Comment by itsaky** [comment]
Flutter/Python will not supported. At least not in the near future.
