### ISSUE TITLE
please add python 

### ISSUE THREAD

**Issue by sg5993** [AndroidIDEOfficial/AndroidIDE#1880]
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

Please add Python 

### Use Case

python 

### Benefits

pythin

**Comment by teixeira0x** [comment]
you can compile python using terminal.

**Comment by sg5993** [comment]
yeah I install python in terminal, but the ide has no python feature

**Comment by Nandini1071** [comment]
Hi, is this issue still there?, If yes then what is the exact requirement?

**Comment by sg5993** [comment]
> Hi, is this issue still there?, If yes then what is the exact requirement?
> 

There is no selection of python in IDE
it is possible to install python with terminal
but it's not appearing on ide

**Comment by Nandini1071** [comment]
so you want to install python through terminal right ?

**Comment by sg5993** [comment]
I already installed python in the terminal.
But I want to load or run python on the IDE

**Comment by Nandini1071** [comment]
Write python on your ide/terminal it will get in to python terminal then you can run your the commands or code in that.
or you can refer this also
https://www.knowledgehut.com/blog/programming/run-python-scripts

**Comment by sg5993** [comment]
I mean I want to choose python when I create a new project
there only java

**Comment by itsaky** [comment]
Python support will not be added.
