### ISSUE TITLE
Button de formatar o código style java 

### ISSUE THREAD

**Issue by JWJIW** [AndroidIDEOfficial/AndroidIDE#1881]
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

Tá faltando um button para formatação de código no java isso seria muito útil 

### Use Case

Seria legal colocar no toolbar para formatação dw código 

### Benefits

Isso ajudaria bastante a trabalhar no código

**Comment by teixeira0x** [comment]
You can format your java code by clicking this button: 
![AndroidIDE](https://github.com/user-attachments/assets/9e21bdd0-0f08-4e50-ada3-1c81ceb5ec5d)
