### ISSUE TITLE
You can format your java code by clicking this button:

### ISSUE THREAD

**Issue by ahmedmsaa** [AndroidIDEOfficial/AndroidIDE#1882]
You can format your java code by clicking this button: 
![AndroidIDE](https://github.com/user-attachments/assets/9e21bdd0-0f08-4e50-ada3-1c81ceb5ec5d)

_Originally posted by @teixeira0x in https://github.com/AndroidIDEOfficial/AndroidIDE/issues/1881#issuecomment-2298585585_

**Comment by CyberXCoder-6649** [comment]
Why new issue? Instead of that you can reply in main issue

**Comment by teixeira0x** [comment]
> Por que nova questão? Em vez disso, você pode responder na questão principal

I didn't understand that either.
