### ISSUE TITLE
bug repport

### ISSUE THREAD

**Issue by JOJO-exm** [AndroidIDEOfficial/AndroidIDE#1883]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

Detail Kesalahan:Jenis Kesalahan: BadTokenException menandakan bahwa token jendela tidak valid.Lokasi Kesalahan: Kesalahan ini muncul saat aplikasi mencoba untuk menampilkan jendela popup, seperti pada PopupWindow, tetapi token yang diperlukan untuk menampilkan jendela tersebut tidak valid.Penyebab Umum:Activity Tidak Aktif: Kesalahan ini sering terjadi jika Anda mencoba menampilkan jendela popup saat aktivitas (activity) yang terkait tidak aktif atau telah dihancurkan.Jendela yang Salah: Menggunakan jendela dengan token yang salah atau tidak terkait dengan aktivitas yang ada.Langkah Pemecahan Masalah:Periksa Aktivitas: Pastikan aktivitas yang terkait dengan jendela popup masih aktif saat Anda mencoba menampilkannya.Validasi Token: Pastikan bahwa token jendela yang Anda gunakan untuk menampilkan popup adalah token yang valid dan terkait dengan aktivitas yang ada.Pengelolaan Lifecycle: Pastikan jendela atau popup dikelola dengan baik sepanjang siklus hidup aktivitas.Untuk solusi lebih lanjut, Anda dapat memeriksa kode tempat kesalahan ini terjadi dan memastikan bahwa semua referensi jendela atau popup terkait dengan aktivitas yang masih aktif dan valid.

### Expected behavior

Popup Dapat Ditampilkan dengan Benar: Saat Anda mencoba menampilkan jendela popup atau dialog, aplikasi harus bisa menampilkannya di layar tanpa kesalahan.Token Jendela Valid: Token jendela yang digunakan untuk menampilkan popup harus valid dan terkait dengan aktivitas yang aktif. Ini memastikan bahwa popup muncul di atas antarmuka pengguna dengan benar.Manajemen Lifecycle yang Tepat: Aplikasi harus mengelola lifecycle aktivitas dengan baik, memastikan bahwa popup hanya ditampilkan saat aktivitas terkait masih aktif dan dalam keadaan valid.Handling Error yang Tepat: Jika ada masalah dengan token atau aktivitas, aplikasi harus menangani kesalahan dengan baik, mungkin dengan menampilkan pesan kesalahan yang informatif kepada pengguna atau menghindari percobaan menampilkan popup jika aktivitas tidak valid.Dengan perilaku ini, pengguna akan mendapatkan pengalaman yang mulus tanpa crash atau error terkait token jendela yang tidak valid.

### Version name

v2.7.1-beta (27102)

### Download source

GitHub

### Relevant log output

```bash
**Stacktrace**:
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
    at android.view.ViewRootImpl.setView(ViewRootImpl.java:1764)
    ...

**Logcat Entries** (contoh):
08-21 15:32:48.123  1234  5678 E AndroidRuntime: FATAL EXCEPTION: main
08-21 15:32:48.123  1234  5678 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
08-21 15:32:48.123  1234  5678 E AndroidRuntime:     at android.view.ViewRootImpl.setView(ViewRootImpl.java:1764)
08-21 15:32:48.123  1234  5678 E AndroidRuntime:     ...

**Build Information**:
- **Version**: v2.7.1-beta (27102)
- **Build Type**: OFFICIAL
- **SDK Version**: 33
- **Device**: Samsung SM-A037F

**Steps to Reproduce**:
1. Open the app and navigate to the editor.
2. Try to open the actions menu.
3. Observe the crash.

**Additional Notes**:
- Ensure the activity is active and valid when showing the popup.
- The issue seems to occur sporadically, possibly linked to lifecycle events.
```

**Comment by itsaky** [comment]
Duplicate of #1752
