### ISSUE TITLE
F-droid version doesn't run in "work profile", it say dont support this user.

### ISSUE THREAD

**Issue by ccchan234** [AndroidIDEOfficial/AndroidIDE#1886]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

As in title, after install latest from F droid in samsung a33 5g latest android OS,
inside work profile. AIDE doesn't allow to run.

G..., my ebanks could run in "work profile", how cant AIDE?

### Expected behavior

shd run

### Version name

latest

### Download source

F-Droid

**Comment by itsaky** [comment]
AndroidIDE can only be installed for the primary user as the packages have hardcoded files directory path (`/data/user/0`). Multi-user support may or may not be added in future.

**Comment by ccchan234** [comment]
hi,

using "work profile" is a security measure.

forcing "personal profile" indeep do not help in security.

thanks
