### ISSUE TITLE
[Question]: Which library do AndroidIDE use for SlidingDrawer(Right side) 

### ISSUE THREAD

**Issue by CyberXCoder-6649** [AndroidIDEOfficial/AndroidIDE#1891]

**Comment by itsaky** [comment]
We do not use a library for this. See [`ContentTranslatingDrawerLayout`](https://github.com/AndroidIDEOfficial/AndroidIDE/blob/dev/core/common/src/main/java/com/itsaky/androidide/ui/ContentTranslatingDrawerLayout.kt)

**Comment by CyberXCoder-6649** [comment]
> We do not use a library for this. See [`ContentTranslatingDrawerLayout`](https://github.com/AndroidIDEOfficial/AndroidIDE/blob/dev/core/common/src/main/java/com/itsaky/androidide/ui/ContentTranslatingDrawerLayout.kt)

Ok
