### ISSUE TITLE
[Question]: Whats going on AndroidIDE Team

### ISSUE THREAD

**Issue by CyberXCoder-6649** [AndroidIDEOfficial/AndroidIDE#1892]
Are you working on New features? or working on stabilizing IDE?

**Comment by itsaky** [comment]
> Are you working on New features? or working on stabilizing IDE?

Mostly on stabilizing the IDE and improving existing features. However, I've not been able to give so much time to the project and there is no one else to work on it so the development is slower than before (too slow, tbh).

If this answers your question, please close this issue.
