### ISSUE TITLE
Visual Ui builder like Sketchware App

### ISSUE THREAD

**Issue by a1x007** [AndroidIDEOfficial/AndroidIDE#1896]
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

The current ui builder is not properly working and is not optimized for smooth user experience. On the other hand if you check Sketchware apps visual ui builder you can see that its very user friendly and smooth drag and drop with so much customization option available. 

### Use Case

Android Ide is the best app for Android current now but its lacking a good ui builder. Also it doesn't alert user about any code error. So i wanna request to the developer to check out the Sketchware visual ui builder and then consider implement similar on Android Ide app.

### Benefits

If you upgrade the current visual builder with Sketchware like visual builder it would benefits all the developer who wanna build a beautiful ui with Android app. Thank you.

**Comment by itsaky** [comment]
The UI Designer will be improved over time. You can file bug reports for issues that you face in the UI designer and we'll look into them.

**Comment by BanDroid** [comment]
what do you mean by "it does not alert user about any code error"?

**Comment by a1x007** [comment]
> what do you mean by "it does not alert user about any code error"?

If i mistake anything inside xml or java/kotlin theres nothing pops up.. if you mistake any code in Android Studio it alert you with red underlines and top right corner an error icon pops up. Thats a good feature and AndroidIde should have also.

**Comment by a1x007** [comment]
> The UI Designer will be improved over time. You can file bug reports for issues that you face in the UI designer and we'll look into them.

On UI editor from left sidebar if i drag a widget and drop in the middle it doesn't adds the widget to code.
And the preview doesn't show the ui properly, like if i use Material TextInputLayout and Edit text it doesn't show the ui properly 
![Uploading Screenshot_2024-09-01-19-32-04-19_9ad8e654efd333b66ab21513aa36e36c.jpg…]()

**Comment by a1x007** [comment]
![Screenshot_2024-09-01-19-32-04-19_9ad8e654efd333b66ab21513aa36e36c](https://github.com/user-attachments/assets/ff2dc2d0-edcc-410b-be80-3ce726bce0d7)

**Comment by a1x007** [comment]
Overall Android Ide is so close to Android Studio i just love it. 😁 Sometimes when I'm outside i can still coding with Android Ide and its really helpful. Thanks for developing this tool for Android.

**Comment by BanDroid** [comment]
> > what do you mean by "it does not alert user about any code error"?
> 
> If i mistake anything inside xml or java/kotlin theres nothing pops up.. if you mistake any code in Android Studio it alert you with red underlines and top right corner an error icon pops up. Thats a good feature and AndroidIde should have also. 

we did have that, but only for xml and java for now

**Comment by a1x007** [comment]
> > > what do you mean by "it does not alert user about any code error"?
> > 
> > 
> > If i mistake anything inside xml or java/kotlin theres nothing pops up.. if you mistake any code in Android Studio it alert you with red underlines and top right corner an error icon pops up. Thats a good feature and AndroidIde should have also.
> 
> we did have that, but only for xml and java for now

Sorry but I don't see any error icons in xml / Java / Kotlin , when i type incomplete code or a wrong code.

**Comment by BanDroid** [comment]
> Sorry but I don't see any error icons in xml / Java / Kotlin , when i type incomplete code or a wrong code. 

you sure?

![Screenshot_2024-09-01-22-33-28-11_9ad8e654efd333b66ab21513aa36e36c.jpg](https://github.com/user-attachments/assets/52039181-2a8b-494b-b2e7-31fd554f4c3c)



i got error notification here, also the editor gives me red lines when i'm writing error code and when the cursor positioned above the red line, it will popup the error message.

**Comment by a1x007** [comment]
![Screenshot_2024-09-01-21-38-48-98_9ad8e654efd333b66ab21513aa36e36c](https://github.com/user-attachments/assets/fce2d079-7787-4c3d-bbf3-1bf67610eb73)
Look i here I'm not getting any red lines...

**Comment by BanDroid** [comment]
enable java diagnostic.

Settings -> Editor -> scroll down to Java section -> Diagnostics enabled.

1. make sure your device is strong enough to run the java language server (atleast device with ram 4gb).
2. make sure you wait until the project syncing finished.

welp. i just said it only available for xml and java, but your image seems that was kotlin file

**Comment by a1x007** [comment]
Thank you I'll try and check if it's working or not.
