### ISSUE TITLE
Static Field Leaks

### ISSUE THREAD

**Issue by Vansh124** [AndroidIDEOfficial/AndroidIDE#190]
# Warning by Lint
![IMG_20220503_161130](https://user-images.githubusercontent.com/100705299/166440180-eb6c5a06-b4d5-4252-ad3c-bebfabb6d13a.jpg)

**After running lint for any project, i experience a warning by it.**

**Comment by Xamp12233** [comment]
You can suppress the warning. If you are confident that it's actually not leaking or holding contexts. It's fine.

**Comment by Vansh124** [comment]
Okay...
