### ISSUE TITLE
[Bug]: Does this not support SD 8gen3?

### ISSUE THREAD

**Issue by cihaneken** [AndroidIDEOfficial/AndroidIDE#1901]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

When I try to install the application, such an error appears.
![IMG_20240905_112710](https://github.com/user-attachments/assets/a7e7ef8a-9377-447a-b17b-2af62d873d7b)

### Expected behavior

İnstallation 

### Version name

27103

### Download source

F-Droid

**Comment by CyberXCoder-6649** [comment]
Which app ABI app you installed? Use cpu z to check kernal arch and then try install app of that specific abi

**Comment by cihaneken** [comment]
Ah, that was the problem. I installed the x86_64 version but I should have installed the v8a version. The device doesn't support 32bit.
