### ISSUE TITLE
Import all not imported classes at once

### ISSUE THREAD

**Issue by JWJIW** [AndroidIDEOfficial/AndroidIDE#239]
![Screenshot_20220627-171226_AIDE](https://user-images.githubusercontent.com/86896232/176027404-0374956d-b6b9-458c-afb4-096616d706dc.jpg)
as you asked here is the problem, I hope you read it and post it, for I can use it soon

**Comment by MrIkso** [comment]
Your issue not have any sense. In screenshot another IDE.

**Comment by BanDroid** [comment]
This is different IDE.

**Comment by itsaky** [comment]
If you read the [message](https://t.me/androidide_discussions/34560) that he sent on Telegram, he's trying to say that AndroidIDE should have a function like this.

**Comment by JWJIW** [comment]
Coreto , e ingênuo

**Comment by JWJIW** [comment]
you will you deploy this soon?

**Comment by Tanya7z** [comment]
'Import all not imported classes at once'really needed feature
