### ISSUE TITLE
Add support for custom color schemes

### ISSUE THREAD

**Issue by QiubyZ** [AndroidIDEOfficial/AndroidIDE#242]
Support For Costum Highlig Syntax

![Screenshot_2022-06-29-03-18-29-655_com itsaky androidide](https://user-images.githubusercontent.com/41333888/176267165-82656195-05ad-4785-b716-1cb4f72534a6.jpg)

Example
![images - 2022-06-29T031600 294](https://user-images.githubusercontent.com/41333888/176267015-85d8ba87-c2e8-461b-9e19-9828f902573b.jpeg)

**Comment by datechies** [comment]
I really want it too. i don't know when they will implement it. but need it badly because my eyes can find codes easily because everything looks white

**Comment by itsaky** [comment]
The [android-tree-sitter](https://github.com/itsaky/android-tree-sitter) library is in development for this. Once it's usable, it'll be integrated in the editor.

**Comment by datechies** [comment]
> The [android-tree-sitter](https://github.com/itsaky/android-tree-sitter) library is in development for this. Once it's usable, it'll be integrated in the editor.

I hope the feature will be added soon..(but fast please)

**Comment by datechies** [comment]
> The [android-tree-sitter](https://github.com/itsaky/android-tree-sitter) library is in development for this. Once it's usable, it'll be integrated in the editor.

Is <a href="https://github.com/itsaky/android-tree-sitter">android-tree-sitter</a> Library finished development now?

**Comment by itsaky** [comment]
> > The [android-tree-sitter](https://github.com/itsaky/android-tree-sitter) library is in development for this. Once it's usable, it'll be integrated in the editor.
> 
> Is [android-tree-sitter](https://github.com/itsaky/android-tree-sitter) Library finished development now?

Nope, working on it.

**Comment by datechies** [comment]
> > > The [android-tree-sitter](https://github.com/itsaky/android-tree-sitter) library is in development for this. Once it's usable, it'll be integrated in the editor.
> > 
> > 
> > Is [android-tree-sitter](https://github.com/itsaky/android-tree-sitter) Library finished development now?
> 
> Nope, working on it.

Waiting so long ...

**Comment by itsaky** [comment]
There needs to be a basic support from the editor itself. And the [work on it has been started](https://github.com/Rosemoe/sora-editor/commit/902c8181612a720fe34ccc71ce98de97d979996c). It'll be available soon.

**Comment by ranjitsingha** [comment]
Hey! Is there any update related to this.

**Comment by itsaky** [comment]
> Hey! Is there any update related to this.

Sora editor recently added support for tree-sitter. I'll be implemented in the IDE soon.

**Comment by itsaky** [comment]
Support for custom color schemes has been added.
