### ISSUE TITLE
"Cancel build" not working (AndroidIDE)

### ISSUE THREAD

**Issue by assis-tant** [AndroidIDEOfficial/AndroidIDE#250]
AndroidIDE crash report
Manufacture: Xiaomi
Device: Redmi9Prime
App version: 2.1.1-beta
OS: MIUI v12.5
Android: 11

Cancel build button not working.

**Comment by itsaky** [comment]
It takes some time for the build to cancel. That totally depends on the Gradle daemon. But yeah, I'll try to improve it.
