### ISSUE TITLE
Can't use bluetooth keyboard in terminal

### ISSUE THREAD

**Issue by faizol** [AndroidIDEOfficial/AndroidIDE#287]
Hi,
I tried to use KBD Trio 500 bluetooth keyboard with AndroidIDE's terminal in a Samsung tablet, but the terminal would not register any characters typed using the bluetooth keyboard. I can use the keyboard normally though when editing a source file in a project. Is there any setup required to use a bluetooth keyboard with AndroidIDE's terminal?

Tq.

**Comment by itsaky** [comment]
The terminal currently isn't configured to support external keyboards. This will be fixed soon.
