### ISSUE TITLE
[Bug]: The buttons on the Toolbar disappear during the build when I am not on EditorActivity

### ISSUE THREAD

**Issue by AndreyKozhev** [AndroidIDEOfficial/AndroidIDE#387]
### What happened?

The buttons on the Toolbar disappear during the build when I am not on EditorActivity.
# Steps to reproduce:
+ Open the project
+ Go to the IDE settings
+ Wait for the project synchronization to finish
+ Go to EditorActivity
# Screenshots
<p>
<img width="180" src="https://user-images.githubusercontent.com/103951737/185315660-8d5570c8-24e9-43d3-a798-ad5359a09d51.jpg"/>
<p>

### What's the expected behavior?

The buttons will not disappear.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Has been fixed in the recent commits. If not, let me know.
