### ISSUE TITLE
[Bug]: App doesn't respond.

### ISSUE THREAD

**Issue by ThatMG393** [AndroidIDEOfficial/AndroidIDE#394]
### What happened?

https://user-images.githubusercontent.com/73651803/185730571-e4412838-cbaa-42af-ac7f-7571df0f6b73.mp4

As you can see in the video, Everything doesn't update/respond. This happened to me twice before, I don't know what caused it. But I think It's caused by the Editor Selection Popup.

### What's the expected behavior?

Normal IDE Behavior.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Cannot access the website. Probably blocked in India.

Please try again to attach the file in the comment itself (at least the video link) or provide another way (upload it elsewhere or something).

**Comment by ThatMG393** [comment]
@itsaky I lost the video recording. I can't play the video on [Streamable](streamable.com). I will post in on [Imgur](imgur.com) as soon as possible!

**Comment by ThatMG393** [comment]
@itsaky Here's the video.

https://user-images.githubusercontent.com/73651803/185730571-e4412838-cbaa-42af-ac7f-7571df0f6b73.mp4

**Comment by itsaky** [comment]
Thanks. I'll look into this.

**Comment by frrrrrits** [comment]
i have facing this issue too, many times.

**Comment by ThatMG393** [comment]
@itsaky I think what caused this is because of the keyboard. When the keyboard suddenly lags. It does that

**Comment by itsaky** [comment]
Okay. Thanks for the info. I'll fix it soon. I'm currently working on something else.
