### ISSUE TITLE
[Bug]: XML file autocompletion does not work

### ISSUE THREAD

**Issue by MatheusTGamerPro** [AndroidIDEOfficial/AndroidIDE#399]
### What happened?

Basically, I noticed that all recent AndroidIDE Builds, XML file autocompletion is not showing, just like in the video below:

https://user-images.githubusercontent.com/89700288/185805455-e6a23f85-9d46-4090-8008-f1ee81a08731.mp4

### What's the expected behavior?

In the version that was released in Beta in releases, autocompletion is partially working, but in recent builds it is not.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
XmlCodeFormatProvider     E   Failed to format code. 
XmlCodeFormatProvider     E  org.xml.sax.SAXParseException: Unexpected token (position:TEXT >@107:17 in java.io.StringReader@abbd074) 
XmlCodeFormatProvider     E  	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:147)
XmlCodeFormatProvider     E  	at com.android.utils.XmlUtils.parseDocument(XmlUtils.java:457)
XmlCodeFormatProvider     E  	at com.itsaky.androidide.lsp.xml.providers.CodeFormatProvider.format(CodeFormatProvider.java:22)
XmlCodeFormatProvider     E  	at com.itsaky.androidide.lsp.xml.XMLLanguageServer.formatCode(XMLLanguageServer.java:156)
XmlCodeFormatProvider     E  	at com.itsaky.androidide.language.LSPFormatter.doFormat(LSPFormatter.kt:61)
XmlCodeFormatProvider     E  	at com.itsaky.androidide.language.LSPFormatter.doFormat$default(LSPFormatter.kt:52)
XmlCodeFormatProvider     E  	at com.itsaky.androidide.language.LSPFormatter.formatAsync(LSPFormatter.kt:41)
XmlCodeFormatProvider     E  	at io.github.rosemoe.sora.lang.format.AsyncFormatter$FormattingThread.run(AsyncFormatter.java:178)
XmlCodeFormatProvider     E  
XmlCodeFormatProvider     E  
XmlCodeFormatProvider     E   Failed to format code. 
XmlCodeFormatProvider     E  org.xml.sax.SAXParseException: Unexpected token (position:TEXT >@107:17 in java.io.StringReader@a1b5ced) 
XmlCodeFormatProvider     E  	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:147)
XmlCodeFormatProvider     E  	at com.android.utils.XmlUtils.parseDocument(XmlUtils.java:457)
XmlCodeFormatProvider     E  	at com.itsaky.androidide.lsp.xml.providers.CodeFormatProvider.format(CodeFormatProvider.java:22)
XmlCodeFormatProvider     E  	at com.itsaky.androidide.lsp.xml.XMLLanguageServer.formatCode(XMLLanguageServer.java:156)
XmlCodeFormatProvider     E  	at com.itsaky.androidide.language.LSPFormatter.doFormat(LSPFormatter.kt:61)
XmlCodeFormatProvider     E  	at com.itsaky.androidide.language.LSPFormatter.doFormat$default(LSPFormatter.kt:52)
XmlCodeFormatProvider     E  	at com.itsaky.androidide.language.LSPFormatter.formatAsync(LSPFormatter.kt:41)
XmlCodeFormatProvider     E  	at io.github.rosemoe.sora.lang.format.AsyncFormatter$FormattingThread.run(AsyncFormatter.java:178)
XmlCodeFormatProvider     E  
XmlCodeFormatProvider     E
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MatheusTGamerPro** [comment]
I think it would be good for you to add an option system in the settings, to disable or enable the auto code formatting when you preview the layout. When the XML formatter returns an exception, code completion doesn't come back, not sure that's it.

**Comment by itsaky** [comment]
The XML completions were temporarily disabled. I'm currently working on it. See the `advanced-xml-registry` branch.

>  When the XML formatter returns an exception, code completion doesn't come back, not sure that's it.

I'll replace the formatter later.

**Comment by MatheusTGamerPro** [comment]
> The XML completions were temporarily disabled. I'm currently working on it. See the `advanced-xml-registry` branch.
> 
> > When the XML formatter returns an exception, code completion doesn't come back, not sure that's it.
> 
> I'll replace the formatter later.

I understood
