### ISSUE TITLE
[Bug]: AndroidIDEPlugin causes compilation failure

### ISSUE THREAD

**Issue by ZeroAicy** [AndroidIDEOfficial/AndroidIDE#404]
### What happened?

Compile the source code of androidide-2.1.1-beta using androidide-2.1.1-beta, and the 
`Execution failed for task ':common:initializeIDEProject'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform tooling-api-impl.jar (project :build-tools:tooling-api-impl) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=11, org.gradle.libraryelements=jar, org.gradle.usage=java-api, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for JetifyTransform: /storage/emulated/0/AndroidIDE-2.1.1-beta/build-tools/tooling-api-impl/build/libs/tooling-api-impl.jar.
         > Transform's input file does not exist: /storage/emulated/0/AndroidIDE-2.1.1-beta/build-tools/tooling-api-impl/build/libs/tooling-api-impl.jar`

appears, but from init After deleting com.itsaky.androidide:gradle-plugin:1.0.0 'init.gradle' file , the compilation is normal

### What's the expected behavior?

com.itsaky.androidide:gradle-plugin:1.0.0 changes the execution flow of gradle, which will cause the dependent library to not compile.
It should be like '.gradlew build' command

### What version of AndroidIDE you're using?

v2.1.1

### Relevant log output

```shell
Execution failed for task ':common:initializeIDEProject'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform tooling-api-impl.jar (project :build-tools:tooling-api-impl) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=11, org.gradle.libraryelements=jar, org.gradle.usage=java-api, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for JetifyTransform: /storage/emulated/0/AndroidIDE-2.1.1-beta/build-tools/tooling-api-impl/build/libs/tooling-api-impl.jar.
         > Transform's input file does not exist: /storage/emulated/0/AndroidIDE-2.1.1-beta/build-tools/tooling-api-impl/build/libs/tooling-api-impl.jar.
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
Building with --build-cache option
