### ISSUE TITLE
[Bug]: editor does not load the color scheme.

### ISSUE THREAD

**Issue by MatheusTGamerPro** [AndroidIDEOfficial/AndroidIDE#408]
### What happened?

In some Java files the editor does not use the color schemes, as shown in the image below, but no error log is captured in the application.

![Screenshot_2022-08-24-20-48-38-268_com itsaky androidide](https://user-images.githubusercontent.com/89700288/186543767-b2b0d2c6-23ee-45e5-8140-30a32e579203.jpg)

### What's the expected behavior?

Enabling color schemes.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This is a known issue and will be fixed soon.

https://github.com/itsaky/AndroidIDE/issues/242#issuecomment-1217436899

**Comment by itsaky** [comment]
Should be fixed now.
