### ISSUE TITLE
[Bug]: Non-Android LibGdx Java Files All Errors

### ISSUE THREAD

**Issue by Trasd** [AndroidIDEOfficial/AndroidIDE#441]
### What happened?

All non-android java files in a LibGdx project have every line marked as an error.

To reproduce:

1. Create a new LibGgx project.
2. Build and run the project to verify it was created correctly.
3. Finally, open the GameSuperClass.java file in the "core" directory.

You will see every line in GameSuperClass.java is marked as an error.

If fixing this problem is too much of a hassle (for now) or not high on the priority list, please add a way to turn off the error underlines as it makes coding difficult (to both read and write).

### What's the expected behavior?

Non-error lines (correct) are not marked as an error.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
Everything seems to build and run correctly.  The only hint is in the log: 

Starting build...
 Creating Idea project model... 

> Configure project :core
Project project ':core' does not apply Android's application or library plugin
AndroidIDE's Gradle Plugin will not be applied to this project
 IdeaProject model created... 
 Project MyGravity is not an AndroidProject 
 Fetching Android project model... 
 Building AndroidModule for project: app 
 Fetching 'debug' dependencies 
 Fetching project sync issues... 
 Android project model for project 'app' created in  417  ms 
 Building IdeGradleProject model for project: :core 

CONFIGURE SUCCESSFUL in 1s
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Please provide the IDE Logs as well for these type of issues.

**Comment by Trasd** [comment]
Sure, if you want, but you should be able to reproduce the problem easily.

It's late here, so I will email them tomorrow.

Thanks.

**Comment by Trasd** [comment]
Attached is the requested IDE log file.

The steps to reproduce:
Create a new Libgdx (from AndroidIDE's Libgdx template)
Hit the 'QuickRun' button to verify the integrity of the project
Open the generated GameSuperClass.java file in the 'core' directory
As the attached screenshot demonstrates, every line of code is marked as an 
error.

Troy
On September 17, 2022 10:42:01 PM Akash Yadav ***@***.***> wrote:
>
> Please provide the IDE Logs as well for these type of issues.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


GradleBuildService        I   Showing notification to user... 
EditorActivity            I   Gradle build service has been started... 
GradleBuildService        I   Starting tooling API server... 
ToolingApiServer          D   ToolingApiMain             Server started. Will run until shutdown message is received...  
CachingProject            W   No tasks found in project '' 
CachingProject            D   Empty module data returned by tooling server. Ignoring... 
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiServer          D   ToolingApiServerImpl       Got initialize request  InitializeProjectMessage(directory=/storage/emulated/0/AndroidIDEProjects/LibGdxScrewupp, gradleInstallation=)  
ToolingApiErrorStream     E   SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". 
ToolingApiErrorStream     E   SLF4J: Defaulting to no-operation (NOP) logger implementation 
ToolingApiErrorStream     E   SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details. 
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle wrapper for build...  
ToolingApiServer          D   StopWatch                  Connector created in 115ms  
ToolingApiServer          D   StopWatch                  Project connection established in 52ms  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2, --warning-mode, all]  
ToolingApiServer          W   ProjectReader              Starting build. See build output for more details...  
ToolingApiServer          D   StopWatch                  Project read successful in 42433ms  
ToolingApiServer          D   StopWatch                  Connection to project completed in 42622ms  
AndroidModule             I   Indexing sources and classpaths for project:  :app 
StopWatch                 D   Indexing sources completed in 51ms 
AndroidModule             D   Found 2 source files. 
StopWatch                 D   Indexing classpaths completed in 223ms 
AndroidModule             D   Found 625 classpaths. 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-32/android.jar 
StopWatch                 D   Indexing 1 bootclasspaths completed in 181ms 
..aultApiVersionsRegistry I   Creating API versions table for platform dir: /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-32 
WidgetTableRegistry       I   Creating widget table for platform dir: /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-32 
ResourceTableRegistry     I   Creating resource table for resource directories ***@***.*** 
ResourceTableRegistry     W   Failed to compile /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-32/data/res/values/symbols.xml 
ResourceTableRegistry     W   Failed to compile /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-32/data/res/values/public.xml 
ResourceTableRegistry     I   Creating resource table for resource directories ***@***.*** 
JavaModule                I   Indexing sources and classpaths for project:  :core 
StopWatch                 D   Indexing sources completed in 22ms 
JavaModule                D   Found 1 source files. 
StopWatch                 D   Indexing classpaths completed in 2ms 
JavaModule                D   Found 0 classpaths. 
StopWatch                 D   Indexing sources completed in 57ms 
AndroidModule             D   Found 2 source files. 
StopWatch                 D   Indexing sources completed in 27ms 
JavaModule                D   Found 1 source files. 
ILanguageServerRegistry   D   Dispatching ProjectInitializedEvent to language servers... 
SourceFileManager         I   Creating source file manager instance for module:  AndroidModule: :app 
SourceFileManager         I   Creating source file manager instance for module:  JavaModule: :core 
ValuesTable               I   Took 7 ms to read 3 files in directory: /storage/emulated/0/AndroidIDEProjects/LibGdxScrewupp/app/res/values 
ValuesTableFactory        D   Created value tables for 1 resource directories in 14 ms 
DefaultActionsRegistry    I   Action 'assembleDebug' completed in 14ms 
ToolingApiServer          D   ToolingApiServerImpl       Received request to run tasks.  TaskExecutionMessage(projectPath=:, tasks=[assembleDebug], gradleInstallation=)  
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle wrapper for build...  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2, --warning-mode, all]  
DefaultActionsRegistry    I   Action 'Quick run' completed in 6ms 
ToolingApiServer          D   ToolingApiServerImpl       Received request to run tasks.  TaskExecutionMessage(projectPath=:, tasks=[assembleDebug], gradleInstallation=)  
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle wrapper for build...  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2, --warning-mode, all]  
QuickRunAction            D   Installing APK(s) for variant: debug 
ApkMetadata               D   Output metadata validation succeeded 
ApkMetadata               I   Found apk in metadata:  /storage/emulated/0/AndroidIDEProjects/LibGdxScrewupp/app/build/intermediates/apk_ide_redirect_file/debug/../../../outputs/apk/debug/app-debug.apk 
QuickRunAction            D   Installing APK:  /storage/emulated/0/AndroidIDEProjects/LibGdxScrewupp/app/build/intermediates/apk_ide_redirect_file/debug/../../../outputs/apk/debug/app-debug.apk 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar
