### ISSUE TITLE
[Feature]: Add support for androidx XML suggestions

### ISSUE THREAD

**Issue by abdulmuhd** [AndroidIDEOfficial/AndroidIDE#469]
### Feature description

e.g 
<androidx.recyclerview.widget.RecyclerView

this will not show as suggestion
      android:layout_width="match_parent"

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Didn't get this. Please explain the issue or simply add a screen recording here if possible.

**Comment by MatheusTGamerPro** [comment]
> Didn't get this. Please explain the issue or simply add a screen recording here if possible.

He wants the XML Layout completion, the AndroidX components and the attributes contained in that component appear.

**Comment by abdulmuhd** [comment]
![Screenshot_20220928-063504](https://user-images.githubusercontent.com/57644185/192696103-be862469-2c6d-4249-83fa-1ad28b71a2a2.png)
is not suggesting android:text

**Comment by itsaky** [comment]
If the tag already has the `android:text` attribute, it won't be suggested. Is this the case?

**Comment by abdulmuhd** [comment]
thanks you!
