### ISSUE TITLE
[Bug]: Weird splash screen

### ISSUE THREAD

**Issue by andihasan97** [AndroidIDEOfficial/AndroidIDE#472]
### What happened?

The splash screen gets weird, but on Android 12 and up it looks fine
![Screenshot_20220926_062505](https://user-images.githubusercontent.com/96150715/192170301-fcce32a0-bfa2-4ede-b549-a9af65dfcee7.jpg)

### What's the expected behavior?

Repair 

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Please check this with the [latest debug build](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/3132839279).

**Comment by itsaky** [comment]
Should have been fixed. Reopen if not.
