### ISSUE TITLE
[Bug]: Swipe Left to Open File Tree Broken

### ISSUE THREAD

**Issue by Trasd** [AndroidIDEOfficial/AndroidIDE#495]
### What happened?

Swipe left to open the File Tree no longer works. I didn't want to report it until I read the full Change Log.  Possibly broken with the "Tree view cannot be scrolled horizontally to the left (#340)." fix.

Low priority.

### What's the expected behavior?

Left swiping from right edge used to open the File Tree.  This is what is expected.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
No log output.
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
It is working. You have to swipe from the edge.

**Comment by Trasd** [comment]
I used this all the time.  It is not working on my machine any longer 
(Lenovo Tab P11 Pro (TBJ706F), Qualcomm Snapdragon 730G 2.20 GHz [8 core], 
128 GB Internal Storage, 6 GB RAM, running Android 11).


Troy

**Comment by Trasd** [comment]
After rebootting my device, swipe-to-left worked again.

My apologize....
