### ISSUE TITLE
[Bug]: SearchView is too small

### ISSUE THREAD

**Issue by afraidnemesis** [AndroidIDEOfficial/AndroidIDE#503]
### What happened?

When searching text, searchview is too small so you can't read the whole text you typed in.

### What's the expected behavior?

Should have shown the whole text that you typed in.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Searching in file or whole project? Please attach screenshots for UI issues.

**Comment by deepkrg17** [comment]
Maybe he is searching in the file. It is small.
Searching in project isn't small.
But it's not a bug, it's an improvement.

**Comment by afraidnemesis** [comment]
![Screenshot_20221006-021117_1](https://user-images.githubusercontent.com/115105972/194497246-bf8d328e-5945-4dde-92bd-1df76af6a50e.png)
This is what I meant. I'm using Android 11 Itsaky🥲

**Comment by itsaky** [comment]
Replaced with bottom search bar.
