### ISSUE TITLE
[Feature]: Add Standard Keyboard Combinations

### ISSUE THREAD

**Issue by Trasd** [AndroidIDEOfficial/AndroidIDE#508]
### Feature description

Please add the ability to customize keyboard key combinations and or standard editor keyboard combinations, e.g.:

Ctrl-Home [beginning of file]
Ctrl-End [end of file]
[delete current line]
etc.

Are you using Sora?

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Customisable key bindings will be added in future releases. For now, Rosemoe/sora-editor#267 adds the requested key bindings along with a few more.
