### ISSUE TITLE
[Bug]: pkg install git not working

### ISSUE THREAD

**Issue by injectoriplay** [AndroidIDEOfficial/AndroidIDE#510]
### What happened?

The pkg install git not working 

### What's the expected behavior?

@It didn't install the pkg git

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
Add the terminal output or attach a screenshot.

**Comment by injectoriplay** [comment]
![Screenshot_2022-10-09-05-49-40-642_com itsaky androidide](https://user-images.githubusercontent.com/104558195/194728922-f92197b6-b65b-40cc-871c-1726c3034899.jpg)


pkg install git is error

**Comment by itsvks19** [comment]
Clear your storage.

**Comment by itsvks19** [comment]
And close this issue.

**Comment by itsaky** [comment]
Not an issue with the IDE.
