### ISSUE TITLE
[Feature]: Change Quick Run icon

### ISSUE THREAD

**Issue by afraidnemesis** [AndroidIDEOfficial/AndroidIDE#520]
### Feature description

![Screenshot_20221012-053407](https://user-images.githubusercontent.com/115105972/195202870-773d1360-9557-4b2c-8431-caa57fbe8c92.png)
To avoid confusion about Quick Run and Build. It saves more time and a smooth experience 😅 I really become annoyed clicking the wrong button. Thanks Itsaky.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsvks19** [comment]
This is not good. The first one is good.

**Comment by MrIkso** [comment]
I think change build icon. Current Quick run its good

**Comment by itsaky** [comment]
Replaced with 'Run tasks' action.
