### ISSUE TITLE
[Bug]: Editor color does not load.

### ISSUE THREAD

**Issue by Luren-unlucky** [AndroidIDEOfficial/AndroidIDE#525]
### What happened?

When there are too many lines in the file, the editor will not display colors.

### What's the expected behavior?

Editor display color

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
This is already reported. Check #242 and #408.
It will be fixed soon with tree-sitter library.

**Comment by deepkrg17** [comment]
This is already reported. Check #408 .
It will be fixed soon with tree-sitter library.
