### ISSUE TITLE
Android IDE project support

### ISSUE THREAD

**Issue by stacoder** [AndroidIDEOfficial/AndroidIDE#533]
### Feature description

Is it possible for you to add a feature in Android Ide like in navigation menu where one can support either in cash or where we can voluntarily watch ads.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
I'm glad you want to support the development of AndroidIDE. But the thing is, we can't use any ad networks because of obvious privacy reasons. Every ad network has a lot of trackers.
