### ISSUE TITLE
[Bug]: IDE Crashed on BUILD SUCCESSFUL

### ISSUE THREAD

**Issue by itsvks19** [AndroidIDEOfficial/AndroidIDE#541]
### What happened?

IDE CRASHED

### What's the expected behavior?

The ide crashed when I finished my build.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-F127G
ABI: arm64-v8a
SDK version: 31
App version: 2.1.2-beta_main-53e3176 (212)

 Stacktrace: 
java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.itsaky.androidide/files/home/AppDesigner/app/build/outputs/apk/debug/app-debug.apk
	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:825)
	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:450)
	at com.blankj.utilcode.util.IntentUtils.getInstallAppIntent(IntentUtils.java:78)
	at com.itsaky.androidide.actions.build.AssembleDebugAction.install$lambda$2(AssembleDebugAction.kt:113)
	at com.itsaky.androidide.actions.build.AssembleDebugAction.$r8$lambda$J79aMVx6MM8OWwCP_pONoU6kInM(Unknown Source:0)
	at com.itsaky.androidide.actions.build.AssembleDebugAction$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Duplicate issues

- [X] This issue has not been reported yet.
- [x] I agree to follow this project's Code of Conduct

**Comment by MatheusTGamerPro** [comment]
> ### What happened?
> IDE CRASHED
> 
> ### What's the expected behavior?
> The ide crashed when I finished my build.
> 
> ### What version of AndroidIDE you're using?
> v2.1.2 (debug builds)
> 
> ### Relevant log output
> ```shell
> AndroidIDE crash report
> Manufacturer: samsung
> Device: SM-F127G
> ABI: arm64-v8a
> SDK version: 31
> App version: 2.1.2-beta_main-53e3176 (212)
> 
>  Stacktrace: 
> java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.itsaky.androidide/files/home/AppDesigner/app/build/outputs/apk/debug/app-debug.apk
> 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:825)
> 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:450)
> 	at com.blankj.utilcode.util.IntentUtils.getInstallAppIntent(IntentUtils.java:78)
> 	at com.itsaky.androidide.actions.build.AssembleDebugAction.install$lambda$2(AssembleDebugAction.kt:113)
> 	at com.itsaky.androidide.actions.build.AssembleDebugAction.$r8$lambda$J79aMVx6MM8OWwCP_pONoU6kInM(Unknown Source:0)
> 	at com.itsaky.androidide.actions.build.AssembleDebugAction$$ExternalSyntheticLambda0.run(Unknown Source:6)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:226)
> 	at android.os.Looper.loop(Looper.java:313)
> 	at android.app.ActivityThread.main(ActivityThread.java:8669)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
> ```
> 
> ### Duplicate issues
> * [x]  This issue has not been reported yet.
> * [x]  I agree to follow this project's Code of Conduct
> 
> ### Code of Conduct

Is your project in the Termux root folder in AndroidIDE? maybe this is the reason.

**Comment by itsvks19** [comment]
> > ### What happened?
> > IDE CRASHED
> > ### What's the expected behavior?
> > The ide crashed when I finished my build.
> > ### What version of AndroidIDE you're using?
> > v2.1.2 (debug builds)
> > ### Relevant log output
> > ```shell
> > AndroidIDE crash report
> > Manufacturer: samsung
> > Device: SM-F127G
> > ABI: arm64-v8a
> > SDK version: 31
> > App version: 2.1.2-beta_main-53e3176 (212)
> > 
> >  Stacktrace: 
> > java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.itsaky.androidide/files/home/AppDesigner/app/build/outputs/apk/debug/app-debug.apk
> > 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:825)
> > 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:450)
> > 	at com.blankj.utilcode.util.IntentUtils.getInstallAppIntent(IntentUtils.java:78)
> > 	at com.itsaky.androidide.actions.build.AssembleDebugAction.install$lambda$2(AssembleDebugAction.kt:113)
> > 	at com.itsaky.androidide.actions.build.AssembleDebugAction.$r8$lambda$J79aMVx6MM8OWwCP_pONoU6kInM(Unknown Source:0)
> > 	at com.itsaky.androidide.actions.build.AssembleDebugAction$$ExternalSyntheticLambda0.run(Unknown Source:6)
> > 	at android.os.Handler.handleCallback(Handler.java:938)
> > 	at android.os.Handler.dispatchMessage(Handler.java:99)
> > 	at android.os.Looper.loopOnce(Looper.java:226)
> > 	at android.os.Looper.loop(Looper.java:313)
> > 	at android.app.ActivityThread.main(ActivityThread.java:8669)
> > 	at java.lang.reflect.Method.invoke(Native Method)
> > 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> > 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Duplicate issues
> > 
> > * [x]   This issue has not been reported yet.
> > * [x]   I agree to follow this project's Code of Conduct
> > 
> > ### Code of Conduct
> 
> Is your project in the Termux root folder in AndroidIDE? maybe this is the reason.

AndroidIDE's home directory.

**Comment by itsaky** [comment]
Check is this happens with the latest commit.

**Comment by itsaky** [comment]
Fixed in recent commits.
