### ISSUE TITLE
[Bug]: Sora Editor Crashes

### ISSUE THREAD

**Issue by Kat234567** [AndroidIDEOfficial/AndroidIDE#549]
### What happened?

If there are errors in your code like Red Lines... The app will crash if you scroll it. Duplicate issue I guess but it's been 5 days since this bug existed. 

### What's the expected behavior?

This hasn't happen before. Strange after updates

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
When reporting crashes, you are expected to provide the stacktrace as well.

This is probably duplicate of #537.

**Comment by itsaky** [comment]
No update from author.
