### ISSUE TITLE
[Bug]: Soft Tab feature not working

### ISSUE THREAD

**Issue by 54b1d** [AndroidIDEOfficial/AndroidIDE#562]
### What happened?

Editor preference to use soft tabs not working as expected. Tabs pressed from keyboard (com.gazlaws.codeboard) are not transforming to spaces.

### What's the expected behavior?

Tabs should transform into spaces.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in Rosemoe/sora-editor#281.
