### ISSUE TITLE
Bug: Custom font cannot be disabled

### ISSUE THREAD

**Issue by BanDroid** [AndroidIDEOfficial/AndroidIDE#564]
Unchecking the switch for custom font settings did not make the editor and terminal back using the default font. I already restart androidide after unchecking the option, but the font still used.

One way to disable the custom font is to remove manually font.ttf in $HOME/.androidide/ui/font.ttf

**Comment by MrIkso** [comment]
Bug here
https://github.com/AndroidIDEOfficial/AndroidIDE/blob/bcb9efefd5e887cfffcab892e200c1181de91ce3/common/src/main/java/com/itsaky/androidide/utils/TypefaceUtils.kt#L35

**Comment by deepkrg17** [comment]
There is no bug I think.
The middle check is for checking the file is not empty, the app may crash if empty file is used.

And '&&' is used because if the first check is false it must not go to the second check.
