### ISSUE TITLE
[Bug]: Text colour for selection it's not usable

### ISSUE THREAD

**Issue by MrIkso** [AndroidIDEOfficial/AndroidIDE#567]
### What happened?

![Screenshot_20221030-113645_AndroidIDE](https://user-images.githubusercontent.com/43380144/198872007-5b5d4932-d9cb-467a-9bdd-4a167ce2e579.jpg)

### What's the expected behavior?

Normally text color for selection 

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Is this issue with the 'Expand selection' action?

**Comment by MrIkso** [comment]
> Is this issue with the 'Expand selection' action?

No , it's manually text selected

**Comment by itsaky** [comment]
Oh. Sorry. I didn't read the title properly.
