### ISSUE TITLE
[Bug]: in layout editor it double up on android:

### ISSUE THREAD

**Issue by HiFIi** [AndroidIDEOfficial/AndroidIDE#574]
### What happened?

Whenever I am in the layout editor and type android:back .. and it suggests background, the problem is that it doubles down on android: so it looks like:
android:android:background 

Which of course causes build errors.  I searched through your code to find where it is so I could fix it but it's been too long :/

### What's the expected behavior?

It just needs to input android: once

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatheusTGamerPro** [comment]
@itsaky for that, you could check the lines behind the cursor, and if it contains the keyword ```android:``` just complete it with the attribute name.

**Comment by MatheusTGamerPro** [comment]
@HiFIi and for that you can just write:
```xml
background
```
That automatically on completion the editor itself will add the tag "android:", so whenever you need to use completion, type directly the name of the attribute. It will automatically look like this:

```xml
android:background=""
```

**Comment by HiFIi** [comment]
> @HiFIi and for that you can just write:
> 
> ```
> background
> ```
> 
> That automatically on completion the editor itself will add the tag "android:", so whenever you need to use completion, type directly the name of the attribute. It will automatically look like this:
> 
> ```
> android:background=""
> ```

Thanks dude. That's a suitable workaround for the time being!

**Comment by itsaky** [comment]
The layout editor is being re-written.
