### ISSUE TITLE
[Bug]: Incorrect and delayed auto-completion of code

### ISSUE THREAD

**Issue by MatheusTGamerPro** [AndroidIDEOfficial/AndroidIDE#580]
### What happened?

When you're typing, and you want to see a method, variable, or anything from an object in the editor, auto-completion most of the time is incorrect or "delayed", as in the video below:

https://user-images.githubusercontent.com/89700288/199515820-1a93ca02-7699-4380-a471-f924be4fdad7.mp4

Also, when it contains a lot of functions or methods, the auto-completion gets messed up even more.

I suggest the error is in the cursor, some position is delayed in launching the completion.Unfortunately, no stacktrace or error appears in the application logs.

### What's the expected behavior?

Auto complete according to cursor pointer

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThatMG393** [comment]
Always happens to me

**Comment by MatheusTGamerPro** [comment]
@itsaky in the last released version of AndroidIDE it is completing normally, I will close this issue.

**Comment by Xamp12233** [comment]
> 

No! It's not working. Bug is still there. You have to use it longer to see it not just once.

**Comment by MatheusTGamerPro** [comment]
> > 
> 
> No! It's not working. Bug is still there. You have to use it longer to see it not just once.

Have you tried using the latest version of the Android IDE SDK? because code completion comes from SDK indexing.

**Comment by Xamp12233** [comment]
> > > 
> > 
> > 
> > No! It's not working. Bug is still there. You have to use it longer to see it not just once.
> 
> Have you tried using the latest version of the Android IDE SDK? because code completion comes from SDK indexing.

Yes All the same. I just live with that bug. If the auto completion don't work. You can't close your project because it will freeze. You have to force stop the app. Yeah it sucks. That bug will forever not solve
