### ISSUE TITLE
[Feature]: Add an option to disable warning highlights. 

### ISSUE THREAD

**Issue by itsvks19** [AndroidIDEOfficial/AndroidIDE#583]
### Feature description

Add an option to disable warning highlight when variable is not used.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Added in f2e9eea49c62cc83a87f013827e832b21529fafb.
