### ISSUE TITLE
Pasting Problem with SymbolPairMatch

### ISSUE THREAD

**Issue by deepkrg17** [AndroidIDEOfficial/AndroidIDE#593]
### What happened?

When you paste anything in editor which is started with a SymbolPair matching character,
it inserts only the SymbolPair. 

### What's the expected behavior?

Paste the whole text from Clipboard.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
N/A
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Probably an issue with the editor. Did you check this issue with sora-editor's sample app?

**Comment by deepkrg17** [comment]
Sora-editor demo app doesn't have this issue.

**Comment by itsaky** [comment]
This should be fixed in https://github.com/Rosemoe/sora-editor/commit/f8e83f5d117ad57f9734fa33f444f1e5d292c5dd.
