### ISSUE TITLE
Activity_main.xml: Warning androidx.coordinatorlayout.widget.CoordinatorLayout is not currently supported.

### ISSUE THREAD

**Issue by Pallas1303** [AndroidIDEOfficial/AndroidIDE#604]
### What happened?

In all projects I create, either Java or Koltin unsupported view error occur in "activity_mal.xml".

Screenshot of Error:
![Screenshot_20221110-204916](https://user-images.githubusercontent.com/103946076/201230543-7e7ffb09-b341-4fbb-8811-88001ce05712.png)

Translation of Error:
activity_main.xml
Warning
androidx.coordinatorlayout.widget.CoordinatorLayout is not currently supported.

Get around the error, replaced the code .xml with a genetic code generated by a layout editor application.

### What's the expected behavior?

Correct view of the layout editor.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
It's not an error.
It's just an info - Views from libraries are not supported to see in layout editor.
You can quick run your project and see layout in installed app.
Or you can use layouts from android.widget
