### ISSUE TITLE
[Feature]: A manager for CodeEditor Themes.

### ISSUE THREAD

**Issue by smith8h** [AndroidIDEOfficial/AndroidIDE#606]
### Feature description

So we'd be able to change the colors of the codes as we prefer.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
Why don't you people check once before creating any issue?
It's already discussed in #242 .
