### ISSUE TITLE
[Feature]: Picture selection and viewing

### ISSUE THREAD

**Issue by anthony-china** [AndroidIDEOfficial/AndroidIDE#621]
### Feature description

There is no picture selection, which is very troublesome.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [ ] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
> There is no picture selection

Could you please elaborate?
