### ISSUE TITLE
[Feature]: Add Light Theme

### ISSUE THREAD

**Issue by ZXHHYJ** [AndroidIDEOfficial/AndroidIDE#623]
### Feature description

see title.androidide not light theme.

### What version of AndroidIDE you're using?

v2.1.1

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Light theme may be implemented in future releases (not very soon).
