### ISSUE TITLE
[Bug]: previewing in UI Designer

### ISSUE THREAD

**Issue by Rystars** [AndroidIDEOfficial/AndroidIDE#629]
### What happened?

![Screenshot_2022-11-25-11-29-47-704_com itsaky androidide](https://user-images.githubusercontent.com/96302690/203901843-ebc43210-a2ee-4066-9501-245cdb49f4b0.jpg)

it happens when i add attribute:
**_android:gravity="center"_**

### What's the expected behavior?

I hope it's fixed soon

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
No log output
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
The UI designer is being rewritten. It'll be available soon.
