### ISSUE TITLE
Can you provide me this app in min sdk 21

### ISSUE THREAD

**Issue by kuttahaitu** [AndroidIDEOfficial/AndroidIDE#645]
### Feature description

Hello bro my device is Android 7 so that I'm not able to install this app. Can you provide me this app in min sdk 21.

### What version of AndroidIDE you're using?

v2.1.3

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Sorry, we have no plans to reduce the min SDK to 21.
