### ISSUE TITLE
[Bug]: still cloning repo in background 

### ISSUE THREAD

**Issue by Deenu143** [AndroidIDEOfficial/AndroidIDE#653]
### Bug description

When you cancel cloning repository [cancel] alert dialog dismissed but git clone still processing in background

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This is clearly not a feature request. Use proper issue templates when creating new issues.
