### ISSUE TITLE
[Feature]: Allow to switch application theme

### ISSUE THREAD

**Issue by ThatMG393** [AndroidIDEOfficial/AndroidIDE#668]
### Feature description

Can you please allow us to switch app theme.
The light mode is very bright, and it's bothering me.

Could you implement it something like this:
![20221214_212045](https://user-images.githubusercontent.com/73651803/207606419-65bb7be8-5b57-47da-ba7c-b574bc37d896.jpg)

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rystars** [comment]
I'm waiting for this feature

**Comment by itsaky** [comment]
Added in 5521bb37b85dfb1c13c4df404007f568c6c2cd98.
