### ISSUE TITLE
[Feature]: Select and compile variant

### ISSUE THREAD

**Issue by Zestski** [AndroidIDEOfficial/AndroidIDE#670]
### Feature description

Is it possible to add variant compile support in AndroidIDE? Like sourcesets?

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
At the moment, you could select variant build tasks from the `Run tasks` dialog.

**Comment by Zestski** [comment]
> At the moment, you could select variant build tasks from the `Run tasks` dialog.

I tried to initialize my project but I get the following error:
```Task with name 'compileDebugJavaWithJavac' not found in project ':app'.```

**Comment by Zestski** [comment]
![Screenshot_20221218-073034_AndroidIDE](https://user-images.githubusercontent.com/96800745/208293434-dc66da33-c5be-47ca-8be3-b2f4b9d1004f.jpg)
In case you want to know how is the structure of my project for more information.

**Comment by MrIkso** [comment]
Maybe duplicate #223

**Comment by Zestski** [comment]
> Maybe duplicate #223

Well, yeah. Went unnoticed, closing. Thank you!
