### ISSUE TITLE
Autocode completions/suggestion

### ISSUE THREAD

**Issue by faultydevil23** [AndroidIDEOfficial/AndroidIDE#683]
### What happened?

IDE isn't showing any autocompletion and suggestion of variable.

### What's the expected behavior?

Not showing autocompletion and suggestion

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
> v2.1.3 (debug builds)

What build are you using? The recent commits temporarily disabled code completions for Java. It has been re-enabled.
