### ISSUE TITLE
[Bug]: Sync Project not working

### ISSUE THREAD

**Issue by Xamp12233** [AndroidIDEOfficial/AndroidIDE#685]
### What happened?

Sync project not working on latest action build. 

### What's the expected behavior?

Please fix

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Works perfectly fine for me. Could you tell me what build you're using and how to reproduce this issue?
