### ISSUE TITLE
[Feature]: Support Min SDK 25

### ISSUE THREAD

**Issue by sradityaa** [AndroidIDEOfficial/AndroidIDE#686]
### Feature description

please add installation support for devices min sdk 25 sir.. Thank you

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Duplicate issues

- [x] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Sorry, but this won't happen as the IDE uses Java NIO APIs which are available only for Android API 26+.

Duplicate of #645.
