### ISSUE TITLE
[Bug]: Blocked By Play Protect

### ISSUE THREAD

**Issue by abdelkrimkr** [AndroidIDEOfficial/AndroidIDE#716]
### What happened?

Blocked by Play Protect  

### What's the expected behavior?

MY app name   
Play Protect doesn't recognise this app's developer. Apps from unknown developers can sometimes be unsafe.  

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This is normal behavior for debug and newly created signing keys.

You might want to see [this SO answer](https://stackoverflow.com/a/55744534).
