### ISSUE TITLE
[Feature]: Add Compose Preview Designer

### ISSUE THREAD

**Issue by abdelkrimkr** [AndroidIDEOfficial/AndroidIDE#719]
### Feature description

You can use this android studio source code 
https://android.googlesource.com/platform/tools/adt/idea/+/refs/heads/mirror-goog-studio-main/compose-designer/

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
We do not have any plans to implement Jetpack Compose Preview at the moment. At least, not before Kotlin LSP is implemented.
