### ISSUE TITLE
UI designer remove my xml tag

### ISSUE THREAD

**Issue by ibnuwahyudi86** [AndroidIDEOfficial/AndroidIDE#729]
i have created xml layout with constraintlayout as root, then linear layout. and inside this i place 3 cardview. one of cardview there is an include layout. first i manually create n edit this layout.

yesterday, when androidide 2.1.4 release, i tried ui designer feature. when i open xml layout which i defined above, all my defined layout erased. only remains constrainlayout (root), parent linear layout, and one materialcardview, rest of layout are gone/erased.

**Comment by itsaky** [comment]
Please use issue templates while reporting bugs.

And, can you provide a layout file to reproduce this issue?

**Comment by ibnuwahyudi86** [comment]
Before
![Screenshot_20230107-230202](https://user-images.githubusercontent.com/18376218/211159750-bbb55eb8-2944-4050-bf4f-792b5156d1d1.png)
![Screenshot_20230107-230230](https://user-images.githubusercontent.com/18376218/211159754-9cb84a48-13b8-4498-aff0-12f2fd4a8ffa.png)

After
![Screenshot_20230107-230032](https://user-images.githubusercontent.com/18376218/211159755-26977289-91f4-4d2f-85da-1d1b684545ad.png)

![Screenshot_20230107-230135](https://user-images.githubusercontent.com/18376218/211159756-290826c2-2900-4787-b783-508b49848856.png)
![Screenshot_20230107-230144](https://user-images.githubusercontent.com/18376218/211159757-f2a38a82-ae43-4316-860c-649dd0ba9e92.png)
![Screenshot_20230107-230212](https://user-images.githubusercontent.com/18376218/211159753-252d5025-8366-4b11-8080-dffcbe070a68.png)
