### ISSUE TITLE
[Bug]: The Ui Designer is not working Properly 

### ISSUE THREAD

**Issue by DarkCode462** [AndroidIDEOfficial/AndroidIDE#733]
### What happened?

Hi, i have just downloaded the latest Android ide V : 2.2.0-Beta
An i have. Just created a new Tabbed Activity Project and it was working fine but when i used Layout Design it shows like this 

An am using Version : 2.2.0 - Beta

![Screenshot_2023-01-10-05-00-57-009_com itsaky androidide](https://user-images.githubusercontent.com/67579112/211429724-ffb109b4-2c1c-4ee7-9ccb-be43748a1dfb.jpg)

So what should I do now ?

### What's the expected behavior?

Please Fix it quickly....

### What version of AndroidIDE you're using?

v2.1.4 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Currently, only Android platform views are supported. Support for other views will be added soon.
