### ISSUE TITLE
Offline module

### ISSUE THREAD

**Issue by Arashvscode** [AndroidIDEOfficial/AndroidIDE#736]
### Feature description

Hello, I am an Iranian and I have your program installed, but if I have written it correctly, the Gerdle module cannot be downloaded. I have also tested it with hundreds of VPNs. If you can add the offline Gerdle module feature in the jdk installation section of the terminal, you will be doing a great favor to everyone.

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Duplicate issues

- [x] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
**_We cannot provide maven repositories with AndroidIDE._**

You can try to find maven mirror repositories located in your region (I found [this](https://iranrepo.ir)) then configure Gradle to use those repositories. If that doesn't work, you can try to find and download `.m2` repository archive and then configure Gradle to use that offline repository.

Read [the Gradle docs](https://docs.gradle.org/current/userguide/declaring_repositories.html).
