### ISSUE TITLE
[Bug]: Gradle build fails on ':app:processDebugResources"

### ISSUE THREAD

**Issue by ThatMG393** [AndroidIDEOfficial/AndroidIDE#739]
### What happened?

I bought a new phone and I transferred the project from the old phone to the new phone, in the old phone its building fine, but in the new phone it fails.

New Phone: Android 13 armv8l, armeabi
Old Phone: Android 8 aarch64, armv8-a

I'm using v2.1.4 (Debug build)
(Its not listed)

### What's the expected behavior?

Should build normally

### What version of AndroidIDE you're using?

v2.1.4

### Relevant log output

```shell
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > AAPT2 .androidide Daemon #0: Unexpected error during link, attempting to stop daemon.
     This should not happen under normal circumstances, please file an issue if it does.
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rajdave-dev** [comment]
Use latest AndroidIde, android-sdk and try this `cp $HOME/android-sdk/build-tools/$SDKVERISON/aapt2 $HOME/.androidide/aapt2`
Replace $SDKVERSION to SDK version that you are using like 33.0.0

**Comment by ThatMG393** [comment]
@Rajdave-dev It seems my project is broken when I moved it to the new phone somehow...

It builds fine on new projects tho

**Comment by ThatMG393** [comment]
@Rajdave-dev I fixed the issue, it's because of leakcanary
