### ISSUE TITLE
android ide not Compile my project

### ISSUE THREAD

**Issue by Arashvscode** [AndroidIDEOfficial/AndroidIDE#740]
### What happened?

Hello, I transferred my program which was from sk pro to your program, deleted duplicate classes and extra libraries, downloaded and installed the latest version, thanks to you, Gerdal was also installed for us Iranians, but the program is being compiled.  It freezes and jumps and the compilation process starts from the beginning

### What's the expected behavior?

Well, the expected behavior is that it runs well like sk pro, and I also forgot to say that the initial check before compilation, whether it's a simple project or a professional project, takes between 3 and 9 minutes, can you reduce this time?

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rajdave-dev** [comment]
> Well, the expected behavior is that it runs well like sk pro, and I also forgot to say that the initial check before compilation, whether it's a simple project or a professional project, takes between 3 and 9 minutes, can you reduce this time?
> 

Build time/Compilation time depends on your device.

**Comment by Arashvscode** [comment]
> 
I don't know, maybe you are right, my device went crazy and deleted the program data, I think I need to buy a new Mobayb, thanks for your reply

**Comment by MrIkso** [comment]
> takes between 3 and 9 minutes
If first build it normally... Read more how to optimize build time in android project.

**Comment by Arashvscode** [comment]
> > takes between 3 and 9 minutes
> 
> If first build it normally... Read more how to optimize build time in android project.

My mobile phone is Samsung A10s and it waits for 10 minutes, but the program crashes and the compilation process starts from the beginning, but in Code Assist, this is not the case, it compiles easily.

**Comment by itsaky** [comment]
> but the program crashes and the compilation process starts from the beginning

This information is not enough for us to debug the issue. Please provide the crash logs or maybe a sample project to reproduce this issue.

**Comment by Arashvscode** [comment]
> 

Hello, I just received your message from my notification, I created a new project and ran it, the program froze for 9 minutes and the compilation process was executed again, and this cycle continued until I was thrown out of the program.

**Comment by MrIkso** [comment]
Without logs and information it need close
