### ISSUE TITLE
[Bug]: Not found the command "idesetup" when open the terminal

### ISSUE THREAD

**Issue by 2980077544** [AndroidIDEOfficial/AndroidIDE#745]
### What happened?

![Screenshot_2023-01-14-10-17-56-341_com itsaky androidide](https://user-images.githubusercontent.com/47817223/212446293-c06f9b6d-de6d-4efd-ba42-fdd131af76e8.jpg)

### What's the expected behavior?

Open Terminal on the main interface and Enter `idesetup` and press Enter.It does not work at all.

### What version of AndroidIDE you're using?

v2.2.0

### Relevant log output

```shell
bash: idesetup: command not found
```

### Duplicate issues

- [x] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esalessandrxx** [comment]
if you need to download SDK etc. you should use idesetup -c

**Comment by ThatMG393** [comment]
It automaticaly deletes "idesetup" when you run "idesetup" and it completed with no errors

**Comment by itsaky** [comment]
This is a known issue and will be fixed with the next terminal packages update. Till then, you can manually download and use the script with :
```bash
wget https://github.com/AndroidIDEOfficial/androidide-tools/raw/main/scripts/idesetup -O $SYSROOT/bin/idesetup
```

**Comment by 2980077544** [comment]
> This is a known issue and will be fixed with the next terminal packages update. Till then, you can manually download and use the script with :
> 
> ```shell
> wget https://github.com/AndroidIDEOfficial/androidide-tools/raw/main/scripts/idesetup -O $SYSROOT/bin/idesetup
> ```

Thank you very much!It works.

After this command,should run `chmod a+x $SYSROOT/bin/idesetup`

**Comment by 2980077544** [comment]
> This is a known issue and will be fixed with the next terminal packages update. Till then, you can manually download and use the script with :
> 
> ```shell
> wget https://github.com/AndroidIDEOfficial/androidide-tools/raw/main/scripts/idesetup -O $SYSROOT/bin/idesetup
> ```

Thank you very much!It works.

After this command,should run `chmod a+x $SYSROOT/bin/idesetup`
