### ISSUE TITLE
[Bug]: App Crashes when closing a file

### ISSUE THREAD

**Issue by Xamp12233** [AndroidIDEOfficial/AndroidIDE#747]
### What happened?

The title described it all.

### What's the expected behavior?

App crashes when closing a file.

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
If the IDE crashes, you're expected to provide the crash logs.
