### ISSUE TITLE
[Feature]: Install packages from termux.dev repository.

### ISSUE THREAD

**Issue by themistocles-0** [AndroidIDEOfficial/AndroidIDE#751]
### Feature description

I downloaded a deb from termux repository but the app couldn't install it, add termux.dev repo to the app

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
Impossible, packages from termux.dev has prefix com.termux, but android ide has com.itsaky.androidide
