### ISSUE TITLE
[Feature]: add documentation how to edit editor theme color

### ISSUE THREAD

**Issue by Rystars** [AndroidIDEOfficial/AndroidIDE#753]
### Feature description

make documentation on how to edit editor theme

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
Already available: https://github.com/AndroidIDEOfficial/AndroidIDE/blob/docs/docs/editor/color_schemes.md
It will be soon merged with the main branch.

**Comment by itsaky** [comment]
Merged with 49e159104219fa90c11f42bce3d8770c1cbfe0fa.
