### ISSUE TITLE
[Feature]: Add automatic generated for R.java

### ISSUE THREAD

**Issue by Raxakuy** [AndroidIDEOfficial/AndroidIDE#754]
### Feature description

It automatically generated for R.java inside folder generated

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
What do you mean?
AGP doesn't generates `R.java` anymore.
You can find class files in `R.jar` at `/app/build/intermediates/compile_and_runtime_not_namespaced_r_class_jar/`.

**Comment by Raxakuy** [comment]
I can't find class file R.jar at /app/build/intermediates/compile_and_runtime_not_namespaced_r_class_jar/
You mention. Does my installation is wrong?

**Comment by itsvks19** [comment]
> I can't find class file R.jar at /app/build/intermediates/compile_and_runtime_not_namespaced_r_class_jar/ You mention. Does my installation is wrong?

![Screenshot_20230123_115434_AndroidIDE](https://user-images.githubusercontent.com/102840735/213977597-a794126a-99fe-4a80-931b-4d419d159742.jpg)

**Comment by Raxakuy** [comment]
Seriously, nothing in there. here the screenshot:
![Screenshot_20230123-132754](https://user-images.githubusercontent.com/115254665/213978043-fa948970-ca3c-4477-ab1c-d474211ff74f.png)

**Comment by itsvks19** [comment]
Try to build apk again.

**Comment by Raxakuy** [comment]
It
