### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by JUDE122-MAX** [AndroidIDEOfficial/AndroidIDE#763]
Whenever I build a project the app checks for package updates and this can take a lot of time. How can I disable this. E.g. Task :app:mergeDebugShaders UP-TO-DATE![Screenshot_20230125-211146.png](https://user-images.githubusercontent.com/59203352/214679347-d9e316f5-e3af-4674-8525-3dfd3c5706b5.png)

**Comment by itsaky** [comment]
The build process is handled by the Android Gradle Plugin and not by AndroidIDE.

AFAIK, you cannot disable tasks and you shouldn't in my opinion. Gradle is smart enough to build only what needs to be built.
