### ISSUE TITLE
[Feature]: API 33: Android 13.0 (Tiramisu)

### ISSUE THREAD

**Issue by itsvks19** [AndroidIDEOfficial/AndroidIDE#770]
### Feature description

Add API 33: Android 13.0 (Tiramisu) in project creator screen.

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Added in #777.
