### ISSUE TITLE
[Feature]: JVM Development

### ISSUE THREAD

**Issue by Luannnn1** [AndroidIDEOfficial/AndroidIDE#779]
### Feature description

Could you work on providing support for JVM development (not apps) to work with Maven projects and Gradle in the AndroidIDE? That would be epic.

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
There are no plans to implement this.
