### ISSUE TITLE
Go back to the last edit location and File tab after entering the software

### ISSUE THREAD

**Issue by Tanya7z** [AndroidIDEOfficial/AndroidIDE#790]
### Feature description

**It is inconvenient to exit the software after editing the file and not keep the tab when you open it again:(**

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This feature has been added. Check out the [release notes](https://github.com/AndroidIDEOfficial/AndroidIDE/releases/tag/v2.1.4-beta) for `v2.1.4-beta`.

**Comment by Tanya7z** [comment]
> This feature has been added. Check out the [release notes](https://github.com/AndroidIDEOfficial/AndroidIDE/releases/tag/v2.1.4-beta) for `v2.1.4-beta`.

I mean to return to the previous file, I don't see such a feature.
