### ISSUE TITLE
Progress Bar Loop 

### ISSUE THREAD

**Issue by Siddhesh2377** [AndroidIDEOfficial/AndroidIDE#797]
### What happened?

When the compile finishes the progress bar should be close but continue to go on an it is very confusing, is project is compiling or not so please look at it here is the image 

![Screenshot_2023-02-14-06-46-11-540_com.itsaky.androidide.jpg](https://user-images.githubusercontent.com/67579112/218613464-9e954a21-6a63-4821-8915-75e8ad9731f2.jpg)

### What's the expected behavior?

..

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThatMG393** [comment]
Use the latest build action

**Comment by ThatMG393** [comment]
https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/4207721249

**Comment by MrIkso** [comment]
I think it fixed

**Comment by itsaky** [comment]
The issue is not reproducible.
