### ISSUE TITLE
[Development Bug]: Gradle sync failed, while configuring AndroidIDE project

### ISSUE THREAD

**Issue by Kovalit31** [AndroidIDEOfficial/AndroidIDE#799]
### What happened?

The text blocks was introduced at 15th level of Java programming language. In 13th and 14th that was a preview feature. May be it is Windows build error, but /build-logic/ide/src/main/java/com/itsaky/androidide/plugins/properties/gen/ClassGenerator.java contents a text block in function licenseHeader(), what won't be compiled, because root and build-logic/ide projects configured with java 11, that haven't got text block feature
Please fix it.

### What's the expected behavior?

AndroidIDE\build-logic\ide\src\main\java\com\itsaky\androidide\plugins\properties\gen\ClassGenerator.java:285: error: unclosed string literal
        return """
                 ^

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Relevant log output

```shell
Nothing can be shown.
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
The JDK version requirement to build AndroidIDE was recently updated to JDK 17 (Android Studio Flaming is bundled with JDK 17).

The contribution guidelines will be updated soon.
