### ISSUE TITLE
[Bug]: The APT mirror station cannot be replaced

### ISSUE THREAD

**Issue by PCX-LK** [AndroidIDEOfficial/AndroidIDE#800]
### What happened?

I tried replacing the mirror, but got the error

### What's the expected behavior?

Replace normally like termux

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PCX-LK** [comment]
I first tried editing the source.list file and then 'apt update'

![Screenshot_20230216134418](https://user-images.githubusercontent.com/62936489/219279622-f5abad3d-b125-43db-b4b5-a5055a40d515.jpg)

Then tried termux-change-repo

![Screenshot_20230216134429](https://user-images.githubusercontent.com/62936489/219279781-63daade2-58e1-4a6b-adaf-4390c4e91d3a.jpg)

Finally, try importing the pub key

![Screenshot_20230216134554](https://user-images.githubusercontent.com/62936489/219279864-2f9a4ecd-9e3a-4b38-bb2e-4b6f6840aa22.jpg)

**Comment by itsaky** [comment]
There is only one mirror for AndroidIDE packages at the moment. Also, termux's packages are incompatible with AndroidIDE ([reason](https://github.com/termux/termux-packages/wiki/Build-environment#important-note-about-termux-prefix)). This is why the `termux-change-repo` command was removed from AndroidIDE packages.
