### ISSUE TITLE
Mirrors for the application download.

### ISSUE THREAD

**Issue by themistocles-0** [AndroidIDEOfficial/AndroidIDE#812]
I'm having extremely crappy speeds downloading from github, could you please host the app elsewhere. It could also be uploaded to the telegram group as soon as a new update is up.

**Comment by deepkrg17** [comment]
You can download it from the [website](https://AndroidIDE.com).

**Comment by themistocles-0** [comment]
> You can download it from the [website](https://AndroidIDE.com).

The website's download link redirects such that the download comes from github releases.

**Comment by itsaky** [comment]
The website now stores its own copies of the APKs.

>  It could also be uploaded to the telegram group.

We could consider this in future. But, as of now, there are only two official sources to download AndroidIDE :
- [The AndroidIDE website](https://androidide.com).
- GitHub ([releases](https://github.com/AndroidIDEOfficial/AndroidIDE/releases) or [actions](https://github.com/AndroidIDEOfficial/AndroidIDE/actions)).
