### ISSUE TITLE
[Bug]: Problems with autocomplete

### ISSUE THREAD

**Issue by ghost** [AndroidIDEOfficial/AndroidIDE#823]
### What happened?

Many times when writing a code inside an onClick the autocompletion is lost, this always happens to me.

### What's the expected behavior?

Being able to write my code without losing autocompletion.

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Please try [this](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/4332318663) build and check if the issue still exists or not.
