### ISSUE TITLE
[Feature]: AAB

### ISSUE THREAD

**Issue by StalkerExplorer** [AndroidIDEOfficial/AndroidIDE#824]
### Feature description

Export apk as AAB!

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
From the `Run tasks` dialog (`Options Menu -> Run tasks `), run the `bundle` task to create AAB.

**Comment by StalkerExplorer** [comment]
> From the `Run tasks` dialog (`Options Menu -> Run tasks `), run the `bundle` task to create AAB.

Great! Thanks a lot!
Using folder custom signing key?
Where is this folder?
Or use something else?
_____________________________
Very good AIDE!
