### ISSUE TITLE
[Bug]: Error highlighting xml

### ISSUE THREAD

**Issue by Tanya7z** [AndroidIDEOfficial/AndroidIDE#825]
### What happened?

In xml highlighting, if there is a number in the tag name after the part becomes white
![Screenshot_2023-02-26-17-45-54-083_com itsaky androidide](https://user-images.githubusercontent.com/65802880/221403548-8d001305-828b-429e-9736-68c4bbe45066.png)

### What's the expected behavior?

Should be repaired

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in AndroidIDEOfficial/tree-sitter-xml@7e6c9c2.
