### ISSUE TITLE
Room Database Library Errror

### ISSUE THREAD

**Issue by mohammad-ayan-008** [AndroidIDEOfficial/AndroidIDE#827]
### What happened?

Task :app:compileDebugJavaWithJavac
Failed to load native library:sqlite-3.39.3.0-d2db51cf-974c-4209-b766-2102751cbd0f-libsqlitejdbc.so. osinfo: Linux/armv7
java.lang.UnsatisfiedLinkError: /data/data/com.itsaky.androidide/files/usr/tmp/sqlite-3.39.3.0-d2db51cf-974c-4209-b766-2102751cbd0f-libsqlitejdbc.so: dlopen failed: library "libc.so.6" not found

### What's the expected behavior?

It should run i think its <JDK 17 bug > i found when i was reading a post on the same issue 

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Relevant log output

```shell
Task :app:compileDebugJavaWithJavac
Failed to load native library:sqlite-3.39.3.0-d2db51cf-974c-4209-b766-2102751cbd0f-libsqlitejdbc.so. osinfo: Linux/armv7
java.lang.UnsatisfiedLinkError: /data/data/com.itsaky.androidide/files/usr/tmp/sqlite-3.39.3.0-d2db51cf-974c-4209-b766-2102751cbd0f-libsqlitejdbc.so: dlopen failed: library "libc.so.6" not found
 at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
 at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
 at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
 at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Use sqlite-jdbc `v3.40.1.0` or newer in your projects to fix this issue. If you're using the AndroidX Room library, you might need to override the transitive dependency. [Learn more](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html)
