### ISSUE TITLE
[Bug]: XML: fully qualified tag names are inserted for platform widgets

### ISSUE THREAD

**Issue by Tanya7z** [AndroidIDEOfficial/AndroidIDE#837]
### What happened?

When using Android's default controls, the completion will complete the previous android.widget together

### What's the expected behavior?

fix it

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
What do you mean by `Android default controls`?

**Comment by Tanya7z** [comment]
![Uploading Screenshot_2023-03-04-18-48-49-945_com.itsaky.androidide.png…]()

**Comment by itsaky** [comment]
> ![Uploading Screenshot_2023-03-04-18-48-49-945_com.itsaky.androidide.png…]()

The screenshot did not upload successfully. Please wait for the screenshot to upload properly before your click `Comment`.

**Comment by Tanya7z** [comment]
Sorry, I'm using a machine translation.  That is to say, there is no need to write the built-in View of the previous package name, such as Button and TextView. In this completion, the previous android.widget will be completed together, which is unnecessary, for example: <android.widget. Button
![Uploading Screenshot_2023-03-04-18-48-49-945_com.itsaky.androidide.png…]()

**Comment by Tanya7z** [comment]
![Screenshot_2023-03-04-18-48-49-945_com itsaky androidide](https://user-images.githubusercontent.com/65802880/222938855-7d3f883b-2de5-4035-950d-914a875b1d2c.png)

**Comment by itsaky** [comment]
Okay. I get it now. It'll be fixed soon.
