### ISSUE TITLE
[Feature]: VectorDrawable

### ISSUE THREAD

**Issue by ghost** [AndroidIDEOfficial/AndroidIDE#845]
### Feature description

Will VectorDrawable be supported in a future version?
![Screenshot_20230308-125803_AndroidIDE](https://user-images.githubusercontent.com/126630297/223764435-1fd53c57-da16-47f8-a0b6-f5268cef9b53.png)
![Screenshot_20230308-125811_AndroidIDE](https://user-images.githubusercontent.com/126630297/223764439-db2f068f-394a-4738-8ff2-7827a9ef3d2e.png)
![Screenshot_20230308-125814_MT Manager](https://user-images.githubusercontent.com/126630297/223764442-b9302054-eec8-4290-8bd2-94d49984c5f4.png)

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
It compiled xml file. You must use normal readable file.

**Comment by MrIkso** [comment]
Copy decompiled xml content and save file on AndroidIDE
