### ISSUE TITLE
[Feature]: support of Persian 

### ISSUE THREAD

**Issue by AmirrezaWeb** [AndroidIDEOfficial/AndroidIDE#848]
### Feature description

Hello friends I am an Iranian. I want to help in Persian translation My email is mnko77534@gmail.com or info@amir85.ir My phone is 9809213894227

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
We manage the translations of AndroidIDE through Crowdin. You can check [here](https://crowdin.com/project/androidide).
If you want to contribute, you have to manage the translations well.
You can join the [telegram group](https://t.me/androidide_discussions) for further discussion.
And you should not disclose your phone number like this if not needed.
