### ISSUE TITLE
[Feature]: Add The Gradle Version Chooser

### ISSUE THREAD

**Issue by Andrew-thecoding12** [AndroidIDEOfficial/AndroidIDE#863]
### Feature description

If someone make a new project and select a custom Gradle version it will download the gradle with the version we choosed on

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
You can edit your gradle version in `gradle/wrapper/gradle-wrapper.properties`.
Also you can use Custom Gradle through `Preferences > Build & Run > Custom Gradle installation`.

**Comment by itsaky** [comment]
The Gradle version can be easily changed by editing the `gradle-wrapper.properties` file.
