### ISSUE TITLE
v2.4.0 - Closing the application that is compiled with assembleRelease

### ISSUE THREAD

**Issue by esalessandrxx** [AndroidIDEOfficial/AndroidIDE#865]
### What happened?

Hello, this is not an AndroidIDE bug per se, what happens is that when compiling the app with assembleRelease and having minifyEnabled in build.gradle set to true, the application sends the following error:

javax.net.ssl.SSLHandshakeException: Chain validation failed
03-15 19:10:21.780 22517/22517 System.err_               W  	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
03-15 19:10:21.780 22517/22517 System.err_               W  	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
03-15 19:10:21.780 22517/22517 System.err_               W  	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
03-15 19:10:21.780 22517/22517 System.err_               W  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
03-15 19:10:21.780 22517/22517 System.err_               W  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
03-15 19:10:21.780 22517/22517 System.err_               W  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)

but if minifyEnabled is false everything goes back to normal.

P.S.  The error is even longer and apparently has to do with some certificate when compiling the app on release using minifyEnabled on true

### What's the expected behavior?

compile using minifyEnabled true without it causing my app to close

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
The issue does not originate from AndroidIDE. We can't do anything to fix this from our side. It's probably an issue with your device or its network configuration.
