### ISSUE TITLE
[Bug]: It's causing the app to crash v2.4.0-beta

### ISSUE THREAD

**Issue by rubensfox20** [AndroidIDEOfficial/AndroidIDE#874]
### What happened?

It is causing the app to crash, when I close a java class in the editor tab with large code it closes the app and restarts again

### What's the expected behavior?

I wanted that when I close the class in the editor, that the app does not restart

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
If the app crashes, you are expected to attach the crash log or at least provide a way to reproduce the error (in your case, info about the file).
