### ISSUE TITLE
[Bug]: triplequote ability not coloring correctly

### ISSUE THREAD

**Issue by AlloMoondragon** [AndroidIDEOfficial/AndroidIDE#884]
### What happened?

![Screenshot_20230320-103050_AndroidIDE~2](https://user-images.githubusercontent.com/127817827/226421691-f7ffafd1-b299-4bb8-a261-da4063b5aa4e.jpg)
may have to reach out to whoever does the coloring because it's really something they should fix on their side.  TripleQuote (for exact strings) isn't recognized and mathed correctly coloringwise.  In this example, it should be the center " of the 7 which is differently colored.

### What's the expected behavior?

for colors to be in correct places

and also to sparkle and dragons pop out

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Sorry, I did not understand the issue at first.
