### ISSUE TITLE
[Feature]: Add Support `System.getenv(string)`

### ISSUE THREAD

**Issue by ask9027** [AndroidIDEOfficial/AndroidIDE#892]
### Feature description

i try to build apk in `ANDROIDIDE` using `Quick Run` and export Signing key details in `terminal bash.bashrc`
but key not found when build apk

```bash
release {
	storeFile = file("dev_keystore.jks")
	storePassword System.getenv("SIGNING_STORE_PASSWORD")
        keyAlias System.getenv("SIGNING_KEY_ALIAS")
	keyPassword System.getenv("SIGNING_KEY_PASSWORD")
}
```

```bash

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > SigningConfig "debug" is missing required property "storePassword".

```
![Screenshot_2023-03-22-13-14-35-152-edit_com itsaky androidide](https://user-images.githubusercontent.com/61283438/226834084-03d0eaff-9e21-4c43-8586-f24007fef4ad.jpg)

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
The environment variables set in `bash.bashrc` file are not used in Gradle builds. If you want to provide custom environment variables, put them in the `$SYSROOT/etc/ide-environment.properties` file. The properties defined in this file are used as environment variables in the Gradle builds as well as the Terminal.

**Comment by ask9027** [comment]
i tried to set `env vars` like this.
and also tried to close and reopen ide but still not working
![Screenshot_2023-03-22-18-59-59-277_com.itsaky.androidide.png](https://user-images.githubusercontent.com/61283438/226919889-19e01fb3-dbf2-4c5e-9e24-f69bb4dcf3ea.png)

**Comment by itsaky** [comment]
That's strange because it works fine in my test. Are you sure that the error is same?

>  storeFile = file("dev_keystore.jks")

I'm not sure, but it might be because of the `=` you have used.
