### ISSUE TITLE
[Bug]: NDK example error

### ISSUE THREAD

**Issue by Duilio12** [AndroidIDEOfficial/AndroidIDE#899]
### What happened?

I can't compile the ndk example in the app. I have installed cmake, clang and ninja. Can help me?
![Screenshot_20230324-153307_AndroidIDE](https://user-images.githubusercontent.com/78109034/227646270-53adbd46-ee06-4000-8085-e1ba1c2b1a27.jpg)

### What's the expected behavior?

I think that can compile without errors

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
If you just read the README :
> No official NDK support because we haven't built the NDK for Android.
