### ISSUE TITLE
[Bug]: Does not compile on correct || usage

### ISSUE THREAD

**Issue by AlloMoondragon** [AndroidIDEOfficial/AndroidIDE#901]
### What happened?

how dare the compiler programmers force imperfect code.
![Screenshot_20230324-211816_AndroidIDE~2](https://user-images.githubusercontent.com/127817827/227696063-d1c4e29e-9b13-48ad-9df4-8bf2204700a3.jpg)
does not accept || allowing code to be on one line.
![Screenshot_20230324-211816_AndroidIDE~3](https://user-images.githubusercontent.com/127817827/227696083-f97707c3-c1b1-448b-a779-64848ce39289.jpg)
but does accept having it on two.
![Screenshot_20230324-211826_AndroidIDE~2](https://user-images.githubusercontent.com/127817827/227696098-013ca514-9bcd-465e-9991-4eee6ad25f35.jpg)
unresolved on the single line ~not on the double.

If you cannot fix this, please point me toward how.  Having my code be forcibly imperfect because programmers sucked is very not ok.  It's forcing my code to spam out on multiple lines where it should acceptably reference every class of a certain type in one go.

### What's the expected behavior?

for every object in a || statement to be individually checked instead of only checking singletons and straight failing on ||

literally novice codeable for loop.  and yes i assume it's kotlin compiler issue and not your doing.  so how do we fix it?

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
First of all, mind your language. Follow the [CODE OF CONDUCT](https://github.com/AndroidIDEOfficial/AndroidIDE/blob/dev/CODE_OF_CONDUCT.md).

In you first condition, the `hemany.coren` property can be accessed if and only if :
- `Notaera` and `absa` inherit from the same class (let's say, `Base`)
- The property `coren` is defined in the parent class `Base`.

In your first case, both conditions are not satisfied. That's why the error.

In the second case, you perform the type checks separately. Here, the `coren` property is defined individually in both classes, that's why the code compiles successfully.

I suggest that you [learn the Kotlin fundamentals](https://kotlinlang.org/docs/home.html) first.

**Comment by AlloMoondragon** [comment]
> First of all, mind your language. Follow the [CODE OF CONDUCT](https://github.com/AndroidIDEOfficial/AndroidIDE/blob/dev/CODE_OF_CONDUCT.md).
> 
> In you first condition, the `hemany.coren` property can be accessed if and only if :
> 
> * `Notaera` and `absa` inherit from the same class (let's say, `Base`)
> * The property `coren` is defined in the parent class `Base`.
> 
> In your first case, both conditions are not satisfied. That's why the error.
> 
> In the second case, you perform the type checks separately. Here, the `coren` property is defined individually in both classes, that's why the code compiles successfully.
> 
> I suggest that you [learn the Kotlin fundamentals](https://kotlinlang.org/docs/home.html) first.

i still do not think you can do anything about this really and it's the kotlin compiler that is at issue.  but interestingly i then tried what you said.  I made an open class.  I made a nice little function in it ~an open function.  And inherited my two girls from it.  And nope.  I overrode the function in both of them first and it was still unresolved.  So I commented out the overrides and they both purely used the base inherited function.  Still nope.  does not matter that they both inherit from a base class with a single property.  || straight wrecks stuff.

And, interestingly, that actually means i'm right and you're wrong ~which yes i agree is silly since i for sure totally am noobiest of noob.  The compiler is at fault.

**Comment by itsaky** [comment]
🤦‍♂️

**Comment by BanDroid** [comment]
I have to report your comments and issue, cause it is not a bug and you're not following [CODE OF CONDUCT](https://github.com/AndroidIDEOfficial/AndroidIDE/blob/dev/CODE_OF_CONDUCT.md).
