### ISSUE TITLE
[Bug]: app crash. 

### ISSUE THREAD

**Issue by code-with-prabhat** [AndroidIDEOfficial/AndroidIDE#919]
### What happened?

When clicked yes on exit dialog  app crashed but doen'nt see any crash log may be this because of big process in dialog when clicked yes 

### What's the expected behavior?

When clicked yes on exit dialog  app crashed but doen'nt see any crash log may be this because of big process in dialog when clicked yes 

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Can you provide a way to reproduce the error?
