### ISSUE TITLE
[Bug]: clone repo doesn't work 

### ISSUE THREAD

**Issue by code-with-prabhat** [AndroidIDEOfficial/AndroidIDE#921]
### What happened?

clone repo doesn't work 

### What's the expected behavior?

 clone repo doesn't work 

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
What repository are you trying to clone? What is the error?
