### ISSUE TITLE
Add Material 3 Template in XML and Compose

### ISSUE THREAD

**Issue by MrMegh** [AndroidIDEOfficial/AndroidIDE#922]
### Feature description

Please add the template of material 3 

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Jetpack Compose projects can be built in AndroidIDE (supported by Gradle). However, we do not provide any other support for the same. I don't think including a template for Jetpack Compose is a good idea.

**Comment by MrIkso** [comment]
Jetpack compose template already added

**Comment by itsaky** [comment]
Templates have been updated to use Material 3.
