### ISSUE TITLE
kotlin error 

### ISSUE THREAD

**Issue by Reza478** [AndroidIDEOfficial/AndroidIDE#926]
I use kapt and ksp in my project so I got error in this kps and kapt tasks it works in android studio but in androidIDE it doesn't work.

**Comment by itsaky** [comment]
You are expected to provide the error/log in such cases.

**Comment by Reza478** [comment]
@itsaky yes or if it is the AndroidIDE problem fix that

**Comment by itsaky** [comment]
How do you expect us to fix the issue if we do not know what the error is?

**Comment by Reza478** [comment]
@itsaky me also do not know but it always says that ksp or kapt Failed but I do not have this error in android studio while running the project
