### ISSUE TITLE
[Bug]: Error apk compilation

### ISSUE THREAD

**Issue by mesflit** [AndroidIDEOfficial/AndroidIDE#929]
### What happened?

for example i am cloning project github.com/termux/termux-x11 but when compiling i get error

### What's the expected behavior?

for example i am cloning project github.com/termux/termux-x11 but when compiling i get error

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
What is the error?

**Comment by mesflit** [comment]
> What is the error?

Ide Error

EditorActivity            I   Connected to Gradle build service 
ToolingServerRunner       I   Starting tooling API server... 
ToolingApiServer          D   ToolingApiMain             Server started. Will run until shutdown message is received...  
CachingProject            W   No tasks found in project '' 
CachingProject            D   Empty module data returned by tooling server. Ignoring... 
EditorActivity            D   Is project initialized: false 
EditorActivity            D   Sending init request to tooling server.. 
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiServer          D   ToolingApiServerImpl       Got initialize request  InitializeProjectMessage(directory=/storage/emulated/0/AndroidIDEProjects/termux-x11-master, gradleInstallation=)  
ToolingApiErrorStream     E   SLF4J: No SLF4J providers were found. 
ToolingApiErrorStream     E   SLF4J: Defaulting to no-operation (NOP) logger implementation 
ToolingApiErrorStream     E   SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details. 
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle wrapper for build...  
ToolingApiServer          D   StopWatch                  Connector created in 101ms  
ToolingApiServer          D   StopWatch                  Project connection established in 50ms  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2]  
ToolingApiServer          W   ProjectReader              Starting build. See build output for more details...  
ToolingApiServer          E   ToolingApiServerImpl      
ToolingApiServer          E  java.net.SocketTimeoutException: Read timed out
ToolingApiServer          E  	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
ToolingApiServer          E  	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
ToolingApiServer          E  	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
ToolingApiServer          E  	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
ToolingApiServer          E  	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:461)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:243)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1503)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1474)
ToolingApiServer          E  	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1059)
ToolingApiServer          E  	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
ToolingApiServer          E  	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
ToolingApiServer          E  	at java.base/sun.net.www.MeteredStream.read(MeteredStream.java:141)
ToolingApiServer          E  	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
ToolingApiServer          E  	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3663)
ToolingApiServer          E  	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3656)
ToolingApiServer          E  	at org.gradle.wrapper.Download.downloadInternal(Download.java:115)
ToolingApiServer          E   Caused by: java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-8.0.2-all.zip failed: timeout (10000ms)
ToolingApiServer          E  	at org.gradle.wrapper.Download.downloadInternal(Download.java:131)
ToolingApiServer          E  	at org.gradle.wrapper.Download.download(Download.java:89)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DistributionInstaller$AsyncDownload$1.run(DistributionInstaller.java:182)
ToolingApiServer          E   Caused by: org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-8.0.2-all.zip'.
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution.getToolingImplementationClasspath(DistributionFactory.java:135)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:41)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:44)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:160)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:142)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:61)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:67)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
ToolingApiServer          E  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
ToolingApiServer          E  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
ToolingApiServer          E  	at java.base/java.lang.Thread.run(Thread.java:833)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
ToolingApiServer          E  	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(DefaultBuildActionExecuter.java:67)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.util.ProjectReader.read(ProjectReader.java:107)
ToolingApiServer          E  	at com.itsaky.androidide.tooling.impl.ToolingApiServerImpl.initialize$lambda$0(ToolingApiServerImpl.kt:109)
ToolingApiServer          E  	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
ToolingApiServer          E  	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
ToolingApiServer          E  	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
ToolingApiServer          E  
ToolingApiServer          E   
CachingProject            W   No tasks found in project '' 
CachingProject            D   Empty module data returned by tooling server. Ignoring... 
ILanguageServerRegistry   D   Dispatching ProjectInitializedEvent to language servers... 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar

**Comment by itsaky** [comment]
Seems like an issue with your internet connection. Please check your internet connection and try again.

**Comment by mesflit** [comment]
> Seems like an issue with your internet connection. Please check your internet connection and try again.

I made a very simple webview application and when I press save I get an error.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
   > Resource compilation failed (Failed to compile resource file: /storage/emulated/0/AndroidIDEProjects/MesWeb/app/build/intermediates/incremental/debug/mergeDebugResources/stripped.dir/layout/activity_main.xml: . Cause: com.ctc.wstx.exc.WstxParsingException: Undeclared namespace prefix "android" (for attribute "layout_width")
      at [row,col {unknown-source}]: [7,34]). Check logs for more details.

**Comment by mesflit** [comment]
> Seems like an issue with your internet connection. Please check your internet connection and try again.

but My internet connection good

**Comment by itsaky** [comment]
Unfortunately, we can't do anything about this.
