### ISSUE TITLE
[Feature]: Add this to mainactivity.xml

### ISSUE THREAD

**Issue by mesflit** [AndroidIDEOfficial/AndroidIDE#931]
### Feature description

xmlns:android="http://schemas.android.com/apk/android"

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThatMG393** [comment]
It's already included.
