### ISSUE TITLE
[Bug]: App Crashed

### ISSUE THREAD

**Issue by mesflit** [AndroidIDEOfficial/AndroidIDE#932]
### What happened?

I made a simple webview application, I installed the Apk, but it throws as soon as I open it.

### What's the expected behavior?

I made a simple webview application, I installed the Apk, but it throws as soon as I open it.

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThatMG393** [comment]
It's probably you're issue, have you even tried debugging your application?

**Comment by mesflit** [comment]
> It's probably your issue, have you even tried debugging your application?
> 
> `LogSender.startLogging(this)` That should work, put it in your main starting activity

i don't know how to do this

**Comment by mesflit** [comment]
> > It's probably your issue, have you even tried debugging your application?
> > `LogSender.startLogging(this)` That should work, put it in your main starting activity


> Task :app:compileDebugJavaWithJavac FAILED
/storage/emulated/0/AndroidIDEProjects/MesWeb/app/src/main/java/com/mesflit/mesweb/MainActivity.java:15: error: <identifier> expected
    LogSender.startLogging(this);
                          ^
/storage/emulated/0/AndroidIDEProjects/MesWeb/app/src/main/java/com/mesflit/mesweb/MainActivity.java:15: error: illegal start of type
    LogSender.startLogging(this);
                           ^
2 errors

> Task :app:initializeIDEProject
>>> PROJECT INITIALIZED <<<

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for d

**Comment by itsaky** [comment]
That's an issue with your project, not AndroidIDE.

**Comment by ThatMG393** [comment]
> > > It's probably your issue, have you even tried debugging your application?
> > > `LogSender.startLogging(this)` That should work, put it in your main starting activity
> 
> > Task :app:compileDebugJavaWithJavac FAILED
> > /storage/emulated/0/AndroidIDEProjects/MesWeb/app/src/main/java/com/mesflit/mesweb/MainActivity.java:15: error:  expected
> > LogSender.startLogging(this);
> > ^
> > /storage/emulated/0/AndroidIDEProjects/MesWeb/app/src/main/java/com/mesflit/mesweb/MainActivity.java:15: error: illegal start of type
> > LogSender.startLogging(this);
> > ^
> > 2 errors
> 
> > Task :app:initializeIDEProject
> > > > PROJECT INITIALIZED <<<
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:compileDebugJavaWithJavac'.
> 
> > Compilation failed; see the compiler error output for d

You need to import the `LogSender` class...
