### ISSUE TITLE
[Bug]: The return gesture of the native system will conflict with the software gesture

### ISSUE THREAD

**Issue by LanHuangJG** [AndroidIDEOfficial/AndroidIDE#935]
### What happened?

The return gesture of the native system will conflict with the software gesture

### What's the expected behavior?

The return gesture of the native system will not conflict with the software gesture

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Unfortunately, this is something that we could not fix. Have a look at [this Reddit post](https://www.reddit.com/r/GooglePixel/comments/dq95jm/side_drawer_vs_back_gesture/) for workarounds.

**Comment by LanHuang025** [comment]
that's works ,thank you very much
