### ISSUE TITLE
[Bug]: Project is not initialized

### ISSUE THREAD

**Issue by masfha** [AndroidIDEOfficial/AndroidIDE#946]
### What happened?

Starting build...
 Creating Idea project model...

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration 'classpath'.
> Could not find com.itsaky.androidide:build-info:v2.4.1-beta.internal.1+branch.dev.commit.58bbf4c.timestamp.20230413184236.
  Searched in the following locations:
    - https://repo.maven.apache.org/maven2/com/itsaky/androidide/build-info/v2.4.1-beta.internal.1+branch.dev.commit.58bbf4c.timestamp.20230413184236/build-info-v2.4.1-beta.internal.1+branch.dev.commit.58bbf4c.timestamp.20230413184236.pom
    - https://s01.oss.sonatype.org/content/repositories/snapshots/com/itsaky/androidide/build-info/v2.4.1-beta.internal.1+branch.dev.commit.58bbf4c.timestamp.20230413184236/build-info-v2.4.1-beta.internal.1+branch.dev.commit.58bbf4c.timestamp.20230413184236.pom
  Required by:
      unspecified:unspecified:unspecified > com.itsaky.androidide:gradle-plugin:2.4.1-beta-58bbf4c6f-SNAPSHOT:20230413.184229-1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 1s
![Screenshot_2023-04-14-23-40-05-20_9ad8e654efd333b66ab21513aa36e36c](https://user-images.githubusercontent.com/79098759/232106108-4e7cb7ee-7683-44f5-a770-68bf1f61ebef.jpg)
![Screenshot_2023-04-14-23-41-40-28_9ad8e654efd333b66ab21513aa36e36c](https://user-images.githubusercontent.com/79098759/232106129-9f2a71c3-1a05-437e-a062-9a2da1e0da85.jpg)

### What's the expected behavior?

How fixed this ?

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
Starting build...
 Creating Idea project model...

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration 'classpath'.
> Could not find com.itsaky.androidide:build-info:v2.4.1-beta.internal.1+branch.dev.commit.58bbf4c.timestamp.20230413184236.
  Searched in the following locations:
    - https://repo.maven.apache.org/maven2/com/itsaky/androidide/build-info/v2.4.1-beta.internal.1+branch.dev.commit.58bbf4c.timestamp.20230413184236/build-info-v2.4.1-beta.internal.1+branch.dev.commit.58bbf4c.timestamp.20230413184236.pom
    - https://s01.oss.sonatype.org/content/repositories/snapshots/com/itsaky/androidide/build-info/v2.4.1-beta.internal.1+branch.dev.commit.58bbf4c.timestamp.20230413184236/build-info-v2.4.1-beta.internal.1+branch.dev.commit.58bbf4c.timestamp.20230413184236.pom
  Required by:
      unspecified:unspecified:unspecified > com.itsaky.androidide:gradle-plugin:2.4.1-beta-58bbf4c6f-SNAPSHOT:20230413.184229-1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 1s
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
The issue was fixed in the recent CI builds. Please update to the latest one.
