### ISSUE TITLE
[Bug]: Symbol overlaps when there's a tab(s) before it

### ISSUE THREAD

**Issue by ThatMG393** [AndroidIDEOfficial/AndroidIDE#949]
### What happened?

![Screenshot_20230417_115543_AndroidIDE](https://user-images.githubusercontent.com/73651803/232374565-73037f62-9854-4dd1-bf53-3a0672684ad1.png)

Here's an example:
```java
!Object tst = new Object();
// OR
	.setThis(this);
```

### What's the expected behavior?

Not overlapping

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This should probably be reported to [sora-editor](https://github.com/Rosemoe/sora-editor), not here.
