### ISSUE TITLE
Problems downloading the necessary data when compiling my first project

### ISSUE THREAD

**Issue by HackFoxnew** [AndroidIDEOfficial/AndroidIDE#953]
When I downloaded the jdk and sdk I went to create my first project but when I touched the green arrow to compile I was asked to download or link something according to what I read in the project documentation.

The problem is that just in that part of the download it gives me an error (probably because of my internet connection) but I find it incredible that this download fails so easily unlike how easy it was to download the jdk and sdk respectively.

Anyway I would like a Manual way to download or do what does that because the app directly does not work for me.

**Comment by itsaky** [comment]
It seems like you're having issues with the Gradle build. If you could provide us the exact error that you're facing, it may help us debug the issue.

**Comment by HackFoxnew** [comment]
> It seems like you're having issues with the Gradle build. If you could provide us the exact error that you're facing, it may help us debug the issue.

Let's start over

When you create your first project in the app, the app has to set up a few things before running or compiling the program

Well at that point the download of whatever is downloading the app is failing me inserted image

![Screenshot_20230419-132632.png](https://user-images.githubusercontent.com/100820447/233153791-7b518ff6-aca9-48dc-9644-048b457fd6d6.png)

I am going to assume that the error in the image is due to my internet connection or other reasons. I would like a Manual way to download those files

**Comment by itsaky** [comment]
Gradle is unable to download the required dependency. As you said, this may be due to your internet connection.

If not, check if you have enabled the `--offline` flag in preferences (`IDE Preferences` -> `Build and run` -> `Additional Gradle commands`). If it is enabled, please disable it.

You can enable `--stacktrace` to get the stack trace for the error. `--info` provides additional information about the build.

**Comment by HackFoxnew** [comment]
> Gradle is unable to download the required dependency. As you said, this may be due to your internet connection.
> 
> If not, check if you have enabled the `--offline` flag in preferences (`IDE Preferences` -> `Build and run` -> `Additional Gradle commands`). If it is enabled, please disable it.
> 
> You can enable `--stacktrace` to get the stack trace for the error. `--info` provides additional information about the build.

Yes but isn't there a way to install these dependencies manually, through the terminal or something like that?

And a question these dependencies can not come preinstalled or as a package for the terminal is that install it that way gives me many connection errors.

**Comment by itsaky** [comment]
> Yes but isn't there a way to install these dependencies manually, through the terminal or something like that?

You should probably search about this on the internet. However in my opinion, you should let Gradle handle the downloads.

> And a question these dependencies can not come preinstalled or as a package for the terminal is that install it that way gives me many connection errors.

Nope, there are thousands of artifacts out there, we cannot package (or pre-install) them with AndroidIDE.
