### ISSUE TITLE
[Feature]: why can't we compile non-AndroidIDE projects?

### ISSUE THREAD

**Issue by mesflit** [AndroidIDEOfficial/AndroidIDE#957]
### Feature description

why can't we compile non-AndroidIDE projects?
If we can compile, how do we compile?

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esalessandrxx** [comment]
Hi, what does it mean to compile non-Android projects? I have compiled projects created in Android Studio and vice versa.

**Comment by ThatMG393** [comment]
@esalessandrxx He/She said that he/she cannot compile normal Java projects.

**Comment by mesflit** [comment]
> Hi, what does it mean to compile non-Android projects? I have compiled projects created in Android Studio and vice versa.

What application did you make? can you give an example?
because i tried to make this app and got error. This is not AndroidIDE project

https://github.com/nuclearfog/Shitter

**Comment by esalessandrxx** [comment]
> > Hola, ¿qué significa compilar proyectos que no sean de Android? He compilado proyectos creados en Android Studio y viceversa.
> 
> ¿Qué aplicación hiciste? ¿Puede dar un ejemplo? porque traté de hacer esta aplicación y obtuve un error. Este no es un proyecto AndroidIDE
> 
> [https://github.com/nuclearfog/Mierda](https://github.com/nuclearfog/Shitter)

I use my project, I am developing it in both programs (Android Studio and AndroidIDE) depending on which one I can use at that moment, so far everything is going well, you just have to make sure that the correct dependencies are downloaded. You should also check if the project is not very large, if so it could be that AndroidIDE does not run it.
