### ISSUE TITLE
[Bug]: Apt failed to fetch 

### ISSUE THREAD

**Issue by fireclouu** [AndroidIDEOfficial/AndroidIDE#963]
### What happened?

It fails to fetch openjdk 17 and its  needed packages even after cleaning , upgrading , checking my internet status, or using vpn. It works on my Oreo device but not with Samsung A03 using android 13.

### What's the expected behavior?

Should install needed files to be able to start androidide
![Screenshot_20230428_204200_AndroidIDE](https://user-images.githubusercontent.com/22563129/235151839-e5a41998-532d-443d-87a6-3eb2858f5ef8.jpg)

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Did you try reinstalling the IDE?

**Comment by fireclouu** [comment]
yes i did, it only happens to my galaxy a03 device running android 13 but installs fine on redmi 6a 8.0

**Comment by itsaky** [comment]
Well, I don't think Android 13 is the issue here. I use Android 13 as well. It might be an issue with the storage space. Could you try checking if you have enough free space?

Are you using any custom ROM? If yes, please mention the name and version.

**Comment by fireclouu** [comment]
> Well, I don't think Android 13 is the issue here. I use Android 13 as well. It might be an issue with the storage space. Could you try checking if you have enough free space?
> 
> Are you using any custom ROM? If yes, please mention the name and version.

Im using stock rom. Ill try checking with my storage space then ill update. Thanks!

**Comment by fireclouu** [comment]
weird it does install on another device other than galaxy a03 that also runs on android 13, will do freeing up more space, I think 3gb still not enough

**Comment by itsaky** [comment]
You'll need more to be able to build multiple projects. But for the installation, 3GB is more than enough. I can't figure out the reason for this issue.

**Comment by fireclouu** [comment]
its working now, i freed some space from 3gb up to 4.5gb, i even removed openjdk-17 package on my termux app thinking it clashes on androidide package but unlikely i guess. Thanks.

**Comment by fireclouu** [comment]
I'll just bump these here since I think I found out why device running on Android 13 suffers from issues above

it might be due to **phantom process killer**, after modifying its value, all issues are gone and successfully installed sdks right away!
