### ISSUE TITLE
[Feature]: Requesting permission to use appt2 for sketchware

### ISSUE THREAD

**Issue by moderGamer** [AndroidIDEOfficial/AndroidIDE#981]
### Feature description

@itsaky Hello, how are you? I wanted to ask your permission to add appt2 for sketchware because it is too old for sketchware and I don't want to trust other versions of appt2. I prefer to use your program files because it is trusted and all  Do you allow them to use it?

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
AndroidIDE is licensed under the GNU General Public License version 3 (GPLv3).

The GPLv3 is a copyleft license that grants certain freedoms to users, including the freedom to use, modify, and distribute the software, as long as any derivative works are also licensed under the GPLv3. If you would like to use a portion of our project, you must comply with the terms and conditions of the GPLv3.

As long as you adhere to the license, you are welcome to utilize the code and resources for your own purposes. The license details can be found at https://github.com/AndroidIDEOfficial/AndroidIDE/blob/dev/LICENSE. Please make sure to review and comply with the license terms.

**Comment by moderGamer** [comment]
> 

Thank you, thank you, I am trying to talk to the Sketchware team that your copyright is also reserved
