### ISSUE TITLE
[Bug]: Gradle Build Service Error

### ISSUE THREAD

**Issue by Precious-ab** [AndroidIDEOfficial/AndroidIDE#987]
### What happened?

Whenever It starts building I get an error 

### What's the expected behavior?

It Should Build Normally 

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
-------------------- NOTE --------------------
Gradle Wrapper is not available!
Installing default one. Gradle v7.4 will be downloaded if necessary.
----------------------------------------------
Starting build...
2023-05-23T23:29:43.685+0000 [INFO] [org.gradle.launcher.daemon.server.exec.LogToClient] The client will now receive all logging from the daemon (pid: 15773). The daemon log file: /data/data/com.itsaky.androidide/files/home/.gradle/daemon/7.4.2/daemon-15773.out.log
2023-05-23T23:30:57.147+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.


//It was actually alot longer had to shorten this
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
The logs you provided does not contain any useful information.

**Comment by itsaky** [comment]
> - [ ] I agree to follow this project's Code of Conduct

You must accept the project's Code of Conduct. Your cooperation is essential for fostering a positive and welcoming community. Please read the project's [Code of Conduct](https://github.com/AndroidIDEOfficial/AndroidIDE/blob/dev/CODE_OF_CONDUCT.md) and reopen this issue if you accept it.

**Comment by Precious-ab** [comment]
Oh sorry about that the issue has been resolved, but I'm new to this and im having problems using the Gradle(I don't know how to execute commands concerning gradle)
Whenever I try ./gradlew (it shows me Permission denied).

**Comment by deepkrg17** [comment]
Use `sh gradlew` instead of `.gradlew`.

**Comment by deepkrg17** [comment]
Use `sh gradlew` instead of `./gradlew`.

**Comment by Precious-ab** [comment]
Thank You
