### ISSUE TITLE
[Feature]: Allow to copy app to sd card

### ISSUE THREAD

**Issue by bassem-saeed** [AndroidIDEOfficial/AndroidIDE#988]
### Feature description

I want you to add the ability to move AndroidIDE app to sd card and thansk

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Full read-write access to external SD cards and USB drives is available only on rooted devices.

We can't add this feature.
