### ISSUE TITLE
[Feature]: Add package name and file type automatically when creating a new file 

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#990]
### Feature description

There could be an option when creating a new file to automatically generate the package name and which type of file like class, object, interface and it generate a preset like in Android Studio, this would help save time and avoid some errors when I try to guess the package name 

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Isn't this feature already available? When creating a new Java file, you can choose if you want to create a class, interface, enum or an activity. The package name is generated based on the directory in which the file is created.

<img src="https://github.com/AndroidIDEOfficial/AndroidIDE/assets/46931079/d4250e31-3bc4-4086-bc71-36195d8ec786" width="250" alt="New Java class dialog"/>

**Comment by Rafael2616** [comment]
Wow , it's exactly something like that, but it doesn't show up in my project with Kotlin. But good to know it already exists

**Comment by Rafael2616** [comment]
Wow , it's exactly something like that, but it doesn't show up in my project with Kotlin. But good to know it already exists

**Comment by itsaky** [comment]
It isn't available for Kotlin at the moment. It'll be added when we add Kotlin LSP.
